### ISSUE TITLE
Crash when trying to use a info reader

### ISSUE THREAD

**Issue by thesimplemajority** [BevoTechPack/BevoTechPack#1002]
When I attach a info reader from practical logistics to a vanilla furnace and try to open the gui the game crashes with the following report. The inventory reader seems to be working without issues. I also tested this with a iron furnace from ic2 (non powered version) and got the same result when I tried to access the gui for the info reader. I have not tested the energy reader or the liquid reader because I have no energy production or liquid storage yet.

http://pastebin.com/EQdJQ9tA

**Comment by b0bst3r** [comment]
Will be added to next update

**Comment by thesimplemajority** [comment]
Just to add in further research it seems when Mekanism updated to v9 there was a change in some of the code that practical logistics uses and that was causing the error. The latest version of practical logistics fixed this error.
