### ISSUE TITLE
Enriched Iron (Mekanism) can't be refined into Steel Dust

### ISSUE THREAD

**Issue by DanmakuDan** [BevoTechPack/BevoTechPack#1003]
The output of the Metallurgic Infuser (Mekanism) gives Enriched Iron Dust, but placing it back in Metallurgic Infuser + Coal doesn't give Steel Dust. It looks like the item overlaps with IC2.
![2016-06-08_17 02 01](https://cloud.githubusercontent.com/assets/9610892/15912577/d6760030-2d9a-11e6-8a2d-b0d743ddf9ec.png)

**Comment by b0bst3r** [comment]
It can the recipe was changed, you use diamond dust with the enriched iron to make steel doing it that way.  This is an intended change to make the easy steel making from Mekanism harder.
