### ISSUE TITLE
Random Crash on World Loading Screen

### ISSUE THREAD

**Issue by Wolfsthrope** [BevoTechPack/BevoTechPack#1006]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure.

Bevo Tech Pack Version :- Most recent as of 14/06/2016

### Description of issue/bug

Whenever I try to load my world, it straight up crashes.  This was not happening the day before, and no updates have been installed since.  

### Steps to reproduce the issue/bug

Tried rolling back the update and launching it again, same result

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

http://pastebin.com/Db6X3uGw

Questions:

Did you add any additional mods? - No
Do you use optifine? - No
Did the problem appear in single player or on a server? - Singleplayer

**Comment by b0bst3r** [comment]
Hmm it would seem the HQM data is corrupt on your game, try this please and it will tell me if it's your save hqm data or the original hqm data.  Try making a new world and see if it loads?

**Comment by Wolfsthrope** [comment]
If it does...does that mean the old world is corrupt?

**Comment by Wolfsthrope** [comment]
Okay, new world created and loaded succesfully

**Comment by b0bst3r** [comment]
No it means your HQM data is your game save needs deleting.   In the saves folder, locate your world, open that folder up and you should see a "HardcoreQuesting" folder, go in there and rename the players.dat to something else and try reloading your world.

**Comment by b0bst3r** [comment]
Then when you load your world go into LAN mode and turn on cheats, then type /hqm edit this gives you an OP book to which you can auto complete the quests that you already did.

**Comment by Wolfsthrope** [comment]
I never did any quests...XD  But I will delete the HQM data

**Comment by Wolfsthrope** [comment]
IT WORKED!  HOLY SHIT IT WORKED!!! THANK YOU YOU BEAUTIFUL HUMAN BEING XD

The reason I'm freaking out about this is because I'm doing a YouTube series on it, and I REALLY needed to get it fixed :D  Thanks so much!

**Comment by b0bst3r** [comment]
:D
