### ISSUE TITLE
[Suggestion] TechReborn

### ISSUE THREAD

**Issue by DrStage** [BevoTechPack/BevoTechPack#1007]
Hello!

I haven't found a request yet, I hope it is ok to open this "issue".

I loved the old 1.4.7 GregTech, imho it was one of the best tech-mods created. Apparently I am not alone with this opionion, so TechReborn, a refurbished version of GT 2.4 was created.

I think it would fit in quite well in BTP:Reborn, maybe you'll find some time to test it (and integrate it)

Keep up the good work,
Cheers!

**Comment by b0bst3r** [comment]
What does Tech Reborn offer that we don't already have?
