### ISSUE TITLE
My game crashes everysingle time i play multiplayer

### ISSUE THREAD

**Issue by pauloAQS** [BevoTechPack/BevoTechPack#1008]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure.

Bevo Tech Pack Version :- 

### Description of issue/bug

Everytime I log in into the server I play for a little bit I and then it crashes then it just gets stuck on the loading screen and the it crashes when I am joining the server

### Steps to reproduce the issue/bug

Play, and then it just crashes after like 5 min of playing, then I relog and then it doesn't even load the gamescreen it just crashes

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://pastebin.com/NibEpn61
Questions:

Did you add any additional mods? - no
Do you use optifine? - no 
Did the problem appear in single player or on a server? - appeared on a server

**Comment by b0bst3r** [comment]
This error doesn't point to anything in particular, can you try without thermos/cauldron?

**Comment by pauloAQS** [comment]
what do you mean as in thermos/cauldron?

**Comment by pauloAQS** [comment]
b0bst3r the problem was fixed  and thanks a lot the issue was that I was using some mods that were not enabled in the server, which made my game crash when it encountered items with same id numbers...

Thanks for your help :3
