### ISSUE TITLE
Ores not Spawning

### ISSUE THREAD

**Issue by Miflof** [BevoTechPack/BevoTechPack#1009]
The Problem is as simple as gamebreaking,  some ores are not spawning, like Osmium from Mekanism or Sulfur from Magneticraft. I tried to load new worlds, but the problem is still there.
is this on purpose?

**Comment by b0bst3r** [comment]
Which version?

**Comment by b0bst3r** [comment]
Confirmed Osmium is present in Beta-U and Magneticraft sulfur is turned off (intended) use railcraft sulfur (found in extreme hills biomes by lava pools).
