### ISSUE TITLE
[FYI] Magneticraft Patcher

### ISSUE THREAD

**Issue by Belgabor** [BevoTechPack/BevoTechPack#1010]
Since you guys had issues with MagnetiCraft as well, this may help you (no guarantees)

https://github.com/Belgabor/MagneticraftPatcher/releases/tag/Release_v0.1

**Comment by b0bst3r** [comment]
Thanks any chance you can fix the crafter dupe too?

https://github.com/cout970/Magneticraft-API-and-Issues/issues/80

**Comment by Belgabor** [comment]
I have taken a look, that is a lot more complex (at least for me) than fixing the other stuff, and that is provided the way I think it can be fixed works. Would be pretty trivial to try if I had access to the source code, but not with ASM patching. In that light and the plentiful availability of crafters from other mods, I'm afraid the effort/use ratio doesn't work out for me.
Maybe if I have a lot of time to spare and want to take on the challenge, but don't hold your breath.

**Comment by b0bst3r** [comment]
Source code - https://bitbucket.org/cout970/magneticraft, can go ahead and fork it if you want Cout already gave permission for someone to edit.

**Comment by Belgabor** [comment]
Ack, wish I had known that earlier =)
I'll take a look.

**Comment by b0bst3r** [comment]
Mod added to BetaV, let me know if you decide to re-release an updated mod version please.

**Comment by Belgabor** [comment]
Dang, I just did =)
Please test with the circumstances reported here, but version 0.2 should fix at least the crafter bug reported as  cout970/Magneticraft-API-and-Issues#80
