### ISSUE TITLE
unable to craft the atomic disassembler

### ISSUE THREAD

**Issue by lAimBotl** [BevoTechPack/BevoTechPack#1013]
Bevo Tech Pack Version :-  BetaV

unable to craft/see atomic disassembler recipe in nei

### Steps to reproduce the issue/bug: open nei search up "atomic disassembler", you will see it in nei but you can't get its recipe

Questions:

Did you add any additional mods? - no
Do you use optifine? -no
Did the problem appear in single player or on a server? -  both

**Comment by b0bst3r** [comment]
Reinstall BetaV

**Comment by lAimBotl** [comment]
Thanks that fixed it
