### ISSUE TITLE
Game freezes on Forge Loader

### ISSUE THREAD

**Issue by xenocide12** [BevoTechPack/BevoTechPack#1014]
Bevo Tech Pack Version :- BTP-Reborn-BetaP-Hotfix

Description of issue- Forge loads up to 7/7 1/12 3/3, then freezes indefinitely.  I've increased RAM, turned off my Antivirus, updated my Java & Intell Driver, ran the jarfix application and edited my splash.properties file to enabled=false.  No dice.  This also appears to be a problem with other modpacks, I've tried loading Sky Factory 2 as a test, but again, the game froze on the forge load screen.

crashlog-http://paste.atlauncher.com/view/02908d1c

Did you add any additional mods? - Only the recommended mods
Do you use optifine? - Unless it was included in the pack- no
Did the problem appear in single player or on a server? - Issue occurs upon loading

**Comment by Watschman** [comment]
Link does not work please post another working one.

**Comment by b0bst3r** [comment]
Can't do anything without a crash log and issue unresponded to after 22 days probably means he either got it sorted or is playing something else.
