### ISSUE TITLE
Tinkers issue

### ISSUE THREAD

**Issue by TaskForce666** [BevoTechPack/BevoTechPack#1015]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- beta v5
### Description of issue/bug

cant craft any tinkers constructs items on server but sp is fine
### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - all suggested
Do you use optifine? -no
Did the problem appear in single player or on a server? - private server

**Comment by b0bst3r** [comment]
Which items?

**Comment by TaskForce666** [comment]
havent been able to make any tc items so far..

**Comment by b0bst3r** [comment]
WHICH ITEMS BE MORE SPECIFIC....

**Comment by TaskForce666** [comment]
i cant start tc cause i cant make and begging game items so far tryed the crafting station, stone rods, starting book..

**Comment by b0bst3r** [comment]
Sounds to me like the server doesn't have tinkers construct on it.

**Comment by TaskForce666** [comment]
so try to manually install it?

**Comment by ranger135xp** [comment]
Yeah it sounds like TiCo isn't installed, but you wouldn't be able to connect to said server unless you're using "open to LAN". Are you running a separate server or simply opening your world to LAN? Also, I had an issue with MFR not allowing me to craft on my server but it worked in SSP. A restart solved it as the config was fine.
