### ISSUE TITLE
Issues with modpacks

### ISSUE THREAD

**Issue by Trollebob** [BevoTechPack/BevoTechPack#1016]
Hello.

Bevo Tech Pack Version : BetaV-NC?

Just went to download this pack, but I can't find it in the instancelist? Has it been discontinued? I just got my host to install this modpack for me on my server, went to get the instance to be able to log on and it's magically disappeared from the list..

**Comment by Clueless4ever** [comment]
there is problem with ATlauncher, they somehow removed latest versions from list. I saw update, let it download and now I'm 2 versions behind and can't play my save...
We need to wait until the V version is back...

**Comment by b0bst3r** [comment]
Duplicate see https://github.com/BevoTechPack/BevoTechPack/issues/1017
