### ISSUE TITLE
Version BetaV or BetaV-NC not available on the launcher.

### ISSUE THREAD

**Issue by ftog-thorgal** [BevoTechPack/BevoTechPack#1017]
We insalled BetaV-NC on our test server and wanted to push it out to the public server today but we noticed that we can't update our clients to V-NC.

When I try to install a new instance of BTP these are the choices I have (only showing latest):
![Options](http://i.imgur.com/IgQtnOZ.png)

Any reason that U, U-NC, V, and V-NC are not available?

**Comment by b0bst3r** [comment]
It's a problem with Atlauncher affecting lots of packs, although I'm told if you change the server to Master Test Server the packs become available again.

ATLauncher -> settings -> Network -> "download server" -> select "Master Server (Testing Only)" -> save -> close launcher -> start again

Some have pointed out that you need to run the atlauncher as administrator to get that option.

**Comment by b0bst3r** [comment]
Should be all fixed now
