### ISSUE TITLE
Rocket Crafting Quests

### ISSUE THREAD

**Issue by Yurdol** [BevoTechPack/BevoTechPack#1018]
Bevo Tech Pack Version :- BetaV-NC

The quests for building the rockets don't consider any rocket with cargo space added as completing the quest.  Not sure if it's possible to detect 1 of 4 possible combinations but it's a bit frustrating to finally craft a rocket and then not be able to progress the quests because you added cargo space.

Did you add any additional mods? - No
Do you use optifine? - No
Did the problem appear in single player or on a server? - single player

**Comment by b0bst3r** [comment]
I've had this come up before and I tested it and it worked, did you click the button in the quest to detect it?

**Comment by b0bst3r** [comment]
Should be fixed in next update BetaW
