### ISSUE TITLE
BTP reborn BETA V - no osmium generating 

### ISSUE THREAD

**Issue by nunavailabul** [BevoTechPack/BevoTechPack#1019]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- BTP reborn BETA V

All extra mods, except compact machines are being used.
Server pack downloaded from launcher.

### Description of issue/bug

Osmium is not generating on SMP

### Steps to reproduce the issue/bug
I have mined at all levels in a 3x3 for a REALLY long time.
I have attempted to get Osmium by going into creative, getting an osmium ore for a digital miner filter - no osmium found by the miner.

Questions:

Did you add any additional mods? - no
Do you use optifine? - no
Did the problem appear in single player or on a server? - server

**Comment by b0bst3r** [comment]
Did you upgrade from a previous version ot install straight from betaV?

**Comment by nunavailabul** [comment]
It was a straight install

**Comment by b0bst3r** [comment]
I installed a brand new server of BetaV (from the launcher) installed a brand new client of BetaV - connected both together, ran the clearblocks command (clears 100x100 blocks all the way to bedrock) and found osmium.  http://i.imgur.com/XqFVDbI.jpg

**Comment by nunavailabul** [comment]
:/ this gives me sad face.  Do you know of a way to retrogen a specific ore?  It is definitely not present on this world.
