### ISSUE TITLE
Sever lag issue

### ISSUE THREAD

**Issue by jtcode42** [BevoTechPack/BevoTechPack#1023]
Bevo Tech Pack Version :- Reborn BetaV

The issue
Framerate is below 10 FPS on my single player world

How it happened
Have a computer like mine
Turn down all graphics settings
Only enable: OpenModularTurrets, Fastcraft, and AE2 stuff

I do not use Optifine.

**Comment by jtcode42** [comment]
Title: Severe*
Whoops

**Comment by b0bst3r** [comment]
I can't really help you with this without a crap ton more information, such as your PC specs, video card driver versions, java settings and even with all that information I probably stillc an't help you.  Just avoid making things which cause a lot of FPS, like walls of barrels and storage drawers.
