### ISSUE TITLE
Pack Fails to Install due to an incorrect JourneyMap Checksum 

### ISSUE THREAD

**Issue by NTorname** [BevoTechPack/BevoTechPack#1026]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- BetaV (other versions I have tried don't work either)

### Description of issue/bug
The Journeymap checksum is a mismatch

### Steps to reproduce the issue/bug
Make a new instance of the modpack

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://pastebin.com/y7HSuSgx
Questions:

Did you add any additional mods? - no
Do you use optifine? - no
Did the problem appear in single player or on a server? - neither, can't load the game

**Comment by b0bst3r** [comment]
I can see the error but don't know why its happening.  Download Journeymap here http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download and place it in your atlauncher\downloads folder to temporarily resolve this.

**Comment by b0bst3r** [comment]
Should be fixed in BetaV and W packs, leaving this here as this is a bigger problem across all packs to do with ATLauncher

**Comment by NTorname** [comment]
Thanks for the quick fix.
