### ISSUE TITLE
tinkers does not work with the metal tritium

### ISSUE THREAD

**Issue by parko12345** [BevoTechPack/BevoTechPack#1031]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug
The issue is that the metal tritium from matter overdrive mod can not be cast into tinkers tool parts.  

Even though there is the tools and parts in nei 
### Steps to reproduce the issue/bug
Try to cast anything with tritium

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - no
Do you use optifine? - no
Did the problem appear in single player or on a server? -  single

**Comment by bookerthegeek** [comment]
Easily fixable with some scripts. Any other metals not castable?

**Comment by bookerthegeek** [comment]
@b0bst3r did you want a script for this?

**Comment by b0bst3r** [comment]
Oh thought this was in your last script update, yes please.

**Comment by bookerthegeek** [comment]
Non issue. Work fine for me both single player and on a server. I would suggest @parko12345 to reinstall your pack.

**Comment by bookerthegeek** [comment]
@b0bst3r You can close, it is a non issue.
