### ISSUE TITLE
Duplicate Ores

### ISSUE THREAD

**Issue by imkSushi** [BevoTechPack/BevoTechPack#1033]
Bevo Tech Pack Version :- BTP-Reborn-BetaW

### Description of issue/bug

Both Thermal Foundation and NuclearCraft spawn their Silver and Tin ores (this may be true for other ores, but after some gameplay, this is all I've come across).

### Steps to reproduce the issue/bug

Generate a world, and have a look around some caves.

### Possible Solution

Disable NuclearCraft (Tin and Silver) ores spawning in its config.
**And/Or**
Adding in 'Ore Dictionary Converter' Mod.

Questions:

Did you add any additional mods? - Yes (Optifine)
Do you use optifine? - Yes
Did the problem appear in single player or on a server? - Singleplayer

**Comment by b0bst3r** [comment]
Yeah this is my fault you're stuck with it unless you want to restart your map, I already fixed this ready for next build.  So BetaX will have the fixed configs.
