### ISSUE TITLE
Magneticraft Crushing Table Particles on modded ores

### ISSUE THREAD

**Issue by imkSushi** [BevoTechPack/BevoTechPack#1034]
Bevo Tech Pack Version :- BTP-Reborn-BetaW

### Description of issue/bug

Using the Magneticraft Crushing Table on ores can show the wrong particles if there is another mod containing the same ore but with a different texture.

It seems to show the particles of the first ore of the type in the NEI menu.

### Steps to reproduce the issue/bug

Use the Magneticraft Crushing Table with most modded ores (Most noticeable on the (White coloured, Red particled) Zinc Ore.

### Possible Solutions

Disable the other unobtainable ores (textures) from the game completely

Questions:

Did you add any additional mods? - Yes (Optifine)
Do you use optifine? - Yes
Did the problem appear in single player or on a server? - Singleplayer

**Comment by b0bst3r** [comment]
I doubt there's anything we can do about this magneticraft is no longer supported unless @belgabor can patch it?

**Comment by Belgabor** [comment]
I took a quick look, it isn't obvious to me why that happens, it keeps the correct itemstack until the particles get spawned. So I have no idea how to fix it, which makes trying to more effort than I'm willing to put into what I consider a very minor issue I'm afraid.

**Comment by b0bst3r** [comment]
Ok thanks for looking :)
