### ISSUE TITLE
Aluminium Processing

### ISSUE THREAD

**Issue by imkSushi** [BevoTechPack/BevoTechPack#1036]
Bevo Tech Pack Version :- BTP-Reborn-BetaX-NC
### Description of issue/bug

Aluminium/Aluminum does not have shards, crystals, and various other semi-processed versions. This makes it impossible to process Aluminium with Mekanism ore processing.
### Steps to reproduce the issue/bug

Try processing Aluminum/Aluminium ore on a 3x or 4x or 5x Mekanism ore processing setup.
### Possible solutions

Probably something in the AOBD config. Otherwise you could manually add it in using Minetweaker or something.

Questions:

Did you add any additional mods? - Yes (Veinminer)
Do you use optifine? - No (Used to, but it crashed the game a lot)
Did the problem appear in single player or on a server? - Single Player

On a slightly separate note, Aluminium/Aluminum Ore spawns very very rarely, and seemingly only in Extreme Hills biomes. This may be a bug. (World generated in BetaW)

**Comment by bookerthegeek** [comment]
Fixable with aobd config and minetweaker.
