### ISSUE TITLE
Rf generator doesn't give energy away

### ISSUE THREAD

**Issue by Elias2419** [BevoTechPack/BevoTechPack#1037]
Bevo Tech Pack Version :- 

### Description of issue/bug

No generator (extra utilities) give energy to machines like the pulverizer from the thermal expansion mod. Furthermore, the steam dynamo (thermal expansion) doesn't give energy away, too. What can I do? I cannot power any machines

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions: What can I do?

Did you add any additional mods? No
Do you use optifine? No
Did the problem appear in single player or on a server? Single player

**Comment by b0bst3r** [comment]
How are they connected?
What version of the pack are you playing?

**Comment by Elias2419** [comment]
Version: Bevo's Tech Pack BTP-12-Full

I put the steam dynamo on top of the pulverizer, because they weren't the right conduits. The generators (extrautilities) i tried to connect with an energy pipe and later with a cobblestone kinetic pipe. Non of them worked.

**Comment by b0bst3r** [comment]
That version is like years old and no longer supported sorry, next time try placing the generator right next to the pulverizer  or if using buildcraft energy pipes you may need a wooden one from the generator.
