### ISSUE TITLE
Mods loading crash

### ISSUE THREAD

**Issue by ImSprizz** [BevoTechPack/BevoTechPack#1038]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :-Reborn BetaV  X

### Description of issue/bug
I start the Mod and its loading the Mods and then at the end it crashes

### Steps to reproduce the issue/bug
Reinstall the Launcher

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://pastebin.com/8nWZ0iNT
Questions:
How can i delete this bug?
Did you add any additional mods? - No
Do you use optifine? -No
Did the problem appear in single player or on a server? - No

**Comment by b0bst3r** [comment]
You need Windows 64 bit you have 32 bit
You need Java 64 bit you have Java 32 bit
You are giving Java 1GB RAM it needs at least 4GB RAM

You can't allocate 4GB RAM because you have 32 bit Java and a 32 bit OS 

You basically cannot run modded Minecraft on that operating system, sorry.
