### ISSUE TITLE
[Suggestion] Make Extra Utilities colored blocks chiselable

### ISSUE THREAD

**Issue by kimfy** [BevoTechPack/BevoTechPack#1040]
Colored Stone (White Frequency) -> Chisel -> Colored Stone Bricks (White Frequency) and the other way around, for all colored blocks.

Thanks :+1:

**Comment by lilmoefow** [comment]
Want me to make this script?

**Comment by b0bst3r** [comment]
You can...already have was going to look at the existing recipes first but got problems with the new build which is holding back all the "cosmetic" updates.

**Comment by b0bst3r** [comment]
In Release 1.0
