### ISSUE TITLE
crash pls fix

### ISSUE THREAD

**Issue by austinclover** [BevoTechPack/BevoTechPack#1041]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- Reborn-BetaX-hotfix

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com) http://paste.atlauncher.com/view/2054345c

Questions: how do i fix this

Did you add any additional mods? - yes 
Do you use optifine? - yes
Did the problem appear in single player or on a server? - none didnt let me in the game

**Comment by b0bst3r** [comment]
Need this **USERSDIR**\Instances\BevosTechPack\crash-reports\crash-2016-08-02_19.11.27-client.txt

**Comment by lilmoefow** [comment]
Its an issue with OpenGL.  Update your videocard drivers and try to launch again.

http://pastebin.com/L8sbBnBB 
That is a small portion of his "crash log"(fml log) that he pasted.   

" OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread."
