### ISSUE TITLE
Quarry and Machine Block Share name

### ISSUE THREAD

**Issue by lilmoefow** [BevoTechPack/BevoTechPack#1042]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- xnc-hotfix (all current versions really)

### Description of issue/bug
Making this for future reference.  The Buildcraft quarry shares the same (block naming structure?) as the Nuclearcraft Machine Base. For example

BuildCraft|Builders:machineBlock
NuclearCraft:machineBlock
 
"machineBlock" is Causing the Builcraft quarry to be named Machine Base.   The script being used in the pack to rename the Quarry back to "Quarry" also caused the Machine Base from Nuclear Craft to be Renamed ( you following me here)

I've found that the name over write is happening cause Buildcrafts en_US.lang has this line in it 

"tile.machineBlock.name=Quarry"

and the Nuclear craft en_US.lang file has this line in it

"tile.machineBlock.name=Machine Base"

Nuclear craft is loaded after Buildcraft which overwrites the name.    The GitHubs en_US.lang file for both mods do not match the ones that are distributed in the pack. 

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? -

**Comment by b0bst3r** [comment]
Aha thanks I wondered why the Quarry ended up being called machine block in the first place.  Also yeah NuclearCraft has been/in the process of being updated to 1.9 so that file has changed.

**Comment by b0bst3r** [comment]
Toying with the idea of updating NuclearCraft in the next release but combining the pack split back into one.
