### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by queni01** [BevoTechPack/BevoTechPack#1043]
Bevo Tech Pack Version : BTP-Reborn-BetaX-Hotfix

crashed when i tried to load the Singleplayer world.

http://paste.atlauncher.com/view/d2a28b34

**Comment by b0bst3r** [comment]
Your HQM data in your game save needs deleting. In the saves folder, locate your world, open that folder up and you should see a "HardcoreQuesting" folder, go in there and rename the players.dat to something else and try reloading your world.

Then when you load your world go into LAN mode and turn on cheats, then type /hqm edit this gives you an OP book to which you can auto complete the quests that you already did.

**Comment by queni01** [comment]
thanks :dancers:
