### ISSUE TITLE
Nuclearcraft Fusion reactor needs too much energy to start

### ISSUE THREAD

**Issue by zeromic** [BevoTechPack/BevoTechPack#1044]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug

Known Bug in Nuclearcraft 1.6:
https://github.com/turbodiesel4598/NuclearCraft/issues/28

Possible Fix:

Update Nuclearcraft to 1.7

### Steps to reproduce the issue/bug

Try to startup a Fusion Reactor.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? SP

**Comment by b0bst3r** [comment]
You missed this info and I need it - Bevo Tech Pack Version :-

**Comment by zeromic** [comment]
The Newest Version on AT-Launcher "BTP-Reborn-BetaX-Hotfix(Mi..."

The AT-Launcher cuts off the last part of the Version name.

**Comment by b0bst3r** [comment]
OK well you really need to be using Veta-X-NC-Hotfix as the -NC version has NuclearCraft updated in it BUT ...

Updating from a non NC version to a NC version requires you to do 2 things AND YOU MUST DO THEM:-

1) Turn off all Fission Reactors
2) Break all Fusion Reactors

If you don't the Fission reactors WILL explode as the calculations have changed, new blocks have been added and your existing reactors will most definitely (probably) explode.

Fusion reactors have changed and they no longer form the same way as the version in the non-nc one.

I emplore you to read this http://bevolj.com/?p=5670 before updating.

You will have to pick the -NC version of Bevo's Tech Pack from the dropdown box within atlauncher
