### ISSUE TITLE
No Use for AOBD Wolframium

### ISSUE THREAD

**Issue by bookerthegeek** [BevoTechPack/BevoTechPack#1046]
Bevo Tech Pack Version :- Beta-X-Hotfix

### Description of issue/bug
Wolframium has no real use other than one. 

Suggest:
- Turn off Wolframium in the AOBD config.
- Ore dictionary the Tungsten ore from GalaxySpace and Magnetic Craft.
- Ore Dictionary the Tungsten Ingots also.

**Comment by b0bst3r** [comment]
Not going to ore dict tungsten with Galaxy Spaces as that means space travel progress is compromised by having tungsten in the OW.

**Comment by bookerthegeek** [comment]
As I'm not familiar with Galaxy Space, what is the use of that tungsten?

**Comment by b0bst3r** [comment]
In the pack its a way to alternate steel and it's part of the HQM storyline.

**Comment by bookerthegeek** [comment]
Gotchya.
