### ISSUE TITLE
Update Chisel2

### ISSUE THREAD

**Issue by lilmoefow** [BevoTechPack/BevoTechPack#1053]
Please update Chisel2 to the most recent and updated version for 1.7.10 please.

https://mods.curse.com/mc-mods/minecraft/235279-chisel

**Comment by b0bst3r** [comment]
Yeah about that, when I updated the pack I put the wrong chisel version in so updating to that version is likely to remove all chisel blocks from the world.  More testing required when I get chance.

**Comment by b0bst3r** [comment]
Yeah np updating this nothing lost should be in next update.
