### ISSUE TITLE
Bevotech pack Server crash

### ISSUE THREAD

**Issue by rushlionheart** [BevoTechPack/BevoTechPack#1054]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- Bevo's Tech Pack BTP-Reborn-BetaX-Hotfix

### Description of issue/bug
java.lang.RuntimeException: Could not spawn mod entity ModID: NuclearCraft EntityID: 29 at ( -162.5,38.0, 183.5)
This happened right after hungry node killed us.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com) http://pastebin.com/Ri2EZLdh tell me if you need more
Questions:

Did you add any additional mods? - only the optional mods asked
Do you use optifine? -no
Did the problem appear in single player or on a server? - server, me and my friend run it

**Comment by b0bst3r** [comment]
Did you change the server config, in particular EnderZoo, like disabling the dirt mobs?

**Comment by b0bst3r** [comment]
<@b0bst3r> rushlionheart_ did you change the enderzoo config on the server, like disable the dirt mobs?
<rushlionheart_> yes

re-enable the slime on the server and change this on the server to 0    D:direSlimeChance=0.2

**Comment by rushlionheart** [comment]
yes
