### ISSUE TITLE
[BC Transport] Golden Transport Pipe Bug / Quarry Bug

### ISSUE THREAD

**Issue by Ohnezahn777** [BevoTechPack/BevoTechPack#1056]
Bevo Tech Pack Version :- BTP-Reborn-BetaX-Hotfix

### Description of issue/bug
Placing a Golden Transport Pipe (e.g. connecting a quarry with a chest) may cause a minecraft crash.
This crash also occurs while a quarry is used.

### Steps to reproduce the issue/bug
Place Golden Transport Pipes until the crash occurs (takes a few attempts).
/ Turn on a quarry.

### Link to crashlog
http://pastebin.com/ZJiC6h5C

Questions:

Did you add any additional mods? - Optifine_1.7.10_HD_U_D6
Do you use optifine? - Yeah... Optifine_1.7.10_HD_U_D6
Did the problem appear in single player or on a server? - Both

**Comment by b0bst3r** [comment]
Which quarry?

**Comment by Ohnezahn777** [comment]
From BC Builders

**Comment by b0bst3r** [comment]
Try without Optifine but that quarry is disabled in the pack.

**Comment by Ohnezahn777** [comment]
Is there another quarry I did not see before? O.o

**Comment by b0bst3r** [comment]
There are several less destructive quarries in the pack:-

Magneticraft - Miner
RFtools - Builder with Quarry cards
Immersive Engineering - Excavator
Extra Utilities - EnderQuarry
Mekanism - Digital Miner
