### ISSUE TITLE
Portal Gun Mod Crash

### ISSUE THREAD

**Issue by JiiSu** [BevoTechPack/BevoTechPack#1058]
I tried to install the Portal Gun Mod but every time i want to use the Portal Gun (in the hotbar) my game freezes and the game crashed. (No Error Log) Please Help. I tried to disable the sounds but it crashes again. 

These are the Mods is need to play the Portal Gun Mod
Portal-Gun-Mod-1.7.10
iChunUtil-4.2.2

**Comment by b0bst3r** [comment]
You need the sound pack from here http://ichun.me/mods/portalgun/download/
