### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by Chaos02** [BevoTechPack/BevoTechPack#1060]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- newest

### Description of issue/bug
i cant install optifine per the launcher or in the directory. other things work, but optifine is just out of the game...

### Steps to reproduce the issue/bug
try to install optifine

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - Rogueliksdungeons, 
Do you use optifine? - thats the problem? i tried...
Did the problem appear in single player or on a server? - both

**Comment by b0bst3r** [comment]
Optifine in 1.7.10 is highly incompatible with modded minecraft, even if you get it to work when you get to a certain point it will start causing rendering crashes.
