### ISSUE TITLE
Server joinen not possible, NEI-crash

### ISSUE THREAD

**Issue by SchildiGames** [BevoTechPack/BevoTechPack#1061]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- BetaX-Hotfix

### Description of issue/bug
When I want to join my server, I will be kicked "A fatal error has occured, this connection is terminated". I fixed this bug: Immersive Engeniering deinstalled, but then NEI has a bug, it crashes when I want to see a recipe

### Steps to reproduce the issue/bug
Deinstall Immersive Engeniering and click on an Item in NEI.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)http://pastebin.com/QDKNHQek

Questions: Can you fix both bugs?

Did you add any additional mods? - Immibiscore, Dimensional Anchor
Do you use optifine? - yes
Did the problem appear in single player or on a server? - server

**Comment by b0bst3r** [comment]
Fatal errors connecting to a server usually means the server and clients do not have the exact same mods loaded.

You added computercraft and it's that which is crashing.

**Comment by SchildiGames** [comment]
I installed the pack and server normaly and the versions of the mods are the same, but the crash is also there.

**Comment by b0bst3r** [comment]
BigReactors-0.4.3A.jar <- Not a mod in BTPR
ComputerCraft1.75.jar <- Not a mod in BTPR
VeinMiner-1.7.10_0.31.4.unknown.jar <- Not a mod in BTPR

java.lang.NullPointerException: Updating screen events
    at dan200.computercraft.shared.turtle.items.TurtleItemFactory.create(TurtleItemFactory.java:58)

Crash caused by ComputerCraft, remove it or get whoever added it to resolve the issue it's not my problem.
