### ISSUE TITLE
Disable auto sapling plant

### ISSUE THREAD

**Issue by LordImperator** [BevoTechPack/BevoTechPack#1062]
Bevo Tech Pack Version : Bevo's Tech Pack BTP-Reborn-BetaV for Minecraft 1.7.10

I want to disable, that tree-saplings auto plant them self , when left on grass.

Did you add any additional mods? Veinminer, Extra Bees
Did the problem appear in single player or on a server? On Both 

Thanks for your help!

**Comment by b0bst3r** [comment]
scottstweaks.cfg 

        B:doPlantGrowable=true 

Change to false
