### ISSUE TITLE
World Crash when trying to join.

### ISSUE THREAD

**Issue by Crazyman92417** [BevoTechPack/BevoTechPack#1063]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- Bevo's Tech Pack (Bevo's Tech Pack BTP-Reborn-BetaX-Hotfix)

### Steps to reproduce the issue/bug
1. Click "Play" on Bevo's Tech Pack in Instances Tab.
2. Wait for it to load then go to single player.
3. Click on world and press play (this is when the crash happens).

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://pastebin.com/FdQw3CR8
Questions:
Is there a way to fix it without deleting the world?
Did you add any additional mods? - AE2 Stuff, Compact Machines, Decocraft, FastCraft, Open Modular Turrets, Roguelike Dungeons, Ruins.
Do you use optifine? - No
Did the problem appear in single player or on a server? - Single player

**Comment by b0bst3r** [comment]
Tried a new world?

Seems like there's corruption in your save somewhere, try and new one and see if that works, if it doesn't try reinstalling the pack to a new instance.

**Comment by Crazyman92417** [comment]
I created a new world and it worked but I want to know if there is a way to get my old world running again. I spent many hours on the world and I really don't want to have to re do everything all over again.

**Comment by b0bst3r** [comment]
In your save\worldname folder is a jabba folder, try renaming it or try renaming the files inside one at a time to figure out which is causing the issue.

**Comment by Crazyman92417** [comment]
I renamed the jabba folder and I tried getting into my old world and it worked. I don't know if renaming it helped at all but thank you so much if that was the case. I'll try getting on tomorrow to see if it still works.
