### ISSUE TITLE
Der Server geht nicht mehr ich komme drauf aber dann flieg ich wieder runter bitte um hilfe 

### ISSUE THREAD

**Issue by andre111103** [BevoTechPack/BevoTechPack#1065]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- BetaX X-NC Hotfixes

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - no
Do you use optifine? -no
Did the problem appear in single player or on a server? - on a server

**Comment by b0bst3r** [comment]
Sorry I don't speak any german and the translation makes little sense.
