### ISSUE TITLE
Buildcraft Quarry has no recipe in the NEI

### ISSUE THREAD

**Issue by erinic04** [BevoTechPack/BevoTechPack#1066]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- BetaX

### Description of issue/bug
Buildcraft Quarry has no recipe in the NEI.

### Steps to reproduce the issue/bug
Type quarry into the text box at the bottom of the screen and press recipe over it

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
no crash
Questions:

Did you add any additional mods? - no
Do you use optifine? -no
Did the problem appear in single player or on a server? - single player

**Comment by b0bst3r** [comment]
It's disabled in the pack, use one of the many better alternative quarries.
