### ISSUE TITLE
Server Lagging allways

### ISSUE THREAD

**Issue by Lyror** [BevoTechPack/BevoTechPack#1067]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :-  BetaW

### Description of issue/bug
Hello,

My Server has always problems to update the machines. All Machines are lagging. Block breaks need one / two seconds. Fastcraft say sometimes: "Server is lagging 100xxx ms behind. Will 15xxx Ticks skipping".

When i run /cofh tps it tells me 100%

My Server:
Intel i5 2400 3,4 Ghz
8GB Ram (Minecraft have 6GB)
1TB HDD

I tried it on an i7 4790k 4,4 Ghz and 32GB Ram (Mincraft have 16GB Ram) the same Problem

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - Yes. Draconic Evolution Version 0.9.5 -beta and Portalgun 4.0.0 -beta 6
Do you use optifine? - no
Did the problem appear in single player or on a server? - yes

**Comment by b0bst3r** [comment]
I can't fix your server problems, try something like Opis to narrow down the issue.
