### ISSUE TITLE
Can't install BTP MINI!

### ISSUE THREAD

**Issue by GotProblemsWBTP** [BevoTechPack/BevoTechPack#1068]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version : BTP-12 MINI BTP 11 MINI

### Description of issue/bug
Can't install it

### Steps to reproduce the issue/bug
Just install it with the ATLauncher

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://paste.atlauncher.com/view/566431c9

Questions:

Did you add any additional mods? - NO
Do you use optifine? - NO
Did the problem appear in single player or on a server? - EVEN BEFORE

**Comment by GotProblemsWBTP** [comment]
Oh i tested all Servers (EU/US in the Network Settings and Updated Java)

**Comment by b0bst3r** [comment]
Fixed, Curse doesn't allow direct downloads from curse websites anymore.
