### ISSUE TITLE
World load error

### ISSUE THREAD

**Issue by Pogofreak** [BevoTechPack/BevoTechPack#1069]
My main gameworld cant be loaded. The game craches evrytime. every other world can be loaded.

[crash-2016-08-17_15.39.03-server.txt](https://github.com/BevoTechPack/BevoTechPack/files/422701/crash-2016-08-17_15.39.03-server.txt)
  ty for help and sorry for bad English

**Comment by b0bst3r** [comment]
On your server in the world folder, there's a HardcoreQuesting folder, within that there are files.

Usually players.dat can get corrupted, I suggest renaming it to playersdat.old and that will fix the issue.  However there maybe a players.dat-backup in this folder which you can try renaming to players.dat and see if that still crashes or not.

If you have to remove/rename the players,dat file then everyone's HQM questline will get reset (if I remember correctly).

**Comment by b0bst3r** [comment]
I take it from the thumbs up it's fixed?
