### ISSUE TITLE
Problem with starting modpack; doesn't ever get past pre-initialization

### ISSUE THREAD

**Issue by HiImDuck** [BevoTechPack/BevoTechPack#1070]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- Beta-X hotfix

When I try to play the modpack, it fails to get past preinitialization,

There is no way to reproduce this; none of my friends experienced this issue downloading the pack, and none of them got errors like this even with all the same settings, even the same java updates as me.

Questions:

I used all optional extra mods but roguelike dungeons.
I do not use optifine.

Any solution?
Crashlog: 
http://pastebin.com/86sfu7z0
I do always see this error, if it means anything:

[10:07:49] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException

**Comment by b0bst3r** [comment]
java.lang.OutOfMemoryError: Java heap space
Memory: 5583312 bytes (5 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)

In Atlauncher click settings - Java/Minecraft and change Maximum Memory/Ram to 4096 and click save at the bottom.  There's no way on earth you can run modded Minecraft on 1GB RAM :)
