### ISSUE TITLE
I need help with my Server

### ISSUE THREAD

**Issue by Synetex** [BevoTechPack/BevoTechPack#1071]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :  BTP-Reborn-BetaX-Hotfix

### Description of issue/bug
The server wont start

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://pastebin.com/Rwsw2LyU
Questions:

Did you add any additional mods? No
Do you use optifine? Yes
Did the problem appear in single player or on a server? Server

**Comment by b0bst3r** [comment]
Do that (my reply) https://github.com/BevoTechPack/BevoTechPack/issues/1069

**Comment by Synetex** [comment]
Thank you so much!

**Comment by Synetex** [comment]
it Keeps Crashing for some reason.
Crash File: http://pastebin.com/ipTenySy

**Comment by b0bst3r** [comment]
https://github.com/aidancbrady/Mekanism/issues/3675

**Comment by b0bst3r** [comment]
@Synetex 
Method 1 - easy way to fix the issue
Edit config/forge.cfg ON YOUR SERVER
Change 
  B:removeErroringEntities=false
  B:removeErroringTileEntities=false
Both to true and restart your server, see if you can join, if you can, quit, change the above both back to false and then restart your server again (never play with the above set to true).

Method 2 - more difficult way to fix
Download world edit to your server https://minecraft.curseforge.com/projects/worldedit/files/2309699
Stop you server and make a backup of the world folder
Restart your server
In the server console type 
/pos1 -149,64,-72
/pos2 -149,64,-72
/replace 0
None of the above commands will echo anything back to you in the console, be careful doing this.

Both the above processes should make the offending block vanish from your game.

**Comment by bookerthegeek** [comment]
@Synetex Still having issues?

**Comment by b0bst3r** [comment]
No reply for over a month if this is still an issue, reply.
