### ISSUE TITLE
MC Bevo Inventar Bug

### ISSUE THREAD

**Issue by MaNa2002** [BevoTechPack/BevoTechPack#1073]
I have a little Problem on 23.8.2016 i started the atlauncher play on Bevo's Techpack and when i go on the World i see i have the books for new players and my Inventor was emty what is the Bug here is the Log : http://paste.atlauncher.com/view/bc8e7952

**Comment by b0bst3r** [comment]
I... I ..... I ... no idea get an OP to give you the books that was obviously a hiccup from the server.
