### ISSUE TITLE
Fluid Hopper Crash

### ISSUE THREAD

**Issue by bookerthegeek** [BevoTechPack/BevoTechPack#1074]
Bevo Tech Pack Version :```` BetaX-Hotfix ````

### Description of issue/bug
Placing any pipe from Logistics Pipes next to a MagnetiCraft Fluid Hopper will turn the Fluid Hopper into a Ticking Tile Entity resulting in a server crash or Single player CTD. The block will need to be world edited out to get the server to reload or the SP world able to load.

### Steps to reproduce the issue/bug
Place Fluid hopper next to Logistics pipe, or vise versa

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
- Server: [Crash Report]( https://gist.github.com/bookerthegeek/1defbeb6fdd463d070355f972aa62685)
- Single Player: [Crash Report](https://gist.github.com/bookerthegeek/78ba8247ab7359a09f01a5e8965a8f14)

### Questions:
Did you add any additional mods? 
- Server: Yes, Also Plugins
- Single Player: No

Do you use optifine? No on both Server and Single Player
Did the problem appear in single player or on a server?  Both

**Comment by b0bst3r** [comment]
Pinging @Belgabor is this something you can patch?

**Comment by bookerthegeek** [comment]
That would be nice if it could be as other then the ender io tank the hopper is the only non powered block able to fill bucket in a single block space.

Belgabor, if you need any more information, or testing, let me know please.
