### ISSUE TITLE
(1.7.10) Launcher crashes due to sharing ID 38

### ISSUE THREAD

**Issue by Jdawg215** [BevoTechPack/BevoTechPack#1075]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 1.7.10

### Description of issue/bug
My friend updated Nuclearcraft on his server to 1.7.10, and now every time i try to load into the game, it crashes and tells me ID slot 38 is sharing something with MatterOverdrive.

### Steps to reproduce the issue/bug
1. Load up launcher
2. Wait till stage 6
3. Crash.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://pastebin.com/MLAZKvB4
Questions:

Did you add any additional mods? - Nothing addition, only updated Nuclearcraft
Do you use optifine? - No
Did the problem appear in single player or on a server? - Cant even get into the game

**Comment by Jdawg215** [comment]
Also everything worked perfectly before i updated Nuclearcraft

**Comment by b0bst3r** [comment]
Yeah but you changed a mod in the mod pack so why are you here lol :D it's not my problem :)

You want me to fix it for you?

**Comment by b0bst3r** [comment]
BTW I know all about the issue because I had it in the new upcoming release :)

**Comment by Jdawg215** [comment]
I feel like the question of fixing it for me was sarcastic, but if it wasnt, sure.

**Comment by b0bst3r** [comment]
Haha kinda I get so many "I added this mod and it crashes.." and I'm like well unadd it then lol it's not my problem you added it :)

But anyway edit MatterOverdrive\matteroverdrive.cfg and change     I:entity.failed_pig.id=38 to     I:entity.failed_pig.id=138

I must express you change it to 138 which is in the new build so wont cause you any issues if/when/should you update.

**Comment by Jdawg215** [comment]
I had a feeling it was that stupid pig id! I wasnt sure cause it was an entity id so didnt know they still clashed. Thanks so much bob-senpai :P

**Comment by b0bst3r** [comment]
https://github.com/BevoTechPack/BevoTechPack/commit/6d8efe771210728d8cfed426d80a2ed3be8d3ca5

**Comment by Jdawg215** [comment]
NOW ITS REJECTING NUCLEARCRAFT

**Comment by Jdawg215** [comment]
it just says Rejecting connection SERVER: [FMLMod:NuclearCraft{1.9c}], fuck my life man.
