### ISSUE TITLE
1.7.10 Nuclearcraft rejected by server

### ISSUE THREAD

**Issue by Jdawg215** [BevoTechPack/BevoTechPack#1076]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 1.7.10
It's me again c:
### Description of issue/bug
Okay so b0b helped my dumb self fix the ID clashing problem, thx again for that. NOW the server, which only updated Nuclearcraft to 1.7.10, REJECTS IT.

### Steps to reproduce the issue/bug
-Log into server
-Mod rejected
-Cry

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
The log is too large for pastebin, should i trim any parts of it? The only related thing i saw was [20:08:17] [Netty Client IO #3/INFO] [FML/factorization]: Rejecting connection SERVER: [FMLMod:NuclearCraft{1.9c}]

Questions: Why do macbooks make life suffering

Did you add any additional mods? - 1.7.10 Nuclearcraft
Do you use optifine? - No
Did the problem appear in single player or on a server? - Server

**Comment by b0bst3r** [comment]
The server you're connecting to needs that updated mod on, if it's not your server you can't connect to it using an updated mods.  All mods must match server to client.

**Comment by b0bst3r** [comment]
Update to Release 1 and this will all be solved.
