### ISSUE TITLE
Ore Dictionary Converter?

### ISSUE THREAD

**Issue by MadEgg** [BevoTechPack/BevoTechPack#1077]
Is there any chance of adding http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286974-ore-dictionary-converter to BevoTechPack?

I have an automated ore processing setup using the Magneticraft machines, however, the dusts produced as primary and bonus output are not always the same (usually IC2 and Magneticraft dusts), so after smelting them I end up with several duplicates of most ingot types. The Ore Dictionary Converter allows to unify the ingots from the various mods into one ingot.

A related question: as you have unified the ore generation in the world, is there an exhaustive list of all ores that can be found in the wild, including their source mod? I'm having a hard time configuring my buildcraft diamond pipes correctly because I always have to go around finding samples of each ore. Using NEI would be much simpler but that lists all variants from all mods, so isn't really helpful. Perhaps this info is available in some config file within the mod-files?

**Comment by b0bst3r** [comment]
There are several ways to unify ore in the pack already, MFR unifier, TE thingymabob, jabba barrels and storage drawers are to name 4 I know of.   Not planning on any more mod additions sorry.

As for your diamond pipes try using one of the other piping systems which can handle the issue much better.  Relocators are probably one of the best and most underused piping systems that contain the most powerful filtering.

**Comment by MadEgg** [comment]
Ok, sorry, I wasn't aware of the MFR unifier, sounds like a proper solution.

I'm actually mostly using Mekanisms Logistical Transporters which are great, but don't give the the amount of flexibility / configuration diamond pipes do. I'll look into Refined Relocators. At least the Sorting Chests of that mod seem promising to combine with Logistical Transporters so get the same functionality. 

Thanks for the suggestion, and won't be needing Ore Dictionary anymore :) There's just so many mods available in BTP that it's sometimes hard to find the one you're looking for.
