### ISSUE TITLE
Minecraft is quitting after launching the pack for the first time

### ISSUE THREAD

**Issue by Cobble101** [BevoTechPack/BevoTechPack#1079]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- newest

### Description of issue/bug

the window automaticly close itself.

### Steps to reproduce the issue/bug

start the pack

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://pastebin.com/8fmk852F
Questions:

Did you add any additional mods? - no
Do you use optifine? -no
Did the problem appear in single player or on a server? - /

**Comment by b0bst3r** [comment]
Memory: 133278368 bytes (127 MB) / 259522560 bytes (247 MB) up to 1038876672 bytes (990 MB)

In Atlauncher click settings (right side) then Java/Minecraft tab at the top and set maximum ram to 4GB.
