### ISSUE TITLE
Cant get on the Server, anything with OpenGL

### ISSUE THREAD

**Issue by Cobble101** [BevoTechPack/BevoTechPack#1080]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug
[ internal exception :java lang runtime no opengl context found in the currend thread ]

### Steps to reproduce the issue/bug

joining an server

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - yes, all but open modular turrets.
Do you use optifine? -no.
Did the problem appear in single player or on a server? - server.

**Comment by b0bst3r** [comment]
Can't do a thing without a log

**Comment by Cobble101** [comment]
http://pastebin.com/mE4S3yQd

**Comment by b0bst3r** [comment]
Try Server Address: bevo.kookykraftmc.us
Optional mods: All but open modular turrets.

**Comment by Cobble101** [comment]
it was the server where  the problem happens.

**Comment by b0bst3r** [comment]
You didn't connect to the server address I posted, did you try that one above?

**Comment by b0bst3r** [comment]
TimeTheCat | KookyKraftMC.us - Today at 12:56 AM
bevo.kookykraftmc.net
b0bst3r - Today at 12:59 AM
oh your website says bevo.kookykraftmc.us
TimeTheCat | KookyKraftMC.us - Today at 12:59 AM
yea
play.kookykraftmc.net: hub
cc.kookykraftmc.net: CC
cc2.kookykraftmc.net: CC2
cc3.kookykraftmc.net: CC3
ms.kookykraftmc.net: modsauce2
sf2.kookykraftmc.net: SF2
crainer.kookykraftmc.net: Crainer
cteam.kookykraftmc.net: cteam
rr.kookykraftmc.net: rr3
tgc.kookykraftmc.net: TGC
sf25.kookykraftmc.net: sf25
sf25b.kookykraftmc.net: SF25B
fitp.kookykraftmc.net: FITP
crack.kookykraftmc.net: Crack
ub.kookykraftmc.net: UB
jwr.kookykraftmc.net: JWR
poz.kookykraftmc.net: poz
pozt.kookykraftmc.net: pozt
bevo.kookykraftmc.net: bevo
we just changed all of em
