### ISSUE TITLE
Ethermal Expansion, Machine Frame recipe

### ISSUE THREAD

**Issue by musznik** [BevoTechPack/BevoTechPack#1082]
Bevo Tech Pack Version :- BTP-Reborn-Release_1.0 from 29.08.2016

### Description of issue/bug
Machine Frame from Thermal Expansion has wrong recipe, there is only (steel or refined iron) instead of (steel or iron ingot). So it's harder to start.

correct recipe : http://teamcofh.com/docs/thermal-expansion/materials/machine-frames/

### Steps to reproduce the issue/bug
always in workbench

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? -  no
Do you use optifine? - no
Did the problem appear in single player or on a server? - single and server

**Comment by b0bst3r** [comment]
Intended
