### ISSUE TITLE
when it is dowloading journeys map it chrashes every time

### ISSUE THREAD

**Issue by SmarterboyOwl** [BevoTechPack/BevoTechPack#1083]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug
i am downloading the pack, The console says that it chrashes because it cant download journeys map.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:
What can i do?
Did you add any additional mods? - No
Do you use optifine? -No
Did the problem appear in single player or on a server? - single player (download)

**Comment by b0bst3r** [comment]
Reinstall should be fixed

**Comment by SmarterboyOwl** [comment]
what should i reinstall? Bevocraft? At launcher?

**Comment by b0bst3r** [comment]
reinstall Bevo's Tech Pack it wont error now.
