### ISSUE TITLE
crach at installation 

### ISSUE THREAD

**Issue by M4DD1N1112** [BevoTechPack/BevoTechPack#1084]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://pastebin.com/WAP8Zneg
Questions: novus crash while installation with this log 

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? -

**Comment by SmarterboyOwl** [comment]
Did you look in the console?

**Comment by SmarterboyOwl** [comment]
My problem is journeys map...

**Comment by M4DD1N1112** [comment]
and how i fixed this?

**Comment by M4DD1N1112** [comment]
smarterboy yes i have in the link is the crash

**Comment by b0bst3r** [comment]
Reinstall should be fixed

**Comment by M4DD1N1112** [comment]
the launcher ?

**Comment by b0bst3r** [comment]
reinstall Bevo's Tech Pack it wont error now.

**Comment by M4DD1N1112** [comment]
my problem is  i can`t install

**Comment by b0bst3r** [comment]
Have you tried it again?

**Comment by M4DD1N1112** [comment]
after reinstall the at launcher?

**Comment by M4DD1N1112** [comment]
its running thank you very mutch
