### ISSUE TITLE
BC Builders Quarry Bug

### ISSUE THREAD

**Issue by Noobinthisgame** [BevoTechPack/BevoTechPack#1085]
Bevo Tech Pack Version :- BTP-REborn-Release-1.0 and BTP-12-Full (problem occured on both versions

### Description of issue/bug

-- It isn't possible to craft the Quarry of the BC builders mod. I did put all the needed parts in a crafting table and in a crafting station but nothing habppens. Also when I click on the quarry on the item list next to the inventory nothing happens.

### Steps to reproduce the issue/bug

-- Try to craft it or select it on the item list (don't now the name of the mod to search item crafts).

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

-- There is no crash log.

Questions:

Did you add any additional mods? - No
Do you use optifine? - No
Did the problem appear in single player or on a server? - Single player.

**Comment by b0bst3r** [comment]
Disabled in the pack by me it's intended, read the last part of the FAQ about how to re-enable - http://bevolj.com/forums/index.php?threads/bevos-tech-pack-reborn-faq.865/

**Comment by bookerthegeek** [comment]
@b0bst3r we should probably hide it from nei or add a tag onto it so it says it is disabled. I'll do it of you like.

**Comment by b0bst3r** [comment]
Well before release 1.0 no one could find it anyway as the block name clashed with NuclearCraft and it got renamed to Machine Block :).  I wasn't intending to do anymore updates but I suppose I could if there were enough changes to warrant one (like Mek fixing the loads of bugs it has in it).
