### ISSUE TITLE
Mod Updates

### ISSUE THREAD

**Issue by bookerthegeek** [BevoTechPack/BevoTechPack#1086]
Bevo Tech Pack Version : ````1.0 ````

### Description of issue/bug
Mods have updates

### Steps to reproduce the issue/bug
Update mods (Please? I'll do it for you if you like)

### List of mods needing updates:
* [ ] [AE2 Stuff](https://mods.curse.com/mc-mods/minecraft/225194-ae2-stuff)
* [ ] [EnderCore](https://mods.curse.com/mc-mods/minecraft/231868-endercore)
* [ ] [Factorization](http://dl.dropbox.com/u/76265666/old/Factorization-1.7.10-0.8.108.jar)
* [ ] [Mod Tweaker](https://mods.curse.com/mc-mods/minecraft/220954-modtweaker)
* [ ] [Natura](https://mods.curse.com/mc-mods/minecraft/natura)
* [ ] [Not Enough Resources](https://mods.curse.com/mc-mods/minecraft/225815-notenoughresources)
* [ ] [Open Modular Turrets](https://mods.curse.com/mc-mods/minecraft/224663-openmodularturrets)
* [ ] [Road Stuff](https://mods.curse.com/mc-mods/minecraft/238984-road-stuff)
* [ ] [Roguelike Dungeons](https://mods.curse.com/mc-mods/minecraft/221585-roguelike-dungeons)
* [ ] [Thermal Expansion](https://mods.curse.com/mc-mods/minecraft/thermalexpansion)
* [ ] [Thermal Foundation](https://mods.curse.com/mc-mods/minecraft/222880-thermal-foundation)
* [ ] [Tinkers Construct](https://mods.curse.com/mc-mods/minecraft/tinkers-construct)

### Some additional Nice mods maybe:
* [ ] [HarvestCraft Waila Fixes](https://mods.curse.com/mc-mods/minecraft/harvestcraft-waila-fixes)
* [ ] [Cooking for Blockheads](https://mods.curse.com/mc-mods/minecraft/231484-cooking-for-blockheads)
* [ ] [IC2 nuclear control](https://mods.curse.com/mc-mods/minecraft/236813-nuclear-control-2)

### Not being Added or updated
* ~~What's This Pack~~
* ~~Galaxy Space~~
* ~~Growthcraft Community Edition~~
* ~~Minefactory Reloaded~~
* ~~Pam's Harvest Craft~~
* ~~Thaumcraft Inventory Scanning~~
* ~~Thaumcraft Node Tracker~~
* ~~Thaumcraft NEI Plugin~~

**Comment by b0bst3r** [comment]
Pam's Harvestcraft will never be updated I rolled it back to the last good version, unfortunately dev made a mess and didn't fix a really nasty bug.

What's this pack doesn't need updating, it does all that I ask.

Not updating Galaxy Space or Galacticraft as it always causes major breakages and what we have now is stable.

If  Growthcraft fixed the spamming of server logs I'll look again at that with the others.

Thanks for the list.

**Comment by bookerthegeek** [comment]
Edited post. :)

**Comment by bookerthegeek** [comment]
...Maybe, you could add rotarycraft and friends?

:D

**Comment by b0bst3r** [comment]
AE2 stuff is up to date the latest one is not for AE rv3

**Comment by b0bst3r** [comment]
Not adding harvestcraft waila fixes as it's for MC 1.6.4 :p
