### ISSUE TITLE
Opening My World

### ISSUE THREAD

**Issue by Zaidevel** [BevoTechPack/BevoTechPack#1087]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- Bevo Tech Pack Release 1.0

### Description of issue/bug
The Issue/Bug is that when I run the Pack on ATLauncher when it finish's installing the mods, I have played on one singleplayer world for the past couple days but know I cant open it, when I try to open it, it closes mc and goes to ATLauncher and says updating launcher but I can create a different singleplayer world and play on the perfectly without trouble, I tryed cloning the pack and copying the world but nothing has seemed to work of what I am doing! Please Help.

### Steps to reproduce the issue/bug
Open Atlauncher, run BevoTechPack, wait for it to install mods, go to singleplayer, open my world I have played on for 3 days, Wait for world to download, It closes and goes to AtLauncher, tab pops up saying, " Updating Launcher".

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
There wasnt a crash log, this is why I think its a problem and I need it to be fixed, Just need help ;)

Questions:

Did you add any additional mods? -  No
Do you use optifine? - No
Did the problem appear in single player or on a server? - Single Player

**Comment by b0bst3r** [comment]
Pastebin the atlauncher log

**Comment by Zaidevel** [comment]
http://paste.atlauncher.com/view/665d1ee0

**Comment by Zaidevel** [comment]
Is this the right one?

**Comment by Zaidevel** [comment]
Found the crash report, Here is the bottom of it. https://gyazo.com/0b3436bde7477a798f6456588748d728

**Comment by b0bst3r** [comment]
Your HQM data in your game save needs deleting. In the saves folder, locate your world, open that folder up and you should see a "HardcoreQuesting" folder, go in there and rename the players.dat to something else and try reloading your world.

Then when you load your world go into LAN mode and turn on cheats, then type /hqm edit this gives you an OP book to which you can auto complete the quests that you already did.
