### ISSUE TITLE
matter overdrive broken

### ISSUE THREAD

**Issue by dhdzeke** [BevoTechPack/BevoTechPack#1088]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 1.0
matter overdrive version 1.7.10-0.4.1 build 56
### Description of issue/bug
the buildings that are supposed to spawn in villages do not spawn and they are needed to progress threw the quest line and in the mod its self u can not become an android unless the villages have spawned the buildings it is turned of in the config

### Steps to reproduce the issue/bug
its disable in the config

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
no crash
Questions:

Did you add any additional mods? - laser mod /wr-cbe/funky locamotion
Do you use optifine? -no
Did the problem appear in single player or on a server? - singleplayer

**Comment by b0bst3r** [comment]
Chapter 8 in the HQM book is the way to become an android.
