### ISSUE TITLE
no quarry

### ISSUE THREAD

**Issue by Chaos02** [BevoTechPack/BevoTechPack#1089]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 10

### Description of issue/bug
I cant craft any quarrys from BC. recipe is needed

### Steps to reproduce the issue/bug
try to craft an quarry

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
no crash
Questions:
is there a guy, who can make this work?
Did you add any additional mods? - some of Novus in germany
Do you use optifine? - yes; but was already without optifine
Did the problem appear in single player or on a server? - singleplayer and server

**Comment by b0bst3r** [comment]
Last section - http://bevolj.com/forums/index.php?threads/bevos-tech-pack-reborn-faq.865/
