### ISSUE TITLE
Power shortage yesterday and now I can't play my save

### ISSUE THREAD

**Issue by Danagossauro** [BevoTechPack/BevoTechPack#1090]
I was playing on my server with some friends yesterday and i had a power shortage on the neighborhood, then i was "ok, imma sleep now", and today i booted up my PC, and started the server, but it suddenly closed after a while, i tried pasting the world data on the atlauncher folder so i could play single player but it started loading and then just closes the game

I've seen some people saying things about deleting enderstorage, i did that on the modpack, the server AND the world save, but still, same thing
[log.pdf](https://github.com/BevoTechPack/BevoTechPack/files/453990/log.pdf)
[crash-2016-09-04_12.46.36-server.pdf](https://github.com/BevoTechPack/BevoTechPack/files/453992/crash-2016-09-04_12.46.36-server.pdf)

Did the problem appear in single player or on a server? - Both

**Comment by b0bst3r** [comment]
Without logs I can't do anything

**Comment by Danagossauro** [comment]
Sorry but how do i post a log?

**Comment by Danagossauro** [comment]
uploaded the last log on my server

**Comment by b0bst3r** [comment]
Your HQM data in your game save needs deleting. In the world folder, you should see a "HardcoreQuesting" folder, go in there and rename the players.dat to something else and try reloading your world.  There might/should be a players.dat-backup which you can try renaming to players.dat which may not have got corrupted which you can try.

You can type /hqm edit (if your a server OP) this gives you an OP book to which you can auto complete the quests that you already did.

**Comment by Danagossauro** [comment]
It worked! thanks a lot man,  you saved my sunday
