### ISSUE TITLE
BTP Crashes in startup

### ISSUE THREAD

**Issue by kalenm** [BevoTechPack/BevoTechPack#1091]
Bevo Tech Pack Version :- Bevo's Tech Pack BTP-Reborn-BetaX-Hotfix

### Description of issue/bug

The problem I've been having is that trying to start up the modpack, it will crash during initializing the minecraft engine, and it will always happen there even without any extra mods. The pack was working fine a few days ago and I'm not sure what to do.

### Steps to reproduce the issue/bug
Just trying to start the pack, with and without extra mods. Problem only started a few days ago.

**Comment by b0bst3r** [comment]
java.lang.OutOfMemoryError: Java heap space
Memory: 4098048 bytes (3 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)

In Atlauncher click settings - Java/Minecraft and change Maximum Memory/Ram to 4096 and click save at the bottom. There's no way on earth you can run modded Minecraft on 1GB RAM :)

**Comment by kalenm** [comment]
Thanks Mate, I guess I forgot to change that max for the ram usage after I had reset my computer. Thanks for helping me fix this problem.
