### ISSUE TITLE
Crashes when installing/downloading pack

### ISSUE THREAD

**Issue by thebestbandit** [BevoTechPack/BevoTechPack#1092]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- BetaT

### Description of issue/bug
When downloading modpack, there is a error to download the pack.

### Steps to reproduce the issue/bug
open launcher, choose instance BetaT and launch.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://paste.atlauncher.com/view/3743e01f

Questions:

Did you add any additional mods? - No
Do you use optifine? - No
Did the problem appear in single player or on a server? - N/A

**Comment by b0bst3r** [comment]
Why are you playing on such an old version?

**Comment by thebestbandit** [comment]
I haven't known how to update my server, if there is a way to update it easily i will gladly do it. I'm the server owner but just got a new computer and it is not launching, all the players on it can launch though

**Comment by b0bst3r** [comment]
To fix your current issue click this link and download the file http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download place the file in the atlauncher\download folder and install Bevo's Tech Pack.

To update your server load atlauncher, select packs, select create server, choose which version you want to go to (pretty safe to go from betaT to release 1 but pay attention to the warning screen about Nuclearcraft).  Once complete go to atlauncher\servers folder and find the one you created, go into this folder and copy the config, mods and scripts folders to your server.  When updating your server rename the current config, mods and scripts folders to something like config.bak so you have a backup just in case.  Then copy across the new ones, never put the new config, scrips and mods folder over the top of the old ones as this will cause huge problems.  

Before you start the server create a backup of your world.

When you start your server there's a pretty big chance (almost guarantee it) that you will have to do a /fml confirm.

**Comment by thebestbandit** [comment]
hmmmm didn't work :(
here's the log:
http://paste.atlauncher.com/view/052b8ac0

Also thanks ill get on that in the next week, they'll like the update!

**Comment by b0bst3r** [comment]
oops morpheus too http://minecraft.curseforge.com/projects/morpheus/files/2280761/download but really morpheus is a server only mod you don't really need it clientside

**Comment by thebestbandit** [comment]
Worked! And thanks for the Server Info!!!
