### ISSUE TITLE
Can't use Focus on Wands in Thaumcraft

### ISSUE THREAD

**Issue by SeDoctorv2** [BevoTechPack/BevoTechPack#1093]
I can't put any wand focus on a wand in the Thaumcraft mod!

Bevo Tech Pack Version :- )

Questions:

How can I fix this Bug?

**Comment by b0bst3r** [comment]
remap the key

**Comment by SeDoctorv2** [comment]
I'm playing on a Server, won't i be able to join the Server anymore once I
have done this?

2016-09-05 23:45 GMT+02:00 b0bst3r <notifications@github.com>:

**Comment by b0bst3r** [comment]
wont make any difference keys are mapped clientside, server doesn't press leys to play the game.

**Comment by SeDoctorv2** [comment]
Awesome, Thank you for your help! :)


2016-09-06 15:47 GMT+02:00 b0bst3r <notifications@github.com>:
