### ISSUE TITLE
Blocks randomly changed to other blocks

### ISSUE THREAD

**Issue by PoliticalDerp** [BevoTechPack/BevoTechPack#1094]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version : BevosTechPack_BTPRebornRelease10 

### Description of issue/bug
For some strange reason, when I started by server up for Release 10, a large amount of generated mod blocks (like mod trees, mod grown plants, and some modded ore) changed into random mod blocks. Some examples:
Random ores turned into Chicken Chunks chunk loaders
Mana pools turned into pools of the mod item Oculus 
Modded lilly pads turned into animal traps
Compressed cobbles stone turn into light blue wooden planks. 
Some type of tree (not sure which one) turned entirely into anti matter bombs (leaves) and some type of technology relay (wood).

My server from then on has been very unstable and some blocks, when broken, will crash the player that breaks them. 

### Steps to reproduce the issue/bug
I can continuously connect to the server that has the bug problem, but I cannot recreate the bug on other servers. 

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
No crashlog

Questions:

Did you add any additional mods? 
I have 5 additional mods added to the modpack:
Ars Magika 2 (includes AnimationAPI)
Modular Powersuits (includes Numia)
ProjectE
Witchery
Ex Nihilo
Do you use optifine? No
Did the problem appear in single player or on a server? Server

**Comment by b0bst3r** [comment]
Need to see your forge log but since you added a load of mods it could be those not had this reported upto now.

**Comment by bookerthegeek** [comment]
Sounds like he deleted his world data file somehow.

**Comment by b0bst3r** [comment]
No reply
