### ISSUE TITLE
BTP Crashing when trying to look up recipes and uses

### ISSUE THREAD

**Issue by zyxwa2000** [BevoTechPack/BevoTechPack#1095]
I'm using the BTP 12 1.7.10 mini version, with Flans Mod (WW2 pack, ye olde pack, simple parts pack, and modern weapons packs installed), Apple Core, Computercraft, Backpacks, Fastleafdecay, Aether II (and the coremod), Pam's harvestcraft, and Project E added.

I first experienced this issue when trying to look up the recipe for TiCon drying racks. I looked it up and the fix was to disable the handlers for Pam's HarvestCraft. I did that and the issue still persists.

Not sure I needed just the crash log or the full log

[The log] (https://docs.google.com/document/d/1XMVjMr6RNzFpI1kYy7k1SHHFxiRBybSyo93Nn4N_V-M/edit?usp=sharing)

thank you in advance

**Comment by b0bst3r** [comment]
Dude BTP 12 is like 2 years old adding new mods to it just wont work :) if you want to play the newer version pick any of the other newer packs.  Those old ones BTP 11 and BTP 12 are too old to add new mods to either play them as they are or move to a newer version :)
