### ISSUE TITLE
Bevo's Tech pack Beta-o Please help, i just spent 40 hours in this f****** world

### ISSUE THREAD

**Issue by CvAtlissues** [BevoTechPack/BevoTechPack#1097]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- Beta o full
### Description of issue/bug

world crashing on loading
### Steps to reproduce the issue/bug

?
### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

http://pastebin.com/xaVtF1Ws
Questions:

Did you add any additional mods? - yes. Xray, bigreactors
Do you use optifine? - no
Did the problem appear in single player or on a server? - single player

**Comment by b0bst3r** [comment]
I can tell you what's causing it but it's not an easy fix unless you know what you are doing with world edit.

A Mekanism Logistical transporter connected to a Magneticraft Shelving unit is what's causing the crash.

Since there's no block co ordinates in the crash log you can't do a simple world edit of the block.

So you have 2 choices, lets start with the easy one and see if it fixes the world.

Edit config/forge.cfg and change 

    B:removeErroringEntities=false
    B:removeErroringTileEntities=false

both to true, load up your world, it may still crash, load it up again.

If it fixes your world change those 2 back to false (don't play your game with them set to true).

If it fixes the issue close this if it doesn't let me know.

**Comment by CvAtlissues** [comment]
Thanks a lot. I'm gonna try tonight and i will let you know if it worked.

**Comment by CvAtlissues** [comment]
It didn't work for me but i have the coordinates. Can you also tell me how to world edit?

**Comment by bookerthegeek** [comment]
Look up on Google "Minecraft cords to region" and get the region file name.

Go into you world datatype folder and make a backup of the region, and then open the original with NBTExplorer. 

Find the cords of the block and delete the item.

**Comment by CvAtlissues** [comment]
Thanks a lot, i will try and let you know if it worked

**Comment by CvAtlissues** [comment]
I don't have the specific coordinates of the block. Is there any in the crash log?

**Comment by CvAtlissues** [comment]
Didn't work. I have the chunk in nbtexplorer but not the block

**Comment by bookerthegeek** [comment]
So now you need to dig down and find the block location. It is their I promise.

**Comment by CvAtlissues** [comment]
Ok, i will work on that this week end and let you know when i find it.

**Comment by b0bst3r** [comment]
If you have the exact block location you could move your world into a server and use the console and world edit to select the position and replace it with an air block, maybe easier than editing nbt data.

**Comment by CvAtlissues** [comment]
It may be easyer but i don't have the money for a server (i have a gtx1080 to buy)

**Comment by b0bst3r** [comment]
You can host the server locally on your pc, on the atlauncher packs tab you should see a create server button, do that and load the same precise mods you have in your client.  Then launch the server, then quit the server, then copy the contents of your single player save game into the server's world folder (deleting what was in there first).

**Comment by CvAtlissues** [comment]
Good, i will try thanks

**Comment by b0bst3r** [comment]
Fixed?

**Comment by CvAtlissues** [comment]
Sorry, forgot... but can you send me a link to download worldedit?

**Comment by b0bst3r** [comment]
https://minecraft.curseforge.com/projects/worldedit/files
