### ISSUE TITLE
Game crashes while loading world

### ISSUE THREAD

**Issue by Lerosen** [BevoTechPack/BevoTechPack#1098]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- Release 1.0
[crash-log.txt](https://github.com/BevoTechPack/BevoTechPack/files/472579/crash-log.txt)

### Description of issue/bug
The instance crashes as I try to open my world, I clicked on "Play selected world" then I see "loading world" and after some seconds Minecraft just closes and the AT Launcher window comes into foreground. I attached the crash report below.

I also tried to delete the player data files and loginTimes.dat - still the exact same Error.

### Steps to reproduce the issue/bug
Start Instance - select world and click play

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - no
Do you use optifine? - no
Did the problem appear in single player or on a server? - single player

Thanks for your help :)

**Comment by b0bst3r** [comment]
How did you end up with this, was it a normal shutdown last time you played or did something happen or was you playing and a crash occured or?

**Comment by Lerosen** [comment]
There was nothing special, i quit the game normally D:

**Comment by b0bst3r** [comment]
I'm not sure how you can fix that or if it's even fixable, Mr Google says it's a corrupted save.

**Comment by Lerosen** [comment]
hm, at least Mr. Google talks with you, i did not even find any good results :3 Thanks for your help 👍
