### ISSUE TITLE
Make HQM Optional

### ISSUE THREAD

**Issue by Time6628** [BevoTechPack/BevoTechPack#1100]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- Release 1.0

### Description of issue/bug
If you've ever played on a highly populated server with HQM, you will know, it causes tons of lag. Specifically, when it saves. It saves every time the server saves, and it doesn't save every player individually, just as one large clump. It also does it in the MAIN server thread, which makes it even worse. If you really _have_ to have quests in this pack, try this fork of it, https://github.com/lorddusk/HQM/pull/218 , it brings the new JSON system of the newer versions of HQM. There's also [BetterQuesting](https://mods.curse.com/mc-mods/minecraft/238856-better-questing) which is similar to HQM, but it much better for performance. There's also the issue of HQM stalling the server when it checks if the items are the same, because it also does that in the main thread instead of it's own.

I know most of my players don't do the pack for the quest, they play the pack because it has an amount of tech that most packs don't have. If you could make HQM optional or switch to the suggestions above, I know my staff team and players would be grateful. :cat:

### Steps to reproduce the issue/bug
1. Setup server.
2. Get players to join.
3. On every save the server will become worse and worse, until it's practically unplayable.

Questions:

Did you add any additional mods? - Yes.
Do you use optifine? - No
Did the problem appear in single player or on a server? - Server :p

**Comment by b0bst3r** [comment]
Just leave the mod off the server = disables HQM

**Comment by bookerthegeek** [comment]
@b0bst3r 

If you like I'm sure I can come up with some people to redo the quests for BetterQuesting

**Comment by b0bst3r** [comment]
Sorry not going to happen, you have choice as server admin to not install mods.
