### ISSUE TITLE
Fatal errors were detected during the transition from POSTINITIALIZATION to AVAILABLE. Loading cannot continue

### ISSUE THREAD

**Issue by zyxwa2000** [BevoTechPack/BevoTechPack#1103]
Bevo Tech Pack Version :- BTP Reborn Release 1.0 1.7.10

### Description of issue/bug
It just crashes on startup. Nothing else really. Loaded fine before I added "some" mods to it (Aether, Agricraft, AppleCore, BattleTowers, ComputerCraft, Fastleafdecay, Flans mod[with Modern Warfare, Simple Parts, WW2 and Ye Olde Packs], The core for Aether, and ProjectE). I'm on Mac OSX El Capitan v. 10.11.5.

### Steps to reproduce the issue/bug
1. Download BTP Reborn Release 1.0 1.7.10
2. Install mods mentioned
3. Voila! You have made your own crash!

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://pastebin.com/QCSU4GFC
Questions:

Did you add any additional mods? - ya
Do you use optifine? - nope
Did the problem appear in single player or on a server? - singleplayer

Thanks in advance.

**Comment by b0bst3r** [comment]
Did you add any additional mods? - ya 

Which?
