### ISSUE TITLE
Permanently Night Time + Permanently Gliding

### ISSUE THREAD

**Issue by SujakAlkesh** [BevoTechPack/BevoTechPack#1105]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings. 

Bevo Tech Pack Version : 2.0

### Description of issue/bug
I'm having a Oxygen Tank UI in the upper right corner even though I don't have anything on me and It's currently night time. The permanent gliding makes it really annoying to play.

### Steps to reproduce the issue/bug
-  Play for a couple of minutes

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - Negative
Do you use optifine? - Yes
Did the problem appear in single player or on a server? - Server

**Comment by b0bst3r** [comment]
I can only presume the chunks aren't loading around your base, try leaving it a while longer and see if anything happens, also get the server admin to check there's nothing bad happening in the server console when you log in.

**Comment by SujakAlkesh** [comment]
Everything is being loaded fine.
This is what it looks like: http://imgur.com/a/OeI9m

**Comment by SujakAlkesh** [comment]
I can't figure out a way to fix this, for most of my players it's impossible to play with. Any ideas how to remvoe it

**Comment by b0bst3r** [comment]
Looks to me like your on Mars, press F3 and see what it says about your location

**Comment by SujakAlkesh** [comment]
I'm on overworld. Just after 10 minutes of playing that earth/moon pops up on the sky and I have oxygen GUI in the upper right corner ( I dont have anything equipped) and it only gets fixed by rebooting the server

**Comment by bookerthegeek** [comment]
@SujakAlkesh do you have access to the backend of the server?

**Comment by SujakAlkesh** [comment]
@bookerthegeek I own the server, I have hosted multiple in the past and have never had that issue before

**Comment by bookerthegeek** [comment]
Just out of curiosity, what is the world type set to?

**Comment by SujakAlkesh** [comment]
The world type is set to DEFAULT. Apparently when the problem accuses and I go into a different dimension e.g. Nether the    
2 tanks disappear. When then going back to overworld it's back. I have to create a new world file now everytime it happens.

**Comment by SujakAlkesh** [comment]
Ok i just found out something: When i open up my JourneyMap, It does tell me that I'm in the dimension; "Proteus" does that help you guys?

**Comment by bookerthegeek** [comment]
Forge server? If not, do you have multi world installed?

**Comment by SujakAlkesh** [comment]
Fix: I disabled Proteus, issue no longer happens
