### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Gexen** [BevoTechPack/BevoTechPack#1108]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version : BetaU

If i try to start my Server, it crashes. I have posted the Server output below. Thanks for help :)

Here is the Server Log:
http://pastebin.com/FTUbzujE

Questions:

Did you add any additional mods? no
Do you use optifine? yes
Did the problem appear in single player or on a server? Server

**Comment by b0bst3r** [comment]
Do you have a crashlog as it's hard to see what's causing the crash in that Forge log?

**Comment by Watschman** [comment]
just to give an answer even though it probably doesn't matter anymore after nearly a month. The Crash is most likely caused by a Solar Evoporation Controller which caused a NPE. At least that's the only indication of a crash I can find in the log

**Comment by b0bst3r** [comment]
It's not that as that NPE is in every forge log, don't see him coming back so
