### ISSUE TITLE
superfast mouse

### ISSUE THREAD

**Issue by LordOfBricks** [BevoTechPack/BevoTechPack#1109]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 
### Description of issue/bug

yeah my mouse is ingame superfast so I can do nothing :(
### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - 
Do you use optifine? - no
Did the problem appear in single player or on a server? - single

**Comment by b0bst3r** [comment]
You tried adjusting the mouse sensitivity?

**Comment by LordOfBricks** [comment]
yes but it doesn't work :(

**Comment by ranger135xp** [comment]
Are you playing on fullscreen? Have you tried playing in windowed mode?
