### ISSUE TITLE
Issue with galacticraft connecting lobby

### ISSUE THREAD

**Issue by Yann151924** [BevoTechPack/BevoTechPack#1110]
Bevo Tech Pack Version :-Reborn Release 2.0

### Description of issue/bug
This the description of the bug, you have all information on the issue, not the same modpack but it still the same issue with the bevo :)

https://github.com/micdoodle8/Galacticraft/issues/2194

### Steps to reproduce the issue/bug

Spigot 1.10 Lobby
Bungeecord HexagonMC latest version
Connect to the lobby and it cause the issue 'No OpenGL context found in the current thread.'

Questions:
Did you add any additional mods? - NO
Do you use optifine? -NO
Did the problem appear in single player or on a server? - Server

The issue is fix in version 461 of Galacticraft if you can update the modpack to this version it will solve my prob

Changelog of Galacticraft : https://ci.micdoodle8.com/job/Galacticraft-1.7/changes
(Improve GC client compatibility with Bungee servers. Fixes #2194 is the fix)

Refering to issue #923 and #898 they have same prob :)

**Comment by b0bst3r** [comment]
gnnn ......arrrrgghhhh ..... hmmm ok if I must .... this might break loads though which is why I refrained from updating GC/GS

**Comment by Yann151924** [comment]
might break loads ?

**Comment by b0bst3r** [comment]
Yes if you went far enough back with the pack when I updated GC and GS a lot they broke each other and the HQM book relies heavily on GS IDs matching.  Everytime I've had to update GS I've had to reset the IDs and rework the HQM book quests :)

Internal testing is currently going on but if all is well expect an update by the weekend.

**Comment by Yann151924** [comment]
Hum ok :( 

Update for the weekend can be good :)

**Comment by b0bst3r** [comment]
Premliminary testing shows this completely breaks HQM, and previously made worlds refuse to load, trying to figure out why.

**Comment by b0bst3r** [comment]
Fixed in 2.1

**Comment by Yann151924** [comment]
Work as expected thanks you

**Comment by Time6628** [comment]
You could always just use bungee forced hosts :p
