### ISSUE TITLE
Server Crash - World Tick Error

### ISSUE THREAD

**Issue by ingel81** [BevoTechPack/BevoTechPack#1111]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version : BTP-Reborn-Release_2.0 
### Description of issue/bug

Random server crashes (every ~10 to 30 Minutes)
### Steps to reproduce the issue/bug
- DON'T have to be logged in with my character for the error to happen.
### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

http://pastebin.com/rPncWMd1

Questions:

Did you add any additional mods? -  no
Do you use optifine? - no
Did the problem appear in single player or on a server? - server

**Comment by b0bst3r** [comment]
Some questions if you please:

How many players are usually on the server:
How old is the map (is it new, old, years old):
How long has this been happening (did it occur on previous occasions with older versions of BTP):
If you updated to Release 2.0 what version did you update from:
Does the server suffer from TPS issues (block lag, slowness opening chests etc):

**Comment by sworddeamon** [comment]
> How many players are usually on the server:

just me for the moment.

> How old is the map (is it new, old, years old):

maybee two weeks

> How long has this been happening (did it occur on previous occasions with older versions of BTP):

It is happening since two days. Before everything was fine for a few days with a lot of playtime.

> If you updated to Release 2.0 what version did you update from:

fresh install of client and server, no updates

> Does the server suffer from TPS issues (block lag, slowness opening chests etc):

no, nothing i am aware of.

Thanks!

**Comment by ranger135xp** [comment]
do you have a bunch of mod items/machines in a base or several bases? This could be chunk churn: https://www.reddit.com/r/feedthebeast/comments/3lfjpp/1710_post_mortem_investigating_mystery_chunk/

This was affecting me but this was solved when I made chunkloaders cover everything that was built by a player and that contained conduits, machines, etc.
