### ISSUE TITLE
Server crashes a few seconds after clicking on Play Selected World

### ISSUE THREAD

**Issue by rahangar** [BevoTechPack/BevoTechPack#1112]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 2.0
### Description of issue/bug

Server crashes a few seconds after clicking on "Play Selected World", usually right after a glass breaking sound.
### Steps to reproduce the issue/bug

This used to happen randomly, even way back before 1.0.  But now it happens every time.  I can no longer start my world.

The first sign of trouble seems to be this line:

[07/10/2016 19:02:17 PM] [19:02:16] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.sound.PlaySoundEvent17@1b7ee708:
### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

http://pastebin.com/tdUqcaCx
http://paste.atlauncher.com/view/dba99b4e

Questions:

Did you add any additional mods? - no
Do you use optifine? - no
Did the problem appear in single player or on a server? - single player

**Comment by b0bst3r** [comment]
You have 2 choices, lets start with the easy one and see if it fixes the world.

Edit config/forge.cfg and change

B:removeErroringEntities=false
B:removeErroringTileEntities=false

both to true, load up your world, it may still crash, load it up again.

If it fixes your world change those 2 back to false (don't play your game with them set to true).

If it fixes the issue close this if it doesn't let me know.

**Comment by rahangar** [comment]
Thanks for the response.

First I upgraded to 2.1 hoping some fix in there resolves my issue.  No luck.
Then I set those parameters set to true, it did not crash.
Then, after setting them to false again, I see a crash.
Is it worth it to repeat setting those to true again?  Is it removing blocks when do?
The new crash:  http://pastebin.com/16Y06Sdg

**Comment by b0bst3r** [comment]
This is a generic error unfortunately which doesn't really point to any specific mod :( so yeah try playing with the flags set to true for a bit and see if it stabilises. Then try them on false and yeah it will make blocks vanish which cause a crash.

**Comment by houssecatlover** [comment]
I have the same issue and it crashed on true and false.

**Comment by ranger135xp** [comment]
This title sounds misleading. When you say, "Server crashes..." and then, "...after clicking on Play Selected World" seems like you're talking about both client and server.  The reason I'm saying this is because even though client and server are now one unlike old minecraft, they can still be separate instances when talking about mods. 

I found a few posts that point to "Exception caught during firing event" errors as being a client-side mod being installed on a server. Are you for sure playing single player?

**Comment by ranger135xp** [comment]
I found ExtraUtilities to be a culprit. What version do you have? Anything less then 1.2.12 has this issue.
https://github.com/rwtema/extrautilities/issues/671
