### ISSUE TITLE
Java Detection Problem

### ISSUE THREAD

**Issue by Stenzler** [BevoTechPack/BevoTechPack#1113]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- BTP-Reborn-Release_2.1 (Minecraft 1.7.10)

When creating the instance, I install and select AE2 Stuff and Fastcraft as the optional mods. The Pack Instance is created, and I click play. The mini-window appears to say that the environment is loading, the console loads a few lines in text and then a warning pops up, after which I click OK and the game stops loading:

"You are using an old Java version, and should update to 1.8 or newer."

**I have Java 1.8 installed**, under Program Files x86. I have tried to change the Java pathway, but then the instance just fails. Don't know what to do to let the pack know it is on there.

http://pastebin.com/tU5McGna

Questions:

Did you add any additional mods? - Fastcraft, AE2 Stuff. Tried with both uninstalled, still not working.
Do you use optifine? - No.
Did the problem appear in single player or on a server? - Neither, before loading the instance.

**Comment by b0bst3r** [comment]
Line 6 

[10/10/2016 22:38:21 PM] Java Version: Launcher: 1.7.0_80, Minecraft: 1.7.0_80

That's java 7 - in Atlauncher click Settings - Java-Minecraft and change the java path to point to java8
