### ISSUE TITLE
"Pack ist not Installed"

### ISSUE THREAD

**Issue by BirnenLaser** [BevoTechPack/BevoTechPack#1114]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

In all Packs i have downloadet.

 Description of issue/bug

When i Start to install a Pack there cames a Window whit: "Pack isn´t installed. Please check the Error-Logs for the Mistake!"

### Steps to reproduce the issue/bug

http://pastebin.com/iNDEQVhi (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? -  No/yes
Do you use optifine? - No
Did the problem appear in single player or on a server? -  In Singleplayer.

**Comment by b0bst3r** [comment]
This is a launcher problem not a pack problem, suggest joining Atlauncher Discord https://discordapp.com/invite/0eXDtXikrVAJffxY and seeking help in the #support channel
