### ISSUE TITLE
Corrupted server

### ISSUE THREAD

**Issue by Chaosrelic** [BevoTechPack/BevoTechPack#1115]
Please help. If I'm missing information let me know how I can get to it. This server is with myself and my 8 year old son on the weekends that I have him. It's important to us.

Bevo Tech Pack Version :- 
BTPRebornBetaQ
### Description of issue/bug

System shutdown because APS(battery backup) freaked out. On reload of system, server would not load. 

Forge Mod Loader detected that the backup level.dat is being used.

This may happen due to a bug or corruption, continuing can damage
your world beyond repair or lose data / progress. (etc... it goes on with the "run /fml confirm" stuff... but that does not work.)

All searches show how to fix single player worlds. 
### Steps to reproduce the issue/bug

This happens every time the server is loaded.
### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

This is of (fml-server-latest.log) as I can't find a crashlog for the server. Searched c:\ for "crashlog" and didn't find one that related for our server.

http://pastebin.com/Q15554Em

Questions:

Did you add any additional mods? - Nothing has changed since original install.
Do you use optifine? - No
Did the problem appear in single player or on a server? - On Server

**Comment by Chaosrelic** [comment]
I have tried the one corrupted world fix by copying a new instance's level.dat/level.dat_old/session lock into the server directories. Same issue persists.

**Comment by Chaosrelic** [comment]
Tried again. Got a crash report this time on it. 

http://pastebin.com/w8BUTxN7

**Comment by b0bst3r** [comment]
Your HQM data in your game save needs deleting. In your world folder on the server, open that folder up and you should see a "HardcoreQuesting" folder, go in there and rename the players.dat to something else and try reloading your world.

Then when you load your world  type /hqm edit this gives you an OP book to which you can auto complete the quests that you already did.

**Comment by Chaosrelic** [comment]
renamed both files in HardcoreQuesting to:
OLDplayers.dat
OLDplayers.dat-backup

No change. Noticed that on running the startup that new copies of these files were not generated.

http://pastebin.com/X4f5P1a9

**Comment by b0bst3r** [comment]
Yeah not sure that's repairable, you have no backups?

**Comment by Chaosrelic** [comment]
I do have a backup but it's 5 months old. Lots has happened since then.
