### ISSUE TITLE
Can't find the Machine Base/Quarry 

### ISSUE THREAD

**Issue by Wirexia9** [BevoTechPack/BevoTechPack#1116]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- Bevo's Tech Pack BTP-Reborn-Release_2.1

### Description of issue/bug
I can't find the Machine Base in the Searching-Menu in my inventory. I can find only 2 Machine Bases. But I can't place them. Another problem is, that i can't build the Quarry.

### Steps to reproduce the issue/bug
1. Go in the inventory in Survival Mode
2. Click the Searching -"Line" and write "Machine Base"
3. And you can see only 2 Machine Bases but not 3.
### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions: How can I fix it?

Did you add any additional mods? - AE2 Stuff, Biome Reactors, Compact Machines, FastCraft, OpenPeripheralCore,OpenPeriphepalAddons, OpenPeriphepalIntegration,Open Modular Turrets, Ruins(Structure Spawning System), TC Node Tracker
Do you use optifine? -No
Did the problem appear in single player or on a server? - single player

**Comment by b0bst3r** [comment]
From the FAQ

Q - I've been asked on numerous occasions about the Buildcraft Quarry and how to re-enable it (as it's disabled by default), there are so many better less world destructive quarry type machines in this pack from Mekanism's Digital Miner to Magneticraft's Miner to Extra Utilities's Ender Quarry that there are so many better choices. But I still get asked after pointing all those out so, how do you enable the Buildcraft Quarry?
A - Delete minecraft\scripts\bc6.zs, in game do a /mt reload (you will have to start a LAN game and enable cheats if you're playing SSP and the server needs to do this if playing SMP). You need to be running Bevo's Tech pack Release 1.0or later to see the quarry or it will be called a Machine Block.

**Comment by Wirexia9** [comment]
Thanks for your help. Now it's working.
