### ISSUE TITLE
How do i get the quest book to show quests?

### ISSUE THREAD

**Issue by Kolby123w** [BevoTechPack/BevoTechPack#1117]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? -

**Comment by b0bst3r** [comment]
You saying it's blank or you can't open it?

Which Bevo version?
Single or server play?

Sigh if you'd have answered the template I wouldn't have to ask these things again.......

**Comment by bookerthegeek** [comment]
@b0bst3r just start closing, locking and then link to a template explaining why they derped, and how to submit properly.
