### ISSUE TITLE
Quest Book Failed Detection - Wind Generator

### ISSUE THREAD

**Issue by rayn337** [BevoTechPack/BevoTechPack#1118]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- BTB_Reborn_Release_2.1

### Description of issue/bug
Guestbook will not recognize creation or placement of the five wind generators for the quest. It is impeding my ability to do more advanced quests.

### Steps to reproduce the issue/bug
Create and/or place 5 wind generators and attempt to redeem quest from questbook

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - no
Do you use optifine? -no
Did the problem appear in single player or on a server? - single player

**Comment by b0bst3r** [comment]
Did you have all 5 in your inventory at the same time?

**Comment by rayn337** [comment]
@b0bst3r I thought I had, but apparently I didn't. The quest shows 0% unless you have all 5 in your inventory. Thank you!
