### ISSUE TITLE
Error with dowloading Bevos Tech pack reborn 1 - 2.1

### ISSUE THREAD

**Issue by LuciPlaysHD** [BevoTechPack/BevoTechPack#1119]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :-  1 - 2.1

### Description of issue/bug
Every time there is a error while downloading. I looked at the Internet but i can't find anything....Pls help!

### Steps to reproduce the issue/bug
New instance -> Version: 2.1 -> All optinal mods -> start -> Error

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://paste.atlauncher.com/view/71871d64

Questions: Has anyone else this problem?

Did you add any additional mods? - No
Do you use optifine? -No
Did the problem appear in single player or on a server? - Nothing

**Comment by b0bst3r** [comment]
This is a launcher problem not a pack problem, suggest joining Atlauncher Discord https://discordapp.com/invite/0eXDtXikrVAJffxY and seeking help in the #support channel
