### ISSUE TITLE
problem beim spielstart

### ISSUE THREAD

**Issue by muchacho132** [BevoTechPack/BevoTechPack#1120]
wenn man das pack das erste mal öffnet und es alles installiert gibt das programm immer bei bibliocraft keine rückmeldung
Bevo Tech Pack Version :- 

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? -

**Comment by b0bst3r** [comment]
Can anyone help translate?

**Comment by Watschman** [comment]
@b0bst3r Translated: "When I open this pack for the first time and everything is getting installed it stops the program at Bibliocraft with no Response."

@muchacho132 Versuche den Launcher neuzuinstallieren und schau ob das Problem weiterhin besteht, die Problembeschreibung ist unzureichend um eine genaue Diagnose durchzuführen. Praktisch wäre außerdem ein crash-report oder Konsolen-Einträge.

**Comment by b0bst3r** [comment]
My guess is he's not allocated enough RAM to the instance.
