### ISSUE TITLE
No Worlds Opening

### ISSUE THREAD

**Issue by Da-Wrench** [BevoTechPack/BevoTechPack#1123]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 2.1

### Description of issue/bug
Whenever I open a world, it is on the loading screen for about 30 seconds, then it goes back to the title screen and does nothing. It does this for all my worlds, even if I just make one. I've had Iguana Tweaks added, but its worked for the mod pack for a long time.

### Steps to reproduce the issue/bug
I simply just start up the mod pack normally and click on one of my worlds or made a new one.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://pastebin.com/KrEJYqus

I Copied from about where the changes were happening to the end.
Questions:

Did you add any additional mods? - Iguana Tinker Tweaks 1.7.10 2.1.6
Do you use optifine? - No
Did the problem appear in single player or on a server? - Single Player

**Comment by b0bst3r** [comment]
Need the full log please

**Comment by Da-Wrench** [comment]
http://paste.atlauncher.com/view/f7e27c2f

**Comment by Da-Wrench** [comment]
It updated and fixed itself. Thanks for communicating
