### ISSUE TITLE
Minecraft keeps crashing

### ISSUE THREAD

**Issue by DestroyerOfStars** [BevoTechPack/BevoTechPack#1126]
Bevo Tech Pack Version :-  2.21

### Description of issue/bug
When i tried to load the map, it crashed after 2-8seconds. Im sure that its not the problem of my video card or other PC parts, because my PC is like 1.5 months old.

### Steps to reproduce the issue/bug
I tried to reinstall the mods and tried to clone +  manually install the modpack, but it still didnt work.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://pastebin.com/ZfTs3D5v
Questions:

Did you add any additional mods? - No
Do you use optifine? - Dont think so
Did the problem appear in single player or on a server? - In single player

**Comment by b0bst3r** [comment]
Did you pastebin the correct log, that tells me nothing at all?

**Comment by DestroyerOfStars** [comment]
ehm... sorry, but witch log ?? Do you mean the console log ??

**Comment by DestroyerOfStars** [comment]
This is the console log, when i try to load up the map:
http://pastebin.com/jXfNaWjg
