### ISSUE TITLE
GraviChestPlate Multiplayer Issue

### ISSUE THREAD

**Issue by n0bra1ner** [BevoTechPack/BevoTechPack#1129]
Hello all,
I've encountered an issue with my server and require a bit of assistance. The server works fine, no errors or crashes and, when I'm playing alone on the server, everything works fine. The problem arises when anyone else joins the server. If a player has a GraviChestPlate and presses the GraviFly key, the chestplate works as intended, however, when a player with the chestplate comes withing about 140-150 blocks of another player and uses the jetpack, even after turning it off or taking it off, the player is still able to fly as if in creative. Then, because flying is not enabled on my server, they get kicked.

TL;DR: When a player uses the GraviChestPlate near another player, the "creative flight" persists even after turning the chestplate off and/or taking it off.

Bevo Tech Pack Version :- Bevo's Tech Pack BTP-Reborn-Release_2.21

Questions:

Did you add any additional mods? - No
Do you use optifine? - No
Did the problem appear in single player or on a server? - Only when withing 150 blocks of another player.

I'm using the stock BTP, no changes or alterations. 

Let me know if anyone needs any more info. I have been unable to diagnose anything because I'm simply unsure what the issue could be.

Thanks in advance, all the best,
nobrainer

**Comment by b0bst3r** [comment]
Yeah in server.properties enable flying.

**Comment by n0bra1ner** [comment]
Thank you for your responce b0bst3r, however it did not solve my root issue. While I no longer get kicked for using the GraviChestPlate, I still am unable to turn it off. After using the ChestPlate once near other players,, I am able to fly even after I take it off. This happens to any player that uses it.

Thanks,
nobrainer
