### ISSUE TITLE
the build craft quarry does not work i have put in the recipe and that did not work and their is no recipe in the too many items interface plz help 

### ISSUE THREAD

**Issue by jackits** [BevoTechPack/BevoTechPack#1130]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? -

**Comment by b0bst3r** [comment]
http://bevolj.com/forums/index.php?threads/bevos-tech-pack-reborn-faq.865
