### ISSUE TITLE
Loud Noise

### ISSUE THREAD

**Issue by Raeffi** [BevoTechPack/BevoTechPack#1131]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug
I hear a weird growling sound that probably is supposed to play in big caves. It does not change volume when i move.

### Steps to reproduce the issue/bug
Load a world, it instantly starts playing.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
Doesnt crash
Questions:

Did you add any additional mods? - Dragons Radio Mod
Do you use optifine? - No
Did the problem appear in single player or on a server? - Single Player

**Comment by b0bst3r** [comment]
And without the Dragons Radioa Mod does it still occur?

**Comment by Raeffi** [comment]
it shouldnt affect anything as it only plays mp3 files/streams locally (around the radio) and i hear this weird (and because of my subwoofer) painful noise

i will try it though

**Comment by Raeffi** [comment]
I created a second world and there it doesn't occour (with the mod) and i loaded the same map without the mod.

I think it is world related

**Comment by Raeffi** [comment]
UPDATE: The sound stops when i put the weather slider to 0 o.O

**Comment by Raeffi** [comment]
It reappeared

**Comment by Raeffi** [comment]
Can you tell me which mod plays the "dark room noise" when you are in a giant cave ? Maybe i can disable it in the config ?

**Comment by Raeffi** [comment]
It is still there even after reinstalling the pack. plz send help D:

**Comment by b0bst3r** [comment]
I'd love to help but unfortunately I've no idea what causes that or if it's even vanilla.

**Comment by Raeffi** [comment]
My friends say they dont hear it [lan]. Sometimes its not there too. Could it be relatey to my setup ?

**Comment by Raeffi** [comment]
I can record it if it helps. Even if you cant fix it it needs to be documented.

**Comment by Raeffi** [comment]
I found out it only happens when i load the world and my character is located near my base. When i leave and reload anywhere else it stops the noise until i reload in my base .

**Comment by Raeffi** [comment]
I finally figured out what causes the sound but i still cant remove it. Its the sound of a gravitational anomaly from matter overdrive. It seems to come from a nearby (tiny) anomaly. But it should NOT be so loud and annoying :(

**Comment by Watschman** [comment]
I created a Soundpatch for you which replaces the sound from the gravitational anomaly with a silent sound. Just put the zip file into your Resoucepackfolder and activate it like you would do with a Texturepack. https://dl.dropboxusercontent.com/s/0q9sx2yk4pvyh8z/Soundfix.zip?dl=0 . If you can still hear it after that it is not a gravitational anomaly or I missed the proper soundfile in the hurry.

**Comment by Raeffi** [comment]
Thanks but i already partially fixed it by finding and removing 2 gravitational anomalies from the area surrounding my base. It still happened once though and i couldn't find the 3rd one :/

If i cant find it I will very gladly use your sound fix :) (I am scared about running into one without knowing though)
