### ISSUE TITLE
Crafted Items Not Fulfilling Quest Crafting Requirements

### ISSUE THREAD

**Issue by DtDrag** [BevoTechPack/BevoTechPack#1132]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 1.7.10

### Description of issue/bug
If the Magneticraft Crafter is used to craft items required for a quest in the HQM book, the items will not count towards the quest and that portion will remain incomplete. I feel I should also mention that acquiring the Crafter is among the quests in the pack.

### Steps to reproduce the issue/bug
Use the Magneticraft Crafter to craft quest items.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - No
Do you use optifine? - No
Did the problem appear in single player or on a server? - Single Player

**Comment by b0bst3r** [comment]
Yeah no way this will be fixed HQM and Magneticraft have long since stopped mod development in 1.7.10 and also a lot of autocrafting is not recognised by HQM (inc AE2).

**Comment by DtDrag** [comment]
Ah, that's too bad. Say, I know this is off topic but in any future packs you guys do, would you mind adding (if they're compatible) many of the ocean mods, i.e. Small Boats, Mariculture, Oceancraft, Aquatic Abyss, and (the already in use) Shipwrecks.
