### ISSUE TITLE
Minecraft don't start

### ISSUE THREAD

**Issue by mikimil** [BevoTechPack/BevoTechPack#1133]
Bevo Tech Pack Version : 2.21

### Description of issue/bug
minecraft don't start

### Steps to reproduce the issue/bug

http://pastebin.com/q58dCEpQ

Questions:

Did you add any additional mods? 
-AE2 stuff
-Biome Reactors
-Compact Machines
-FastCraft
Do you use optifine? no
Did the problem appear in single player or on a server? -

**Comment by b0bst3r** [comment]
Nvidia updated video drivers kill minecraft, if you downloaded and installed nvidia drivers version 378.49 then you will need to uninstall them and revert back to an earlier version.

More information in this thread - https://www.reddit.com/r/feedthebeast/comments/5pydv9/dont_install_nvidia_gpu_driver_version_37849_it/

**Comment by mikimil** [comment]
thanks and new minecraft starts with the new nvidia drivers ( 378.49 )
