### ISSUE TITLE
Can't Launch BTP

### ISSUE THREAD

**Issue by IFreakZI** [BevoTechPack/BevoTechPack#1134]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug
2 days ago from this post i could play this Modpack Normally but now i cant even get Minecraft to start

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

http://pastebin.com/Jf3LgxEV

Questions:

Did you add any additional mods? -  No.
Do you use optifine? - No.
Did the problem appear in single player or on a server? - I canT even launch mincraft.

**Comment by joeeoj99** [comment]
i'm having the exact same problem, my log even looks exactly the same as yours

**Comment by b0bst3r** [comment]
https://github.com/BevoTechPack/BevoTechPack/issues/1133 Duplicate
