### ISSUE TITLE
Bevo Tech Pack v 2.1 isn't starting after NVIDIA Update

### ISSUE THREAD

**Issue by raidi87** [BevoTechPack/BevoTechPack#1135]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 2.1

### Description of issue/bug
When I'm starting an instance, it isn't starting. The log is searching for updates, don't find any and the window for starting an instance ist open again.

Friend of mine have the same mistake. We niticed that the problem is the newest update of the NVIDIA GeForce Xperience. So is there a possibility to start the Pack with the newest update of NVIDIA?

### Steps to reproduce the issue/bug
Start the Mod pack - get Back to the launcher

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://pastebin.com/fTNPdaEu
Questions:

Did you add any additional mods? - optifine, but it worked with that till the update of NVIDIA
Do you use optifine? - yes
Did the problem appear in single player or on a server? - don't come into the game. so both. 

mfg raidi

**Comment by b0bst3r** [comment]
I can't do anything about this you have to uninstall the drivers and install an earlier version.

Nvidia updated video drivers kill minecraft, if you downloaded and installed nvidia drivers version 378.49 then you will need to uninstall them and revert back to an earlier version.

More information in this thread - https://www.reddit.com/r/feedthebeast/comments/5pydv9/dont_install_nvidia_gpu_driver_version_37849_it/

**Comment by raidi87** [comment]
thanks for the quick answer. Did the downgrade yet. Is working now. Hopefully NVIDIA is fixing that.
