### ISSUE TITLE
BTP crashs after launching 

### ISSUE THREAD

**Issue by overfoxmc** [BevoTechPack/BevoTechPack#1136]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug
BTP crashs after launching with ATLauncher. Java(TM) Platform SE binary does not work anymore

### Steps to reproduce the issue/bug
No idea :/

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
Crashlog: http://pastebin.com/bQs5dqrX
fml-client-latest.log: http://pastebin.com/6DtmGcST
Questions: How to fix the problem?

Did you add any additional mods? - no
Do you use optifine? -no
Did the problem appear in single player or on a server? - Immediately after launching

**Comment by overfoxmc** [comment]
I forgot: 
Operating system: I7-4790k , Geforce GTX 970 , 16GB DDR3-Ram
Anti-Virus: Comodo

**Comment by b0bst3r** [comment]
See https://github.com/BevoTechPack/BevoTechPack/issues/1135
