### ISSUE TITLE
Bevo didn't launch

### ISSUE THREAD

**Issue by tadeuskeks** [BevoTechPack/BevoTechPack#1137]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- all

### Description of issue/bug
Bevo didn't start because it crashed before it going to launch

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://paste.atlauncher.com/view/42d97413
Questions:

Did you add any additional mods? - No
Do you use optifine? - No
Did the problem appear in single player or on a server? - every time when i start the Modpack

**Comment by b0bst3r** [comment]
See https://github.com/BevoTechPack/BevoTechPack/issues/1135
