### ISSUE TITLE
Bevo Tech Pack Server/Singleplayer World Loading Problems

### ISSUE THREAD

**Issue by LenroHD** [BevoTechPack/BevoTechPack#1138]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version : 2.21

### Description of issue/bug
At first sorry for my bad english.
Well.... i made a bevo tech pack server with my friends.
At first everything was fine and we could play on this server with no problems.
But since 3 days ago i couldn´t start the server.

### Steps to reproduce the issue/bug
I´ve already find out, that the problem is the world. I´ve removed the "world" folder, started the server, he created a new world and started with no problems.
I´ve tried to start the world in singleplayer and my Minecraft crashed...
I hope you can help me.
Greetings from Germany

### http://pastebin.com/5LNsKRv8
Questions:

Did you add any additional mods? - Just "fast craft"
Do you use optifine? - No
Did the problem appear in single player or on a server? - Both

**Comment by b0bst3r** [comment]
So you have 2 choices, lets start with the easy one and see if it fixes the world.

Edit config/forge.cfg on the server and change

B:removeErroringEntities=false
B:removeErroringTileEntities=false

both to true, load up your world, it may still crash, load it up again.

If it fixes your world change those 2 back to false (don't play your game with them set to true).

If it fixes the issue close this if it doesn't let me know.

**Comment by LenroHD** [comment]
No..... it haven´t worked.

First start: http://pastebin.com/D1fsRSWp

Second start: http://pastebin.com/wqU7CtAS

**Comment by b0bst3r** [comment]
Ok so you are left with world editing out block located at -345,75,79  the issue you have is the server crashes so you have to do this manually using world edit gui.  It's not something I can talk you through as it's complicated and a wrong move could ruin your world completely.  Do you have someone with World Edit knowledge to do that?

**Comment by LenroHD** [comment]
Only some single basics...
I´ve tried to remove the block and i did it.
But now the server starts without mods..(I did an backup from the world before i did it)

**Comment by LenroHD** [comment]
OH MY GOD
Thank you very much.
After trying to handle MC Edit, i did it. I removed the block and everything works fine now.
After the first try the whole world were reseted, but the mods were working. After the second try the mods didn´t worked, but the world was correct. And after the third try everything is working.
Thank you very much.
