### ISSUE TITLE
Mechanism Metall infuser dös Not create Steel from enriched irondust

### ISSUE THREAD

**Issue by naplivetv** [BevoTechPack/BevoTechPack#1140]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? -

**Comment by b0bst3r** [comment]
Q - What happened to the Mekanism Steel recipe?
A - In short, I butchered it. In long I removed the recipe and after discussions with our group re-added it but changed the recipe to require diamond dust (30) instead. I know the recipe makes no logical sense (diamond dust doesn't make steel) but it was a compromise to the very easy steel recipe mekanism puts in. But that does not mean it costs 3 diamonds to make a steel.... enrich the diamonds for 100 volume in the infuser.
