### ISSUE TITLE
Can't install Instance of BevoTechPack

### ISSUE THREAD

**Issue by hyflicker** [BevoTechPack/BevoTechPack#1141]
Bevo Tech Pack Version :- 2.21

When I go to install an instance of BevoTechPack it starts downloading then it says "Error downloading launchwrapper-1.12.jar ...". It checks all the servers and then it pops up saying "Failed to download file launchwrapper-1.12.jar from all ATLauncherservers. Copied to FailedDownloads Folder. Cancelling install!"

I've tried reinstalling ATLauncher, installing the instance with optional mods or no optional mods, and it stil produces the same outcome.

http://paste.atlauncher.com/view/6a26aec9

Questions:

Did you add any additional mods? - None that were not optional 
Do you use optifine? - No

**Comment by b0bst3r** [comment]
This is a launcher problem not a pack problem, suggest joining Atlauncher Discord https://discordapp.com/invite/0eXDtXikrVAJffxY and seeking help in the #support channel
