### ISSUE TITLE
Inventory Crafting Graphics Glitch (Solved)

### ISSUE THREAD

**Issue by Heliusslayer** [BevoTechPack/BevoTechPack#1142]
Bevo Tech Pack Version :- Bevo's Tech Pack (Bevo's Tech Pack BTP-Reborn-Release_2.21)

### Description of issue/bug
Inventory crafting has a graphical glitch (see photo). It's only the inventory crafting graphics.

![minecraft](https://cloud.githubusercontent.com/assets/26286724/23724733/d9111ed0-041b-11e7-8013-a8c8da39c73d.png)

Did you add any additional mods? - Only BevoTechPack
Do you use optifine? - No
Did the problem appear in single player or on a server? - Single Player

**Comment by b0bst3r** [comment]
It's most likely your resourcepack, remove it and see if the boxes are still mis-aligned.

**Comment by Heliusslayer** [comment]
One of the things I didn't think about... and of course you were right. Thanks.
