### ISSUE TITLE
 Add Mod

### ISSUE THREAD

**Issue by PG-MG** [BevoTechPack/BevoTechPack#1143]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:
Hello,
Is it possible to add a mod?
We would like to add Betterstorage and Computercraft

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? -

**Comment by b0bst3r** [comment]
Nothing stopping you from adding them in but there's enough in those lines already in the pack.
