### ISSUE TITLE
cant load world

### ISSUE THREAD

**Issue by maximo400** [BevoTechPack/BevoTechPack#1144]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug
cant load world

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - big reactors, Archimedes' Ships 
Do you use optifine? - no
[crash-2017-03-24_14.44.04-server.txt](https://github.com/BevoTechPack/BevoTechPack/files/869014/crash-2017-03-24_14.44.04-server.txt)

Did the problem appear in single player or on a server? - single player

**Comment by b0bst3r** [comment]
Your HQM data in your game save needs deleting. In the saves\world folder, you should see a "HardcoreQuesting" folder, go in there and rename the players.dat to something else and try reloading your world. There might/should be a players.dat-backup which you can try renaming to players.dat which may not have got corrupted which you can try.

You can type /hqm edit (if your a server OP) this gives you an OP book to which you can auto complete the quests that you already did.
