### ISSUE TITLE
Magneticraft

### ISSUE THREAD

**Issue by mikekleckner** [BevoTechPack/BevoTechPack#1145]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug

Hi all not sure if this is the best place for this however when I insert ore into the Crusher of Magneticraft it acts like it is doing the work and then outputs nothing. Not sure if its a problem that I'm creating but all the pictures that I have looked at seem exact to this, even when I was using the routing tubes is wasn't outputting anything. Essentially right now it is just eating resources and consuming energy with no result lol.
[Crusher :(](https://imgur.com/a/a2QkC)

### Steps to reproduce the issue/bug

Feed crusher some ore, waste power, returns air

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? -  no
Do you use optifine? - no
Did the problem appear in single player or on a server? - single player

**Comment by b0bst3r** [comment]
Which ore and what pak version?
