### ISSUE TITLE
Bevo's Tech Pack Reborn doesn't work

### ISSUE THREAD

**Issue by FrenzyBoy18** [BevoTechPack/BevoTechPack#1146]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 2.1 (Requiered for the server)

### Description of issue/bug
When I want to start the Modpack it won't load:

### Steps to reproduce the issue/bug
Starting Bevo's Tech Pack

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
https://pastebin.com/38vBGrZQ
Questions:

Did you add any additional mods? - All
Do you use optifine? - None
Did the problem appear in single player or on a server? - Yes I'm the only one

**Comment by b0bst3r** [comment]
The crash log tells me that you possibly have the bad Nvidia driver version which basically stopped Minecraft from working.  Update your video drivers as this has been fixed.  Come back once done and close this if resolved or post again if not.
