### ISSUE TITLE
Server lag/ Error loop.

### ISSUE THREAD

**Issue by Killer595** [BevoTechPack/BevoTechPack#1148]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :-  Release 2.5

### Description of issue/bug
When a player joins joins the server and opens his inventory or opens a UI it causes an error to start and will keep scrolling until he leaves the UI or inventory. It causes massive lag on the server while its cycling.

### Steps to reproduce the issue/bug
It only happens when he plays and not me and when he's not on the server it never has that issue.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
https://pastebin.com/RyPjPHkq
Had to cut and paste the actual error readout since the log of 5 min. of gameplay is like 1.7 GB.
Questions:

Did you add any additional mods? - no
Do you use optifine? - yes, but the player having the issue does not.
Did the problem appear in single player or on a server? - Server side.

**Comment by b0bst3r** [comment]
Get him to try without Fastcraft installed.
