### ISSUE TITLE
Crash with optifine

### ISSUE THREAD

**Issue by Pocketkid2** [BevoTechPack/BevoTechPack#1150]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 2.5

### Description of issue/bug

When I added and enabled Optifine 1.7.10 D8 as a mods folder mod, the bevo tech pack won't start. It crashes and gives an error in the log.

### Steps to reproduce the issue/bug

Download optifine 1.7.10 D8, add as mods folder mod, enable mod, and start the pack.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

https://pastebin.com/y3G2RVvB

Questions:

Did you add any additional mods? - No
Do you use optifine? - Yes
Did the problem appear in single player or on a server? - No

**Comment by b0bst3r** [comment]
Try without Fastcraft

**Comment by Rackoolio** [comment]
Try using **OptiFine_1.7.10_HD_U_D6**
Newer version of Optifine doesn't work for this modpacks...
