### ISSUE TITLE
Cant go to other planets

### ISSUE THREAD

**Issue by KittyKatGamer345** [BevoTechPack/BevoTechPack#1151]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug

I cant launch to other planets in galaticraft

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - no
Do you use optifine? -yes
Did the problem appear in single player or on a server? - on a single player I dont know about on a server.

**Comment by b0bst3r** [comment]
Why?

Rocket doesn't launch?
Map doesn't come up?
You crash?
What?
