### ISSUE TITLE
Quarry not craftable

### ISSUE THREAD

**Issue by Stuhlgang** [BevoTechPack/BevoTechPack#1152]
I cant craft a quarry. if i wana see the recipie nothin comes

Bevo Tech Pack Version :-  1.7.10

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? -

**Comment by b0bst3r** [comment]
From the FAQ

Q - I've been asked on numerous occasions about the Buildcraft Quarry and how to re-enable it (as it's disabled by default), there are so many better less world destructive quarry type machines in this pack from Mekanism's Digital Miner to Magneticraft's Miner to Extra Utilities's Ender Quarry that there are so many better choices. But I still get asked after pointing all those out so, how do you enable the Buildcraft Quarry?
A - Delete minecraft\scripts\bc6.zs, in game do a /mt reload (you will have to start a LAN game and enable cheats if you're playing SSP and the server needs to do this if playing SMP). You need to be running Bevo's Tech pack Release 1.0or later to see the quarry or it will be called a Machine Block.
