### ISSUE TITLE
Unabridged Missing Autobackups?

### ISSUE THREAD

**Issue by Nortalian** [BevoTechPack/BevoTechPack#1153]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- Unabridged 1.7.10

### Description of issue/bug
So, every so often in Unabridged it states that it is performing an auto back up. Something happened in the world that my brother and I had opened to LAN, so we could play together, and we wanted to go to a previous backup to undo the damage. We looked for a while in the file, but the folder marked "backups" was empty, and the modpack didn't show up under "instances" so we can't look at the pack directly. 

### Steps to reproduce the issue/bug
I guess just look in the files?

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
Not a crashlog problem, issue is with the files.
Questions:

**Did you add any additional mods? -** nothing other than some of the optional mods it lists
**Do you use optifine? -** no
**Did the problem appear in single player or on a server? -** Singleplayer opened to LAN

**Comment by b0bst3r** [comment]
Not Bevo's Tech Pack
