### ISSUE TITLE
Cant download pack

### ISSUE THREAD

**Issue by JaySprintYT** [BevoTechPack/BevoTechPack#1155]
Every time I try to download the pack (1.7.10) , I get an error saying it can't find the .jar file for journeymap. I tried fixing this myself by downloading journeymap separately and putting it into the downloads folder, but it gets deleted from it every time I attempt to download the rest of the pack.

http://paste.atlauncher.com/view/7cad53b1

Did you add any additional mods? - no
Do you use optifine? - no

**Comment by Clinterpottrmus** [comment]
Exact same problem

**Comment by b0bst3r** [comment]
Fixed in update
