### ISSUE TITLE
Server Crashing on boot up

### ISSUE THREAD

**Issue by meddlingmayhem** [BevoTechPack/BevoTechPack#1157]
Bevo Tech Pack Version BTP-Reborn-Release_2.6

I started up my server today and it wouldnt start. There is an issue with the world and i dont know how to fix it. I removed the world and started it up and it worked fine. 

Here is a link for the pastebin: https://pastebin.com/7CtJuSzF

**Comment by b0bst3r** [comment]
Your HQM data in your game save needs deleting. Locate your world folder, open that folder up then the  "HardcoreQuesting" folder, go in there and rename the players.dat to something else and try reloading your world.

**Comment by meddlingmayhem** [comment]
I did that and now when I log into my world. It seems my instance crashes. I reinstalled my instance and made a new world. My new world works fine it just seems as though there is a issue with my instance. But it works with the new server fine.

Instance crash report:
here is the link to the pastebin: https://pastebin.com/EPrzayYF
