### ISSUE TITLE
game crashes when getting items from creative (clicking on compass to search for items)

### ISSUE THREAD

**Issue by ericgames234** [BevoTechPack/BevoTechPack#1158]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? -

**Comment by b0bst3r** [comment]
Oh yeah I can see from the crash log you gave me .. oh wait, no I can't.
