### ISSUE TITLE
Can't download Bevo's Tech Pack-Release_2.5

### ISSUE THREAD

**Issue by 6FireBeast6** [BevoTechPack/BevoTechPack#1159]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 2.5

### Description of issue/bug

Can't download Bevo's Tech Pack-Release_2.5. Failed when it tried to download journeymap-1.7.10-5.1.4p1-unlimited.jar . Nitrado doesn't Support the newest Version (2.6) only the Version 2.5 and I want a Server for this Pack.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
https://pastebin.com/pUjbSJJb
Questions: How can I download the pack successfully?

Did you add any additional mods? - No
Do you use optifine? - No
Did the problem appear in single player or on a server? -

**Comment by b0bst3r** [comment]
OK I fixed 2.5
