### ISSUE TITLE
SP lag spikes

### ISSUE THREAD

**Issue by ColouReZ** [BevoTechPack/BevoTechPack#1160]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug

Every 10-20 seconds or so my single player world gets a 3-5 second lag spike where all my actions are erased. For example if a few monsters are attacking me during the lag spike I don't notice anything until the lag spike is over and everything that happened during the lag spikes happens within a fraction of a second. I can still walk around normally and I'm getting 200-300 fps. I have 4 GB ram allocated which is 50% of my total and in game the ram usage lies between 50-60%.

### Steps to reproduce the issue/bug

It happens by itself pretty frequently.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - I enabled all the optional mods but didn't add any more.
Do you use optifine? - If it's already in the modpack I do, otherwise not.
Did the problem appear in single player or on a server? - Single player

**Comment by ColouReZ** [comment]
The modpack's version is: Reborn Release 2.6

**Comment by ColouReZ** [comment]
It got fixed after removing highlands.

**Comment by b0bst3r** [comment]
I messed up 2.6, it has major ID conflicts which I'm sorting out now.
