### ISSUE TITLE
Bevors Tech pack crash 

### ISSUE THREAD

**Issue by Marcel3006** [BevoTechPack/BevoTechPack#1161]
Hello, I have an poblem with this modpack i loved to play it but at the moment i can*'t because the game craash at loading I hope anyone can halp me please. 

Bevo Tech Pack Version :-2.6

The game crash after loading the construction mod it must be a coustom mod but can't find wich

Hers the Link to the Crash report: 
http://paste.atlauncher.com/view/9bf4d5d6

Questions:

I added following mods 
- Big Reactors 
- Thermal Dynamics
-3D furnfaces
-advance genetics
-archimedis ships
-Bioms ore plenty
-Slimevoid library
- Tropicraft
-world edit forge 

all mod versions are for the pack version 1.7.10 

i ope you can help me.
thank you

**Comment by b0bst3r** [comment]
You need to remove the mods you added 1 by 1 until it loads as one of them is stopping adv machines from loading
