### ISSUE TITLE
wont download 

### ISSUE THREAD

**Issue by Kek-istan** [BevoTechPack/BevoTechPack#1162]
Bevo Tech Pack Version:- BTP-Reborn-Release_2.6 (1.7.10)

### Description of issue/bug?
it won't download from the launcher pack thing [other mod packs will] 

### Steps to reproduce the issue/bug?
im lost and confused and lost so I have not done any 

### Link to crash log (do not paste full crash logs in this issue, use pastebin.com)
 http://paste.atlauncher.com/view/c4f9f87d
I am aware it requests for me to use pastebin.com but im not smart enough to know the kind of programmes which cause the problem so it's useless.
edit: added it anyway ... might have fucked up but whatever 
https://pastebin.com/RuqLv31E 
 

Questions:

Did you add any additional mods? - no
Do you use optifine? - no 
Did the problem appear in single player or on a server? - if only I got that far 

thanks in advance

**Comment by b0bst3r** [comment]
Do this:
Create a folder called c:\atlauncher or use another drive if you have more
Place the atlauncher.exe in the c:\atlauncher folder
Run atlauncher.exe from c:\atlauncher
Download the pack

Tell me if that works, where you are trying to save packs to is protected by the Windows Operating System.

**Comment by Kek-istan** [comment]
that was not the problem [my fault for explaining it shittly] but I have made process I have identified the problem as being the mod journeymap [http://www.9minecraft.net/journeymap-mod/] mod so if that helps i don't think the problem is with forge because other mod packs work like a dream so idk. 
thanks for the help and any in advance
