### ISSUE TITLE
world issues my game saves 

### ISSUE THREAD

**Issue by ZenoniaSoul** [BevoTechPack/BevoTechPack#1164]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? - 
every time I load my saved world it doesn't load with what I originally would save and quit the game with everytime I go to play the world I saved all the things like tools and materials I gather disappear and all I have is 3 books its been doing this ever since I updated the game and it wont load like it should it glitches and all my things I had are gone ,,,,,,,,,,,, oh yeah and when I do get into my world I saved I back where I first started and all my gear like armor weapon and materials I gathered like ores , wood, and saplings from cutting trees disappear and I have 3 books and no quest book either. I love the mod pack up until the last up date please fix it thanks

**Comment by b0bst3r** [comment]
When you save and exit look in the atlauncher log which runs concurrently with Minecraft and paste any crashes it might come up with.
