### ISSUE TITLE
Buildcraft

### ISSUE THREAD

**Issue by Ivashkas** [BevoTechPack/BevoTechPack#1165]
Sorry for my english.
I can't craft quarry.
if i try watch craft, i will see that:
[Picture (link)](https://yadi.sk/i/DMyFzOZ83LexVL)
Please, help me. I will wait,thinks)

**Comment by Watschman** [comment]
The normal Buildcraft quarry is disabled on purpose, use Extra Utilities "Ender Quarry" instead.

**Comment by Ivashkas** [comment]
okey. Can i activated craft "quarry" in the simple game?(I want)

**Comment by b0bst3r** [comment]
Q - I've been asked on numerous occasions about the Buildcraft Quarry and how to re-enable it (as it's disabled by default), there are so many better less world destructive quarry type machines in this pack from Mekanism's Digital Miner to Magneticraft's Miner to Extra Utilities's Ender Quarry that there are so many better choices. But I still get asked after pointing all those out so, how do you enable the Buildcraft Quarry?
A - Delete minecraft\scripts\bc6.zs, in game do a /mt reload (you will have to start a LAN game and enable cheats if you're playing SSP and the server needs to do this if playing SMP). You need to be running Bevo's Tech pack Release 1.0 to see the quarry or it will be called a Machine Block.
