### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AnnaGautrey** [BevoTechPack/BevoTechPack#1166]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug
When on creative mode, the game crashes every time you click the search tab in inventory

### Steps to reproduce the issue/bug

?

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - no
Do you use optifine? - no
Did the problem appear in single player or on a server? - single player

**Comment by Watschman** [comment]
a crashlog would be nice to determine what exactly is causing it.
You can find the crashlog in your instancefolder in the folder crash-logs.

**Comment by bradster2214** [comment]
it happens to me aswell, i've added my crash logs, they should be similar
[crash-2017-08-05_16.46.17-client.txt](https://github.com/BevoTechPack/BevoTechPack/files/1202252/crash-2017-08-05_16.46.17-client.txt)
[crash-2017-08-05_18.11.03-client.txt](https://github.com/BevoTechPack/BevoTechPack/files/1202253/crash-2017-08-05_18.11.03-client.txt)
