### ISSUE TITLE
Can not craft the first rocket.

### ISSUE THREAD

**Issue by NopileosMC** [BevoTechPack/BevoTechPack#1168]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- BTP Reborn Release 2.6.6

### Description of issue/bug
As Title says: cant craft the first Tier 1 rocket, parts i could craft but at the NASA-Workbench
it does nothing after putting in the items.
1 nose cone 5705
8 Heavy-Duty Plate 5704
4 Rocket Fins 5706
1 Tier 1 Rocket Engine 5703
(dunno if it's important: i followed the steps in the "Quest Book" and there is written that i have to "use the "Packing Tape 7841" to fix the stuff together.)

### Steps to reproduce the issue/bug
put stuff in the NASA Workbench and nothing happens

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://paste.atlauncher.com/view/7c914fc3

Questions:

Did you add any additional mods? - No
Do you use optifine? - dunno, how do i find out?
Did the problem appear in single player or on a server? - Single Player

**Comment by NopileosMC** [comment]
UPDATE:

It look's like i can't craft any rockets..... :(

**Comment by lAimBotl** [comment]
click the arrow in nei, you need 3 more items :)
