### ISSUE TITLE
Won't launch in the morning (Not even a joke)

### ISSUE THREAD

**Issue by GazelleSamyueru** [BevoTechPack/BevoTechPack#1170]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug

Idk if I'm meant to delete all this stuff so I won't... anyway, if I try to launch the pack in the morning it will crash when trying to load the textures. If I try in the evening it will work fine. It's happened two days in a row, which isn't very long, but I feel it's specific enough to be a genuine bug.

### Steps to reproduce the issue/bug

Launch the game in the morning. Honestly. 

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

https://pastebin.com/rsuMu81G

Questions:

Did you add any additional mods? - no
Do you use optifine? - no
Did the problem appear in single player or on a server? - N/A

**Comment by b0bst3r** [comment]
Remove Fastcraft
