### ISSUE TITLE
Crashes when pressing the vanilla search button

### ISSUE THREAD

**Issue by tz44** [BevoTechPack/BevoTechPack#1171]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug
When you are in creative mode, if you go into the inventory and press the search button, the game just suddenly closes
### Steps to reproduce the issue/bug
What I said above ^^

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
Doesnt have a crashlog that i can find
Questions:

Did you add any additional mods? - just the reccomended ones from ATlauncher
Do you use optifine? -no
Did the problem appear in single player or on a server? - Single Player

**Comment by yukiteramanu** [comment]
Hello, 

I have the same problem!! Someone help us please!! ahah

**Comment by b0bst3r** [comment]
Not a lot I can do 1.7.10 stopped being updated a long time ago.
