### ISSUE TITLE
bevo tech pack crash 

### ISSUE THREAD

**Issue by GermanShadow** [BevoTechPack/BevoTechPack#1174]
Hello, I have an poblem with this modpack i loved to play it but at the moment i can*'t because the game craash at loading I hope anyone can halp me please.

Bevo Tech Pack Version :- 2.7.0

### Description of issue/bug
The game crashes after it has finished loading.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
 http://paste.atlauncher.com/view/b052b2c0
Questions:

Did you add any additional mods? - i have no mods add
Do you use optifine? - i dont use optifine
Did the problem appear in single player or on a server? - I have no idea

**Comment by b0bst3r** [comment]
Try increasing RAM to 4GB.
