### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by LapisYT** [BevoTechPack/BevoTechPack#1176]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version:- 1.7.10

### Description of issue/bug
When you go to the search tab in the inventory the game crashes

### Steps to reproduce the issue/bug
None

### Link to crash log (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? -

**Comment by b0bst3r** [comment]
https://github.com/BevoTechPack/BevoTechPack/issues/1171
