### ISSUE TITLE
bevos tech pack 2.7.0 crashes

### ISSUE THREAD

**Issue by imnotfamous** [BevoTechPack/BevoTechPack#1178]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 2.7.0

### Description of issue/bug
the pack use work perfectly, but now it crashes everytime i try to load a world.
i tried increasing max ram to 8gb and updating video drivers but it didnt help.

### Steps to reproduce the issue/bug
1.use my pc
2.launch a world

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
https://pastebin.com/sKUuT5wd
Questions:
how to fix it?
Did you add any additional mods? - no
Do you use optifine? - no
Did the problem appear in single player or on a server? - single player

**Comment by b0bst3r** [comment]
Your HQM data in your game save needs deleting. In the saves\world folder, you should see a "HardcoreQuesting" folder, go in there and rename the players.dat to something else and try reloading your world. There might/should be a players.dat-backup which you can try renaming to players.dat which may not have got corrupted which you can try.

You can type /hqm edit (if your a server OP) this gives you an OP book to which you can auto complete the quests that you already did.

**Comment by imnotfamous** [comment]
thanks so much!
