### ISSUE TITLE
BevosTechPack_BTP12Mini Serverproblem on ubuntu

### ISSUE THREAD

**Issue by Fknclown** [BevoTechPack/BevoTechPack#1180]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :-   BevosTechPack_BTP12Mini 

### Description of issue/bug
Failure to lanch BevosTechPack_BTP12Mini server on ubuntu

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
https://pastebin.com/AkBWqYQh

Questions: I am new to ubuntu, what am i doing wrong?

Did you add any additional mods? - Not that i am aware of, downloaded the server through ATLauncher
Do you use optifine? - I dont know..
Did the problem appear in single player or on a server? -  Server

**Comment by Darylth** [comment]
Im no expert, extremely far from it, but try disabling journey map and starting it again and let me know if that works?

**Comment by Fknclown** [comment]
Yeah, that did the trick. Thanks :)


________________________________
Från: Darylth <notifications@github.com>
Skickat: den 5 mars 2018 05:58
Till: BevoTechPack/BevoTechPack
Kopia: Fknclown; Author
Ämne: Re: [BevoTechPack/BevoTechPack] BevosTechPack_BTP12Mini Serverproblem on ubuntu (#1180)


Im no expert, extremely far from it, but try disabling journey map and starting it again and let me know if that works?

**Comment by Darylth** [comment]
Your welcome :)
