### ISSUE TITLE
key Bindings

### ISSUE THREAD

**Issue by WildBill55** [BevoTechPack/BevoTechPack#1182]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? - 
Hello, my problem is the key bindings, when I look at the controls there is alot that are red. I've tried reassigning the keys, but there is not enough keys on the keyboard to change them all, therefore it has caused a conflict when you push a key it either doesn't respond or it opens something different then what you exoected, like pushing b to mark a spot, nothing happens.

**Comment by Watschman** [comment]
That is normal in a Modpack. You can just reassign unneeded keys to the same like ' or similar, so only your unneeded keys conflict with one another and your useful keys are left for the frequently used shortcuts.

**Comment by b0bst3r** [comment]
Yeah not enough keys :) can't fix that, just unmap what you aren't using and map what you are, like every other pack out there this is a problem.
