### ISSUE TITLE
World crashed during loading

### ISSUE THREAD

**Issue by toffers** [BevoTechPack/BevoTechPack#1184]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 2.7.0

### Description of issue/bug
After i start my world, Minecraft load a few second and closed/crushed then. ATLauncher open automatcly in the "Instance-Screen"

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
http://paste.atlauncher.com/view/920acfe7
Questions:

Did you add any additional mods? - no
Do you use optifine? - no
Did the problem appear in single player or on a server? - singleplayer

**Comment by b0bst3r** [comment]
Your HQM data in your game save needs deleting. In the saves\world folder, you should see a "HardcoreQuesting" folder, go in there and rename the players.dat to something else and try reloading your world. There might/should be a players.dat-backup which you can try renaming to players.dat which may not have got corrupted which you can try.

You can type /hqm edit (if your a server OP) this gives you an OP book to which you can auto complete the quests that you already did.
