### ISSUE TITLE
Suggestion Please good sir consider adding these mods?

### ISSUE THREAD

**Issue by bookerthegeek** [BevoTechPack/BevoTechPack#762]
Please consider adding these following mods into your wonderful pack good sir...

| Mod name | Link |
|----------------|---------------|
| Tinker's Stealworks | https://github.com/Ephys/TinkersSteelworks/releases |
| Blue Power | http://minecraft.curseforge.com/mc-mods/223099-blue-power |
| Forbidden magic | http://minecraft.curseforge.com/mc-mods/224237-forbidden-magic |
| Sanguimancy | http://minecraft.curseforge.com/mc-mods/223722-sanguimancy |
| Fluxed Trinkets | http://minecraft.curseforge.com/mc-mods/224164-fluxed-trinkets |
| Thaumic NEI | http://minecraft.curseforge.com/mc-mods/225009-thaumicnei |
| Iron Chest Minecarts | http://minecraft.curseforge.com/mc-mods/224989-iron-chest-minecarts |
| Baublelicious | http://minecraft.curseforge.com/mc-mods/223951-baublelicious |
| Sanguine Utilities | http://minecraft.curseforge.com/mc-mods/225413-sanguine-utilities |

Thank you for taking the time to read my wall of text, and hopefully I will find some of my suggestions in your next release.

**Comment by Alex-hawks** [comment]
Even if it did have a place in the pack, I would highly advise against adding Sanguine Utilities in its current state. There are a couple of crashes that I need to fix before I encourage people to put it in packs
