### ISSUE TITLE
Pack Not Starting

### ISSUE THREAD

**Issue by Brain888** [BevoTechPack/BevoTechPack#771]
Whenever I launch it, the pack doesn't start, and give me this log.

http://pastebin.com/0YrGa7q1

**Comment by LightningJimmy** [comment]
Check which version of Java you have. I think Minecraft Forge 1.7.10 only allows Java 7. This problem is common in computers with Java 8.

**Comment by Brain888** [comment]
I checked and I have Java 7 :/

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
