### ISSUE TITLE
Index out of bounds, galacticraft.

### ISSUE THREAD

**Issue by magnusjjj** [BevoTechPack/BevoTechPack#773]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 11/12/14 20:26
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 9
        at micdoodle8.mods.galacticraft.core.tile.TileEntityElectricIngotCompressor.func_94128_d(TileEntityElectricIngotCompressor.java:419)
        at appeng.util.Platform.generateTileHash(Platform.java:1520)
        at appeng.parts.automation.PartSharedItemBus.getHandler(PartSharedItemBus.java:88)
        at appeng.parts.automation.PartImportBus.getTickingRequest(PartImportBus.java:161)
        at appeng.me.cache.TickManagerCache.addNode(TickManagerCache.java:206)
        at appeng.me.GridCacheWrapper.addNode(GridCacheWrapper.java:52)
        at appeng.me.Grid.add(Grid.java:193)
        at appeng.me.GridNode.setGrid(GridNode.java:242)
        at appeng.me.Grid.<init>(Grid.java:71)
        at appeng.me.GridNode.getInternalGrid(GridNode.java:150)
        at appeng.me.GridNode.updateState(GridNode.java:208)
        at appeng.me.helpers.AENetworkProxy.getNode(AENetworkProxy.java:159)
        at appeng.me.helpers.AENetworkProxy.onReady(AENetworkProxy.java:199)
        at appeng.parts.AEBasePart.addToWorld(AEBasePart.java:202)
        at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:369)
        at appeng.tile.networking.TileCableBus.onReady(TileCableBus.java:141)
        at appeng.hooks.TickHandler.onTick(TickHandler.java:256)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_429_TickHandler_onTick_TickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Linux (amd64) version 3.2.0-58-virtual
        Java Version: 1.7.0_65, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 281012112 bytes (267 MB) / 1095761920 bytes (1045 MB) up to 1908932608 bytes (1820 MB)
        JVM Flags: 2 total; -Xmx2G -XX:MaxPermSize=256M
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
        FML: MCP v9.05 FML v7.10.85.1236 Minecraft Forge 10.13.2.1236 158 mods loaded, 157 mods active
        mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        FML{7.10.85.1236} [Forge Mod Loader] (forge-1.7.10-10.13.2.1236-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Availabl$
        Forge{10.13.2.1236} [Minecraft Forge] (forge-1.7.10-10.13.2.1236-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Availab$
        appliedenergistics2-core{rv2-alpha-29} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Avail$
        Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->$
        CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        <CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        NotEnoughItems{1.0.3.73} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.73-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Availab$
        OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        malisiscore{1.7.10-0.10.2+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->A$
        IC2{2.2.654-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.654-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Availab$
        AdvancedMachines{1.1.2} [IC2 Advanced Machines Addon] (AdvancedMachinesAS-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->A$
        AppleCore{1.0.1} [AppleCore] (AppleCore-mc1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        appliedenergistics2{rv2-alpha-29} [Applied Energistics 2] (appliedenergistics2-rv2-alpha-29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->A$
        Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available$
        Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Av$
        AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        asielib{0.3.4} [asielib] (AsieLib-1.7.10-0.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Backpack{2.0.0} [Backpack] (backpack-2.0.0-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
(cut here)

     OpenModsLib crash transformers: [gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED],[map_gen_fix:FINISHED],[movement_callback:ENABLED],[stencil_patches:ENABLED]
        AE2 Version: alpha rv2-alpha-29 for Forge 10.13.2.1230
        Mantle Environment: Environment healthy.
        TConstruct Environment: Environment healthy.
        AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, MJ6:ON, MJ5:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:ON, FMP:ON, RB:OFF, CLApi:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, Be$
        Profiler Position: N/A (disabled)
        Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Player Count: 0 / 10; []
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)

Seems to be an interaction between our AE system and galacticraft ingot compressor. This came up right after we updated from BTP 10.8 to BTP 11.

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
