### ISSUE TITLE
MFR TileEntityRedNetCable crashing server BTP11 Full

### ISSUE THREAD

**Issue by sanek2k6** [BevoTechPack/BevoTechPack#775]
Hello,

I just upgraded the server from BTP 10.8 to BTP 11 and looks like everything started up fine, but few minutes later, it crashed with a RuntimeException, seemingly caused by TileEntityRedNetCable.

The exception does contain the entity coordinates, so I'll try to see whats going on there. I have not tried logging in yet, but I might have to remove the offending block, although I am concerned there might be other occurrences.

Crash report:
http://pastebin.com/LJ28wV9R

//Edit: Rednet cables are connected to several pulverizers and one of them was crashing the server at random intervals, usually every 15-30 minutes.

//Edit2: Replaced all Rednet cables with Red Alloy Wires and everything seems stable now.

**Comment by MrTool** [comment]
Same problem here

**Comment by deB4SH** [comment]
to extend @MrTool problem, the cable produced this issue was in a combination of reciever transmitter and a rednet controller. maybe this helps somehow

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
