### ISSUE TITLE
NEI Crash to desktop

### ISSUE THREAD

**Issue by OCDiary** [BevoTechPack/BevoTechPack#776]
Whenever I try to look at a recipe in nei it crashes my minecraft back to desktop. However it works fine in single player mode? It's only on multiplayer that the issue occurs. I've been troubleshooting with a friend on the server (NEI works perfectly for him) and I am using the same Java, same btp install (11-full). I've tried everything and just can't get it to work so hope someone here can help thanks guys
Crash log: http://pastebin.com/cy2EMFB1 
Console log: http://pastebin.com/rCMd2rMu

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
