### ISSUE TITLE
Links are not clickable in chat - BTP11 Forge

### ISSUE THREAD

**Issue by sanek2k6** [BevoTechPack/BevoTechPack#777]
Links are not getting detected automatically anymore (I think this was also an issue in the last version of the pack as well). If you send the link as Json (i.e. using tellraw command), everything works, but if you simply send a link in the chat, it will not be clickable.

Running the server using the included forge, so that might be where the issue is.

Thanks!

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
