### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by Tearahk** [BevoTechPack/BevoTechPack#779]
After updating the pack I loaded up my world only to find that certain blocks are refusing to render. All of my TCon blocks, as well as my chisel blocks aren't showing up, only the bounding boxes are displaying. That, and various other mod blocks are also refusing to show up. I have shut down and restarted my map several times, but nothing seems to be working.

Does anyone know how to fix this issue?

**Comment by BevoLJ** [comment]
Just updated the pack and optifine should work fine now. Please let me know if this is still an issue in BTP 12.
