### ISSUE TITLE
Crash when put Open Blocks Tank into Flaxbeard's steam power mod's standard boiler

### ISSUE THREAD

**Issue by MinecraftsBestGuy** [BevoTechPack/BevoTechPack#780]
When i out the tank inside of the boiler and then it crashed. is  this a problem with FSPM or Open blocks? I would say the tank was not full when i put it in,but i,for less than a second,(before crashing)saw it go down.please fix this.

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
