### ISSUE TITLE
Server crash issue between Galacticcraft and extra utilities

### ISSUE THREAD

**Issue by thecrazyrai** [BevoTechPack/BevoTechPack#788]
I placed down a retrievel transfer node (items) between a compressor and a electric compressor from galacticcraft 
crash-report:
https://www.dropbox.com/s/mdiqfij2glqkfn1/crash-2014-12-19_17.58.35-server.txt?dl=0

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
