### ISSUE TITLE
mekanism cardboard box on aura node [sometimes] causes server crash

### ISSUE THREAD

**Issue by kuzetsa** [BevoTechPack/BevoTechPack#790]
https://github.com/Azanor/thaumcraft/issues/1211 << it's fixed in thaumcraft 4.2.2.0

{[quote / copied from changelog / thaumcraft-4-2-2-0-updated-2014-12-21](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292130-thaumcraft-4-2-2-0-updated-2014-12-21)}
> Crash prevention in nodes and buffers

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
