### ISSUE TITLE
Can't launch Bevo's Tech Pack

### ISSUE THREAD

**Issue by jd5698** [BevoTechPack/BevoTechPack#791]
Hi so I've been trying to launch Bevo's Tech Pack for the last day or so and I can't seem to launch it.
Here is the pastebin of the logs: http://pastebin.com/B78hir5q.
Basically what happens is I load the instance and the console loads and then minecraft loads however does not respond and eventually crashes.

**Comment by Xfel** [comment]
Also don't forget to increase the PermGen space, as that is what you actually ran out of.
