### ISSUE TITLE
JABBA barrels can break AE2 inscribers

### ISSUE THREAD

**Issue by seebs** [BevoTechPack/BevoTechPack#793]
A JABBA barrel with a "hopper upgrade" can insert more than one object into an inscriber, which breaks all inscriber recipes.

Reproducer: Inscriber with silicon press, JABBA barrel with hopper upgrade and hopper facade pointed at "side" of inscriber. Note how inscriber ends up with more than one silicon, and since that's not a valid recipe, it doesn't process them.

Not sure which mod's fault this is, but given that conduits, pipes, hoppers, and everything else, seem to work fine with inscribers, I bet JABBA.

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
