### ISSUE TITLE
unable to connect to server

### ISSUE THREAD

**Issue by sennettt** [BevoTechPack/BevoTechPack#794]
Hey,
So i have recently been switched to fiber optic internet, so new router and everything, i have set up the router  and everything is running fine, i can check my server using https://dinnerbone.com/minecraft/tools/status/  ,
it shows my server is up what version of mine craft ect. i can direct connect but  cannot connect through  any other means, even though that says that the server is up,  i do not get any message of anything trying to connect (yes i have checked firewalls)
anyone have any idea?

**Comment by Xfel** [comment]
if you post the client log, we might be able to tell you more.

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
