### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by Zombatron** [BevoTechPack/BevoTechPack#796]
Hey,

So, I have just installed this modpack. It keeps crashing and when I check the logs it says that it has something to do with chickenchunks?
Anyway, here is the coding
http://pastebin.com/ayptXPXm
Could someone please help? I would love to play this mod pack

**Comment by Sabster** [comment]
Error says file not found - try a reinstall.

**Comment by Zombatron** [comment]
Thank you. I don't understand why it worked this time! I tried that like 7 times :/ Anyway, thanks
