### ISSUE TITLE
Thaumcraft, Bees, but not Magic Bees?

### ISSUE THREAD

**Issue by Tokoshoran** [BevoTechPack/BevoTechPack#797]
I get this pack is supposed to have a focus on technology, not on magic, but since Thaumcraft is already included, why not Magic Bees? It's basically just closing the gap between Thaumcraft and Forestry, just as you have Trahermagy (built into Railcraft by default) that closes the gap between Railcraft and Thaumcraft.
...That, and despite being a magic mod, Thaumcraft is very science-y.

**Comment by Yulife** [comment]
Trahermagy is automatically into Railcraft, however, Magic Bees is a whole different and mod and iirc Bevo does not want to add any TC4 addons.

**Comment by Tokoshoran** [comment]
Personally, I feel that Magic Bees is more of a necessary wedge than an add-on.
