### ISSUE TITLE
Bevo's Tech Pack don't download a library

### ISSUE THREAD

**Issue by Hyderatic** [BevoTechPack/BevoTechPack#800]
When i am starting a new instance for the pack it downloads everything but a library called akka_actor_2.11-2.3.3.jar. A log is here : http://paste.atlauncher.com/view/ad53c180

**Comment by Xfel** [comment]
See #486

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
