### ISSUE TITLE
DSU & ME causing lags

### ISSUE THREAD

**Issue by MrTool** [BevoTechPack/BevoTechPack#801]
Hi Bevo,

I know that you are not the programmer of MineFactory Reloaded neither from AppliedEnergistics but maybe someone of your pack users are helpful and can confirm an lag causing build.

Currently one of the people on my server is using the Deep Storage Unit with ME Storage/Export Buses and we found out that this combination causes tick skipping and enormous chunk updates.

If someone of you would try this combination and could tell if you can confirm that, that would be great.

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
