### ISSUE TITLE
Open Lan Server, Player cannot mine after crash

### ISSUE THREAD

**Issue by alatyami** [BevoTechPack/BevoTechPack#802]
LAN Player as able to mine and interact with the world when the client crashed. After returning to the world, the player can place blocks and interact with the inventory items but cannot mine/break blocks unless they are in creative. 

No errors show up in the client or the LAN/host client client.

**Comment by Xfel** [comment]
Is it possible that you have accidentally been set to adventure mode?

**Comment by alatyami** [comment]
Thanks for the follow-up. Inspecting the players .dat file it says that they are in mode 0. The instance allows for "cheats" and they can switch to Creative (can break blocks) and then back to survival (cannot break blocks). I'll delete their dat file and get back to you.

**Comment by Sabster** [comment]
Just as a suggestion:  I would have the player do a /gamemode 0 - just to make sure they are in the right mode.  My first thought when I read this was they were in adventure mode.

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
