### ISSUE TITLE
Bevo Pack started to crash

### ISSUE THREAD

**Issue by richardrickard44** [BevoTechPack/BevoTechPack#806]
I have a back up.
I am an older man, so I need a detailed list on how to put my backup into the pack, so it will work again.
I looked in the saves and double clicked on, it but non-thing happens. so that not the way.
So I need help.
Thanks Rick

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.

**Comment by richardrickard44** [comment]
It works,if you start a new world. But my world does not work and I lost all the months of work I put into it. 
I had the same problem using your first pack 1.6
Is there a way to use the back up? 
I had the same problem with other packs on AT launcher. Never had a problem with FTB packs.

On Feb 21, 2015, at 04:44 PM, BevoLJ <notifications@github.com> wrote:

Just updated the pack. Please let me know if this is still an issue in BTP 12.
