### ISSUE TITLE
Mekanism disables my texture packs for some reason

### ISSUE THREAD

**Issue by seiclone37** [BevoTechPack/BevoTechPack#810]
I'm running Minecraft Forge 1.7.10 and I have a bunch of mods installed that all run perfectly. I also have the SPHAX/BDCraft texture packs installed for all of these mods, which work fine too. I downloaded Mekanism and put it into my mods folder like with almost every mod and I ran Minecraft, but my textures were all back to the base Minecraft textures, which honestly look kinda bad after using SPHAX. I went to the Resource Packs tab and clicked the little "play" button on the texture packs to move them over from the left to the right to enable them. When I click done all the textures are still back to base Minecraft. I also found another place to download Mekanism and I figured I must've done it wrong before so I used this different installer thing. When I started Minecraft the same exact texture thing happened again. I have absolutely no clue how to fix this and I have scoured the internet for hours trying to find someone who could help or had the same problem and i can't find anything. Literally nothing anywhere on all of the internet. I just cannot understand why Mekanism disables my texture packs. Please help. Thanks.

**Comment by Sabster** [comment]
You should probably ask the mekanism guys.  It sounds like you aren't even using bevo's tech pack so not sure why you came here  :)

**Comment by seiclone37** [comment]
@Sabster Sorry I didn't realize this was for a specific pack. Thanks anyways. Do you happen to know how I can ask the right people about this?

**Comment by Sabster** [comment]
No worries  :)
Sphax:  http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1229984-sphax-purebdcraft-04-02-15-all-resolutions-100

Mekanims:  http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284681-mekanism-v7-seismic-vibrators-5x-ore-duplication

Try those two for starters.  It's always a pretty sure bet if you search for <mod name> minecraftforum - you'll find the specific mod in question  :)
