### ISSUE TITLE
Chunks failing to render?

### ISSUE THREAD

**Issue by xXxMountainJewritos42069xXx** [BevoTechPack/BevoTechPack#811]
Hello,

I tried playing this pack from the ATLauncher, but when I loaded a world and started playing, I could only load so many chunks before it just stopped. I waited and waited, suspecting lag, but nothing happened.

![2015-02-14_22 32 59](https://cloud.githubusercontent.com/assets/11013714/6202359/de3be4e4-b49a-11e4-9256-ba29f5eb0234.png)

It also seems that past the void of nothingness, there's more loaded chunks. I don't know what's happening. :/

Any input, anyone?

**Comment by Sabster** [comment]
Sounds like you don't have sufficient memory/resources

**Comment by xXxMountainJewritos42069xXx** [comment]
Well then, what would be considered "sufficient memory/resources?"

**Comment by Sabster** [comment]
Anything over 4 gig is usually enough - without seeing your system, one can only hazard a guess as to what's going on...

**Comment by BevoLJ** [comment]
Just updated the pack with Fastcraft. This should be sorted in BTP 12. Pls let me know if it isn't.
