### ISSUE TITLE
No info about voxelmapNoRadar in ATLauncher page

### ISSUE THREAD

**Issue by JAWSAWN** [BevoTechPack/BevoTechPack#812]
I really liked that map mod but couln't find any info about where can I download it from the source? Thinking about putting it in my modpack.

**Comment by Sabster** [comment]
Journeymap is way better in my opinion; but search the internet...

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290155-liteloader-for-minecraft-1-7-10?page=97#c1965

**Comment by JAWSAWN** [comment]
Ok thanks for help.
I'l proubly usr journeymap instead maybe
