### ISSUE TITLE
Can't place any modded items or blocks?

### ISSUE THREAD

**Issue by batteryacidd** [BevoTechPack/BevoTechPack#813]
I created a server for me and my friends using the BTP Mini version. I have all of the mods enabled and in game, I see all of the mod's items in both the item menu in survival and creative. When I click on one of them in the item menu in survival, it says, "There is no such item with ID (####)". In creative, I pick a modded item or block, and when I place it, it disappears immediately. The vanilla Minecraft blocks can be placed normally, but none of the items or blocks from BTP mod's are placeable.

**Comment by BevoLJ** [comment]
Just updated the pack. This should be sorted in BTP 12. Pls let me know if it isn't.
