### ISSUE TITLE
Crashing When Opening Inventory

### ISSUE THREAD

**Issue by JacobGreenbaum** [BevoTechPack/BevoTechPack#814]
Hi. I am not sure if this is a problem with a certain instance of anything, but it is a huge issue I am having and need help with. Whenever I load Bevo's Tech Pack and go onto my brothers world, I can play perfectly time with minimal lag and no issues. When I go to open my inventory (no matter what key I change the button to) The pack crashes and I get kicked out of the world. I have deleted the launcher and re downloaded it completely, but no luck. Please send me a guide of what to do I am frustrated and I am not able to play with my brother. PLEASE HELP!

**Comment by Sabster** [comment]
It's been said that if you have mods installed that aren't on the server - you'll crash NEI.  I would start there...

**Comment by BevoLJ** [comment]
There is likely a mod miss match.  Pls let me know if this didn't get sorted.

**Comment by JacobGreenbaum** [comment]
I went through and double checked the mod list twice myself, thinking it was the same thing but I came to the conclusion that they were identical. About 20% of the time it will let me log in and play as well as open my inventory, but the other 80% of the time I am not able to. I reinstalled the pack, restarted the computers, and switched internet a but I am still having the issue,

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.

**Comment by JacobGreenbaum** [comment]
Ok I am not at home right now, but thanks. In about 4 hours I will be home and I will let you know.

**Comment by JacobGreenbaum** [comment]
Does it need to be reinstalled or just updated?

**Comment by BevoLJ** [comment]
Just updated.  Although the server will need to be updated too.

**Comment by JacobGreenbaum** [comment]
The update did not fix the issue :(

**Comment by BevoLJ** [comment]
can you post a log?

**Comment by BevoLJ** [comment]
Also if you have any suggestions on how I might go about reproducing this issue that would be awesome.
