### ISSUE TITLE
Minecraft dont start

### ISSUE THREAD

**Issue by Davj90** [BevoTechPack/BevoTechPack#818]
Hi,I have a problem with this pack.After making the last update of the pack, minecraft no longer starts.

here the report crash. http://pastebin.com/TDcf999R

**Comment by BevoLJ** [comment]
Skyboy just push out a few updates about 30 mins ago.  Can you try updating to the latest of all the COFH mods and let me know what happens?  http://minecraft.curseforge.com/members/TeamCoFH/projects

I have been unable to recreate this issue on my own, so if you can't update the mods can you tell me what you are doing different so I can try to recreate and troubleshoot the issue?

**Comment by Davj90** [comment]
i have update all the cofh mods,and still crash.I do not do anything different from what I did before....

**Comment by BevoLJ** [comment]
can you pastebin the crash report pls?

**Comment by Davj90** [comment]
sure
https://www.dropbox.com/s/ja05zcbxck8fwo4/crash-2015-02-24_09.46.37-client.txt?dl=0

**Comment by Finchers** [comment]
I am have the same problem with the pack crashing before it even gets to the main screen.

http://pastebin.com/jRa8Hx8J

**Comment by mst3in** [comment]
Can you start any ATL pack?  Please just something else and see what happens.

**Comment by Davj90** [comment]
I tried it with the sky factory, it works.
