### ISSUE TITLE
Big Reactors, can't eject waste (SMP)

### ISSUE THREAD

**Issue by mst3in** [BevoTechPack/BevoTechPack#820]
Related thread:
https://github.com/erogenousbeef/BigReactors/issues/326
A possible fix was suggested:
https://github.com/MrMetric/BigReactors/commit/b38aeb6b914c78ff922b9b5b8ced02bc55f70df7

Symptom:  Toggling "Auto eject waste" on the controller does nothing; setting is stuck on "auto" but waste is never ejected.  Toggle your ports all you want, waste never comes out.  Shift-ejecting to destroy all waste does still work.  (Can still manually eject fuel)

Not all reactor designs have this problem.  Restarting server has no effect on the problem. (Edit, restarting has helped actually, but the symptoms reappear.)

Sample reactor:  6x5 base, two adjacent rods in the middle stacked five high, ender fluid, and active cooled.  Rearranging where ports are has no effect on problem.  (Edit: it doesn't seem to matter what the design is.)

**Comment by BevoLJ** [comment]
looking into it.  Thanks.

**Comment by mst3in** [comment]
Suddenly the same design works again.  :(   IDK what's going on...

Keep this open and I'll try to repro some more.

**Comment by mst3in** [comment]
Have not been able to repro today.  :(   I'm SURE about what I was seeing but I have not been able to repro.  Close until I see it again.

**Comment by mst3in** [comment]
All BG reactors stop working properly after a time.

**Comment by mst3in** [comment]
Restart server.  Do not touch port assignment; no problems.

If you change things, expect problems.

**Comment by mst3in** [comment]
Have not been able to reproduce this issue since; built multiple reactors in the last two weeks.
