### ISSUE TITLE
Recipe Conflict

### ISSUE THREAD

**Issue by KeYMC** [BevoTechPack/BevoTechPack#821]
On BTP-12-Full  Version there is a conflict with :
Coal and Charcoal not making pellets for Progressive Automation and instead making GalacticCraft's Fragmented Carbon.

The recipe is one coal or charcoal in a shapeless form.

Not sure if this was intended i just though of dropping it in here.

**Comment by BevoLJ** [comment]
cool, thanks.  That is not intended.
