### ISSUE TITLE
BTP12Full Server crash: Exception in server tick loop

### ISSUE THREAD

**Issue by filikun** [BevoTechPack/BevoTechPack#822]
I have played BTP since like v10 and havent had any problems with server crashes. But after me and my friend started out a new BTP V12Full-server a problem with server crashes has accurred. It seems that when my friend is taking out things from chests/machines we get a "Exception in server tick loop" (ac to server crash report). I have a few of them now but ill post the latest. We use a lot of Ender IO. 

EDIT: We do run the server with non of the optional modpacks enabled and the only thing I changed in config is the lenght of the OpenBlocks elevator. 

Here a link to the crash report: http://pastebin.com/ez3pJWuN

**Comment by BevoLJ** [comment]
looking into it.  Thanks.

**Comment by mst3in** [comment]
at crazypants.enderio.item.darksteel.ItemDarkSteelAxe.func_77648_a(ItemDarkSteelAxe.java:178)
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)

I dont' see any item of that type.  The world seems to contain an item this pack does not have.

Am I mistaken? Was this world created with this pack?

**Comment by filikun** [comment]
This world was created as BTP V12Full. Havent had the issue for a while now. Really random!

**Comment by filikun** [comment]
Nah got it today again :S 

New crash report here
http://pastebin.com/rZTUj4kv

**Comment by filikun** [comment]
Hmm we do have some lag where we put our machines to... we had a lot more machines in previous BTP V11 but without any lag. Its the same server setup but different versions of BTP. Dont know if there is any connection between the issues here but thats what i noticed.
