### ISSUE TITLE
Bronze paxels (possibly) impossible to create...

### ISSUE THREAD

**Issue by Sabster** [BevoTechPack/BevoTechPack#823]
You need a bronze shovel, pickaxe and axe to create a paxel - but you can't create mekanism bronze...  It immediately converts to Tinker's Alloy Blend...

**Comment by Sabster** [comment]
Also - there are two copper ores being generated.

**Comment by BevoLJ** [comment]
right on.  I'll look into these.  I thought I sorted mek out last summer with minetweaker.  Not sure why that would suddenly derp now.

**Comment by BevoLJ** [comment]
how are you trying to make the bronze?

**Comment by mst3in** [comment]
Wait, just when did paxels start working?  I thought this pack banned them.  (Need to look into that...ty!)

**Comment by Sabster** [comment]
Thanks Bevo!

I ran copper and tin through a sag mill - did the 3/1 dust into bronze dust - and it suddenly changed to the tinker's alloy blend.  I ran those into a normal furnace - created the bronze tools; but when I tried to turn those into the paxel - it wasn't working...

**Comment by Sabster** [comment]
@mst3in - they've always been active (I regularly use steel paxels - best tool around!)  :)

**Comment by mst3in** [comment]
I really was under the impression they were not possible in this pack for balance reasons.  Oops!

**Comment by BevoLJ** [comment]
have you tried making bronze using Mek?

**Comment by Sabster** [comment]
Not yet - just started a new world so didn't have anything other than a sag mill...

**Comment by mst3in** [comment]
Note new here, by far.  

No Sir, no problem making bronze mek; or bronze tinker...

I can tell you a story about how I had a hard time finding iron.  This was about 9 months ago, yes, it was simply luck of the spawn point and I didn't move far enough away...anyway, at the time I found safety in bronze tools.  I recall trying to madly to make a paxel and how it just would never work. (I eventually found my iron needed to progress. and other stuff, then we needed a server reset, and I had to start over but I digress...

Tonight.  Seriously, I've been working for the last hour trying ANY paxel recipe and none work.  None of them have ever worked in this pack as far as I'm concerned and I challenge OP to deliver any paxel recipe that ever did.

I'm not so sure that's an issue; don't try to fix it, this pack doesn't need paxels, IMO.

**Comment by Sabster** [comment]
Just wanted to add:  NEI has a different recipe (meaning the output) than what's actually created.  (NEI says the mekanism tool will be created; and it's not - it's the thermal foundation one...

**Comment by Sabster** [comment]
And yeah mst3in - I was using them since BTP 10-ish (?)  It was definitely last summer (cuz my friend who moved to AZ a year ago had his server up at that point...)

**Comment by mst3in** [comment]
Hold up.   So, you CAN, make a paxel in beovs?  

What is the recipe? in SP?  In SMP?  I've never seen it work.

**Comment by Sabster** [comment]
NEI has the right formula (well the bronze ones don't work with some of the bronze as noted above):  for an iron paxel; it's an axe, pickaxe and shovel over 2 sticks (like a normal tool) - to make the best one (steel); you have to make a steel tools - but instead of sticks, you use iron)

ie. for the steel one you'll need 7 steel ingots - and 8 iron ingots.  For the iron one, you need 7 iron ingots and 8 sticks...

**Comment by mst3in** [comment]
yeah, still no dice.  I'm 99.999% sure this was disabled in this pack.

Bevo??
