### ISSUE TITLE
EnderIO Console Spam - "Silently" catching entity tracking error

### ISSUE THREAD

**Issue by mallrat208** [BevoTechPack/BevoTechPack#824]
I'm not sure if any others are getting this, but as a heads up

My LP world has been getting some absolutely terrible console spam about tracking entities. After some digging, this comes back to EnderIO and it's ability to track Skeletons and Wither Skeletons as different creatures and spawn in EIO Wither Skeletons in their place.

As a work around I've changed the EIO config to B:Misc=true to B:Misc=false

That change has seems to have eliminated all of the console spam I was getting and my world is much more responsive. From the looks of it the EIO devs do know about this problem. https://github.com/CrazyPants/EnderIO/issues/1899

**Comment by erkro1** [comment]
I had thesame problem too, I thought it was because I was pumping tons of lava out of the Nether, what does turning misc off actually do and will it change other things?

**Comment by mallrat208** [comment]
In this case, turning it off stops EnderIO from turning Vanilla Wither
Skeletons into EnderIO Wither Skeletons.

**Comment by erkro1** [comment]
Oh because the option is named Misc I thought it would change more, I will try it out and thanks for the fix! Also I just noticed you're mallrat208, I love your videos on Youtube, keep it up man!

**Comment by mallrat208** [comment]
Thanks :)
