### ISSUE TITLE
Mob spawn rate very low

### ISSUE THREAD

**Issue by notchriss** [BevoTechPack/BevoTechPack#825]
Mobs almost do not spawn in the wild, in the server. Difficulty is set to 3 (hard). It used to work fine till around the time I upgraded to bpt 12, but I can't tell for sure if it started precisely after upgrade, or a few days earlier. Anyhow now it's version 12 and you can sometimes run all night without meeting a single hostile mob. Sometimes you do meet, up to three or four, but not often. I also sometimes get messages like "Grim Skeleton has tried to swim in lava" or "Such and such spider has fell out of the world", so I assume there are some mobs around somewhere, but not many.

 I did try restarting server, didn't help.

I did start a new single player game and mobs seem to spawn normally.

**Comment by mst3in** [comment]
Does the server have a bunch of mobs trapped somewhere?  IOW, is the spawn limit being tested?

**Comment by notchriss** [comment]
There's an Ender IO spawner with spiders constantly working, but thats around 5 spiders always alive. Shouldn't affect whole world spawn rate, should it? Other than that, probably nothing.

**Comment by notchriss** [comment]
Just in a case I restarted server on Peaceful with Monster spawn set to false, kept it for a while in this mode, and then rebooted with Hard difficulty monster spawn true. And hooray, the night is dark and full of mobs again! So it probably was the case of bunch of mobs trapped somewhere. Thanks a lot!
