### ISSUE TITLE
Server crash using "Fluid Interface"

### ISSUE THREAD

**Issue by JIH97** [BevoTechPack/BevoTechPack#826]
I have played BevoTechPack on my own server for a little while now and i started to use me system, and when i put down and open the GUI the server crashed.

Here is a link to the crash report http://pastebin.com/PLcvQLU0

**Comment by mst3in** [comment]
I wish I could help, but I can't.  Unhelpful remark: extra-cells is a badly written mod, at best.  Don't use it.
