### ISSUE TITLE
Client hangs in smp (no crash dump)

### ISSUE THREAD

**Issue by jaz000** [BevoTechPack/BevoTechPack#830]
Playing on server we have been having clients hanging a lot. Spinney cursor and java not responding, sometime - but very rarely it crashes.

This started on BTPv11 and is still happening on BTPv12. This is probably a world issue but I thought I would probably be able to get good advice here about how to debug.

The client will often crash when first connecting to the server (worst case it took someone an hour to get logged in). After that it tends to crash sometimes when you are moving (e.g. flying or walking a lot) it tends not to crash if you are stationary which makes me think it is related to chunk loading. Yesterday a friend reported it had been crashing every 2 mins but stopped when he started taking a pause every 20 blocks he walked. That said you can fly from one side of the map to the other and be ok most of the time ...

The server is unaffected. Two players have been next to each other when one hangs and the other is fine.

We have tried java 7/8/ reinstalling java, different memory settings, different graphics settings even everything on minimum with no difference.

I play another forge mudpack without this issue but like I say it could be that we've started using something in the world that is doing this.

Would appreciate any tips on things to try to stop this happening :-)
thanks

**Comment by jaz000** [comment]
Yay I looks like I can fix my own problem.

This was caused by Journeymap.

2 possible fixes -  1) delete all journeymap data or 2) install latest journeymap 5.01 and it then works again with existing data

not sure what in my journey map data was causing the problem ...!

**Comment by jaz000** [comment]
I speak too soon - I am still facing this problem

I have had an evening of lockups followed by a trouble free evening after removing waypoint data and updating journeymap, only for the poroblem to return.

I have been repeatedly unable to login untill I deleted my player data from the world save directory.

I have been unable to logon to the server for 2 hours - the client creashing each time only for a rollback of the world to solve the problem logging in.

I still have the client lockup every 30 mins or so. About 1 in 10 times the client will crash properly. I could post some crashdumps but eachtime the stack (and fingerpointing) is completely different.

I could still use some help here :(

**Comment by jaz000** [comment]
might be talking to myself here, but will record the resolution for future readers
this was caused by mekanism dynamic tanks
I had 13 6x6x8 tanks with various liquids in - dismantling them fixed the lockups
of course mek has many updates since the version in this pack - maybe one of those woudl resolve as well ...

**Comment by dan4ik-orel** [comment]
Tell me why not start launcher please so I want to play.

**Comment by BevoLJ** [comment]
Mek has updated to Mek 8 which is not compatible with Mek 7 (requires world resets).
