### ISSUE TITLE
FPS drop in new BTP 12 (Opis stats)

### ISSUE THREAD

**Issue by filikun** [BevoTechPack/BevoTechPack#831]
I have an issue on my server when there is a lot of machines and conduits the FPS drops dramaticly. This would not seem to be strange but I didnt have this issue in BTP 11 with almost as advanced setup. Where there is no machines i have like 100-120 FPS but in our base it drops to 19-35FPS. 

EDIT: Server
AMD Athlon II X2 250 Processor 3 GHz
4GB RAM (2GB dedicated to server)
HDD WDC WD20EARS 2TB

Checked with opis and this is what I got: 

World tick 1.443
TileEntities 0.289 ms
Entities 20.971 ms
Total 22.703 ms

Tick time around 7-10 ms
Ping around 100 ms

Forced chunks 1-74 (tried both)
Loaded chunks 795

Im using machines from MineFactory Reloaded, Ender IO and Thermal Expansion. Conduits from Ender io.

Top 10 Tile entities (Type, Mod, Dim, Pos, Update time): 
Meat Packer	MineFactory Reloaded	0	[ -255   64  294 ]	28.525 µs
Power Buffer	Ender IO	0	[ -490   60  506 ]	22.674 µs
Breeder	MineFactory Reloaded	0	[ -261   64  295 ]	17.111 µs
Powered Spawner	Ender IO	0	[ -498   65  497 ]	11.482 µs
Vacuum Chest	Ender IO	0	[ -489   75  521 ]	8.933 µs
Stirling Generator	Ender IO	0	[ -521   59  520 ]	8.795 µs
Alloy Smelter	Ender IO	0	[ -524   60  520 ]	8.777 µs
Power Monitor	Ender IO	0	[ -513   65  519 ]	8.148 µs
Cyclic Assembler (Basic)	Thermal Expansion	0	[ -509   63  518 ]	6.869 µs
Metallurgic Infuser	Mekanism	0	[ -489   67  513 ]	6.342 µs

Top 10 Entities [Type] (Name, Mod, Amount, Timing, Mean Value):
Meat Packer	MineFactory Reloaded	1	28.525 µs	28.525 µs
Power Buffer	Ender IO	1	22.674 µs	22.674 µs
Breeder	MineFactory Reloaded	1	17.111 µs	17.111 µs
Power Monitor	Ender IO	1	8.148 µs	8.148 µs
Metallurgic Infuser	Mekanism	1	6.342 µs	6.342 µs
Fluid Tank	Ender IO	1	6.316 µs	6.316 µs
Powered Spawner	Ender IO	3	16.287 µs	5.429 µs
Alloy Smelter	Ender IO	2	9.307 µs	4.653 µs
Pulverizer (Basic)	Thermal Expansion	1	3.841 µs	3.841 µs
Vacuum Chest	Ender IO	6	22.764 µs	3.794 µs

Top 5 handlers (Mod, Tick, Update time)
Ender IO	ServerTickEvent	18.021 µs
OpenComputers	ServerTickEvent	7.647 µs
Forge Multipart	ServerTickEvent	7.360 µs
WR-CBE Addons	ServerTickEvent	6.390 µs
Galacticraft Core	ServerTickEvent	5.782 µs

Feel free to ask for more info!

**Comment by filikun** [comment]
Installed Optifine seems to fix most of the lag! Mabey include in upcoming BTP?

**Comment by erkro1** [comment]
Yeah would be a good idea, I've never used a modpack without it unless it crashed. With previous MC versions there were a lot of problems with Optifine and that's why it wasn't included often. (although it's also a licensing problem I believe), but since 1.7.10 I can't recall a single one,

**Comment by filikun** [comment]
Yeah I see a problem where the new ender io capacitor bank monitor (That shows input/output) really been messed up by optifine. 

Like this: 
http://imgur.com/ijfIYFu
