### ISSUE TITLE
Minefactory reloaded harvester's WAY too slow?

### ISSUE THREAD

**Issue by Sabster** [BevoTechPack/BevoTechPack#834]
I used to have a 22 x 22 tree farm with 4 harvesters and 1 planter.  It never needed the fertilizer module because it was fairly quick...   But in BTP 12, the harvesters are abysmally slow (I counted 3 minutes before it would cut a tree down).  So slow in fact, the farm will fill up with trees ...  And again, that's with 4 harvesters... :(

Maybe a bug?  Maybe a nerf (that was too hard?) - Any ideas?

**Comment by Sabster** [comment]
Interesting - couldn't figure anything out; so I went into creative mode - destroyed them; and plopped down 4 new harvester's with emerald chips (again, in creative) - they suddenly shot off like they were supposed too.

Maybe something got corrupted when I created the first ones...  Strange.

**Comment by Sabster** [comment]
I think this was either a weird bug - or, the more sludge stored in the harvester, the slower it goes.  Once I got pipes attached and starting sucking it out - the harvester's were moving like a bat out of hell again...

**Comment by belathus** [comment]
Yup, a recent change to MFR. If it is full of sludge, the harvester slows down.
