### ISSUE TITLE
Update to ModTweaker2

### ISSUE THREAD

**Issue by ace13** [BevoTechPack/BevoTechPack#836]
Seeing as jaredlll08 has taken over development of ModTweaker - now ModTweaker2 - and gotten it to work with ThermalExpansion again.

**Comment by BevoLJ** [comment]
Unfortunately that would require resets.  I'm not willing to do that unless I overhaul the pack.  Which I might do.

**Comment by ace13** [comment]
I wasn't aware upgrading ModTweaker to 0.7.0 / ModTweaker 2 would need a reset, it worked fine when I was testing it myself. Does it actually add anything that can be reset, since it's just additions to the MineTweaker scripts?

The reason I asked was because you can't change any TE recipes with the current ModTweaker version (0.6.0), and there's issues with other mods too.

**Comment by Yulife** [comment]
As someone who deals a lot with Modtweaker, a reset as in world reset is not needed at all. Jared just fixed a few bugs and added some new features so you are good to go mate.
