### ISSUE TITLE
Crash in when placing generator

### ISSUE THREAD

**Issue by Nimaz82** [BevoTechPack/BevoTechPack#837]
Hey Bevo, thanks alot for your wonderful pack.

However i have run into a little problem.
i love playing with Mekanism, and the gas (hydrogen) generators.

But, everytime i put down a generator, my world crashes.
I tried messing with it in a superflat creative world. didnt seem to get any issues.
Hope you can help, ive come quite far in my survival world. id be really bummed out , if i have to start over :( 

sincerely
--Ben

**Comment by mst3in** [comment]
Are you putting the gen down next to anything; any side?  (Tubes, cables, etc.)

**Comment by BevoLJ** [comment]
Ben out of curiosity, what was the solution here?  Were you placing it next to anything as @mSt3in commented?

**Comment by sevs44936** [comment]
Hi, I'm having what I believe to be the same problem.

1. Craft a new gas-burning generator.
2. Place it down
3. Pick it up again (using a wrench or simply with a pick)
4. Place it down again
leads to a crash-to-desktop on the client, server keeps running

After a very small bit of digging I found this: aidancbrady/Mekanism#2210, which is the exact bug I'm experiencing.

This fix is included in 7.1.2.186 (see changelog at http://aidancbrady.com/mekanism/download/legacy/), but if you're at it we could update to 7.1.2.187 which is the last version in the 7.x series.
For some reason there is no download for 7.1.2.187, but it still is on the ci at http://ci.indiewikis.com:8080/job/Mekanism/187/ (if you download another release it does in the end come from there, this specific build is just not linked on the download page)
