### ISSUE TITLE
Drawbridge blacklist needed to close dupe bug

### ISSUE THREAD

**Issue by mSt3in** [BevoTechPack/BevoTechPack#839]
Hello, old issue but asking if we could get these blacklist entries put into your default config on next update.
 
Le dupe "bug"
https://github.com/SlimeKnights/TinkersMechworks/issues/70

Le black list entries:
https://github.com/SlimeKnights/TinkersMechworks/issues/32

Thanks

**Comment by mst3in** [comment]
It looks liks this was reported before, the old issue was never reopened after a solution was found.

https://github.com/BevoTechPack/BevoTechPack/issues/647

File TMechwoks.cfg:

```
# Configuration file

drawbridge {
    # Add block names that should not be placed from the drawbridge [default: ]
    S:blacklist <
        minecraft:stone
        ThermalExpansion:Cache
        ThermalExpansion:Strongbox
        MineFactoryReloaded:tile.mfr.machine.1
     >
}
```

**Comment by mst3in** [comment]
LOL, should probably allow minecraft:stone

**Comment by mst3in** [comment]
Update your local config,  admins, for  this is an easy fix.  This has been going on for a while, lol.

**Comment by mSt3in** [comment]
Turns out I was wrong.  Your original instinct to just delete this mod turned out to be the correct one.  There are other ways to dupe with this thing, it's silly.

Thanks for coming back.  Now let's talk about those hungry nodes; because that's what I want to take my frustration out on tonight.  Ever use a cardboard box to put several side by side?

**Comment by b0bst3r** [comment]
This version of BTP will not update, closing issue.
