### ISSUE TITLE
Crashing Client

### ISSUE THREAD

**Issue by jpm42** [BevoTechPack/BevoTechPack#840]
So over the last week I've been playing Bevo Tech Pack.Well today i load the pack up and when i try to play my world it says FML has detected your using the backup of the level.dat file and some other stuff. i tried a couple times of hitting Yes and it crashed.Crash log:http://paste.atlauncher.com/view/c744d78d 

P.s my pc did completely shut down randomly yesterday while i was playing so could that of did something.

**Comment by BevoLJ** [comment]
was this caused by HQM?  It isn't needed in the pack so can just be removed if you need.
