### ISSUE TITLE
Is pack infected?

### ISSUE THREAD

**Issue by kernelpanik92** [BevoTechPack/BevoTechPack#842]
I am running MineOS to run/admin a few minecraft servers for friends and I. I noticed alot of traffic on the modem when no one was connected. After process of elimination, shutting down other servers, it only occurs while BevoTechPack 12 Full is running. It connects to 208.73.210.29 on port 80. If I stop the server, the connection stops as well. When I open the IP in a browser it takes me to fwdservice.com. I google'd the IP and it appears it is a malware site. I do not know what it does but I have blocked it in my firewall. Everything continues to function that I know of. What does this IP do for BevoTechPack?

**Comment by kernelpanik92** [comment]
Ah this may be the IRC services it is connecting to. I looked up esper.net and the IP's are close.

**Comment by kernelpanik92** [comment]
How do I remove the IRC feature from my server? I tried deleting the config for the irc plugin but I don't see the jar file.

**Comment by BevoLJ** [comment]
Delete "EiraIRC"  Or you can just not select it when download the pack.  The pack is not infected.

**Comment by kernelpanik92** [comment]
Ah, maybe you can help me. I do not have the plugin on client side. It is on the server side. How do I remove it? Or disable it on the server side?

**Comment by kernelpanik92** [comment]
I went here: http://blay09.net/?page_id=63 and tried the sirc commands but they don't work. Also the help command in bevotechpack is borked. Some of it is scrambled and certain pages cause the client to crash. I tried changing the config files for EiraIRC but it doesn't seem to matter.

**Comment by kernelpanik92** [comment]
Ok cool. I found the fix. I uninstalled the entire pack and deleted from server. Thanks for the awesome fix!
