### ISSUE TITLE
Server is lagging

### ISSUE THREAD

**Issue by IceFlows** [BevoTechPack/BevoTechPack#847]
Hey, I am launching a tech pack server and it's lagging when like 3 persons is online. I'm running at 4gb ram to my server. And when it lagging I get the message on the console : can't keep up did the system time change or is the server overloaded. Did I need to allcolate more ram or what?

**Comment by erkro1** [comment]
How much RAM do you have allocated?

**Comment by b0bst3r** [comment]
Without any info on server spec it's not possible to comment, this issue is months old and either likely fixed or moved on.
