### ISSUE TITLE
client won't load windows

### ISSUE THREAD

**Issue by djamko** [BevoTechPack/BevoTechPack#848]
hello, have downloaded Bevo's Tech pack.
When I open it, it opens the client and than it gets black screen.
I can't find on forums, what to do and that is why I make a new topic.
here is my log:http://paste.atlauncher.com/view/5bbd3a97
i hope someone can respond and can help me.

Sincerly djamko

**Comment by erkro1** [comment]
Try to increase your permgen space, you can do that at ATLauncher options.

**Comment by b0bst3r** [comment]
Paste is no longer visible and really old issue so closing.
