### ISSUE TITLE
Server not starting, bad interpreter

### ISSUE THREAD

**Issue by Hajto** [BevoTechPack/BevoTechPack#854]
Hi,

i have just freshly "created" Bevo's Tech Pack Server 12 Full using the AT Launcher and uploaded on my Debian 8 Server. When i try to launch it with LaunchServer.sh i get following error:
![image](https://cloud.githubusercontent.com/assets/8336429/8513624/8c8e0e22-2373-11e5-8684-f22c7c0abb99.png)

Java Version:
![image](https://cloud.githubusercontent.com/assets/8336429/8513637/a16fbb42-2373-11e5-95fe-804e159a1ab9.png)

**Comment by jgshaban** [comment]
I think I see something in the error you supplied.

Looks like an accidental Carriage Return Character in your script. Unix and Linux don't use the Carriage Return Character for a new line, just Line Feed. That causes reading/execution issues of scripts sometimes, and it looks like ^M at the end of a line like in your error you posted.

Odd question, but did you edit LaunchServer.sh from a Windows machine before uploading it to your Debian box? A text editor in Windows may have added a Carriage Return Character to every line, as Windows uses both Carriage Return and Line feed to denote a new line.

If you did open or edit it from a windows machine, you can try using the command dos2unix on the Debian box to strip out all the Carriage Return characters out of ~/at/LaunchServer.sh. Either that, or maybe try uploading a fresh LaunchServer.sh file, and editing it from the Debian machine itself using vim or vi.

Clear as mud?

Hope this helps.

**Comment by b0bst3r** [comment]
Old issue, cleaning up github ready for new release, let me know if this is still a problem.
