### ISSUE TITLE
My World Want A Backup but it doesnt want to accept the backup

### ISSUE THREAD

**Issue by sylvester123456** [BevoTechPack/BevoTechPack#857]
can you please help me somehow i have accendently turnd of my pc en when is started it again up it said Forge Modloader detected that the backup level.dat is being used this may happen due to a bugg or corruption end id download a backup of my world but it still doesnt work plss help plsss

**Comment by b0bst3r** [comment]
Old issue, cleaning up github ready for new release, let me know if this is still a problem.
