### ISSUE TITLE
A fatal error has occoured, this connection is terminated

### ISSUE THREAD

**Issue by MinerManc3X** [BevoTechPack/BevoTechPack#859]
I'm trying to make a BevosTechPack server but when I login it just crashed and "A fatal error has occoured, this connection is terminated" comes up! I'v checked the client console but nothing!
Please help!!

**Comment by oliver276** [comment]
If you've made the server yourself, chances are that you've not activated all of the mods.  Inside the server directory /mods/ you'll find some mods end in '.disabled'.  These are the optional mods.  Make sure that these mods match the ones that the clients have, and you should be good to go.  I spent about 4 hours working on this :D 
It's annoying, but simple

**Comment by b0bst3r** [comment]
What oliver said.

Old issue, cleaning up github ready for new release, let me know if this is still a problem.
