### ISSUE TITLE
gas genrater

### ISSUE THREAD

**Issue by matmoos** [BevoTechPack/BevoTechPack#861]
wen it try to place the bio gas generator we all clients shut down instantly  and it is placed once we can reconnect but have to wait four the server to notis we have left no era showing in sever window we are playing local game

**Comment by b0bst3r** [comment]
Yeah old issue with old mod, was fixed but couldn't update Mek as it would have posibly destroyed your world.

Old issue, cleaning up github ready for new release, let me know if this is still a problem.
