### ISSUE TITLE
Severe Lag with Tesseract

### ISSUE THREAD

**Issue by Fir3will** [BevoTechPack/BevoTechPack#863]
Hello, I have recently created a tesseract in my world and placed it down next to an Ender IO conduit. The whole conduit system is connected to my AE system. When I first placed down the Tesseract, it was fine. It wasn't lagging what so ever. But as soon as I selected a frequency, it started lagging a lot. I mean I couldn't move my player. Multiple second delays. If you need another instance of where this lag happened. Here's a post on the 1.7.10 Modpack issue tracker which I think was the same situation.
https://github.com/EnderMediaDev/The-1.7.10-Pack/issues/250
I believe it might be important to mention that I have removed Pneumaticraft and I added the mod Ex Nihilo and Ex Astris. Thank you for reading this. I hope to hear from you soon!

**Comment by b0bst3r** [comment]
Can you post screenshots next time please.

Old issue, cleaning up github ready for new release, let me know if this is still a problem.
