### ISSUE TITLE
OpenComputers: Issue With Memory Detection

### ISSUE THREAD

**Issue by jgshaban** [BevoTechPack/BevoTechPack#865]
When creating a computer from the OpenComputers modpack in Bevo's Tech Pack, RAM will not be identified in the computer, making it unusable. In the provided snapshot, memory is installed in both slots when this error happens. However, this issue occurs if RAM is in the first, second, or both slots.

![2015-08-05_00 29 00](https://cloud.githubusercontent.com/assets/13654797/9079889/f3c4f68c-3b0b-11e5-8cf8-daf0e2e9328d.png)

If it is of any use, OpenComputers' GitHub page shows this issue was identified, and later rectified in OpenComputers 1.5.3:
https://github.com/MightyPirates/OpenComputers/issues/954

Let me know if you need any more information.

Thanks!

**Comment by b0bst3r** [comment]
Yeah old mod bug, pack is stuck on version it is due to big changes that would break your worlds in certain mod updates which is why Bevo never updated.

Old issue, cleaning up github ready for new release, let me know if this is still a problem.
