### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by sackboy338** [BevoTechPack/BevoTechPack#868]
When I go to play the pack, it loads for a bit, but then the console puts out this error: Exception in thread "Client thread" [16:20:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.OutOfMemoryError: PermGen space

then it freezes permanently, I have given it plenty of memory, and it still doesn't work.

Plz help!

**Comment by b0bst3r** [comment]
In the atlauncher - settings - java/minecraft is a box for permgen size, if you haven't figured it out it was this that needed making bigger.

Old issue, cleaning up github ready for new release, let me know if this is still a problem.

**Comment by sackboy338** [comment]
Was I supposed to get This Email?
