### ISSUE TITLE
Error with  BevoTech modpack

### ISSUE THREAD

**Issue by Alezanderr** [BevoTechPack/BevoTechPack#875]
I have a problem with a mod in the BevoTech modpack.It's called JourneyMap Fairplay.

Error downloading JourneyMap5.0.0_FairPlay_MC1.7.10.jar from http://minecraft.curseforge.com/mc-mods/32274-journeymap-32274/files/2219482/download. Expected hash of 67d93dd4c415acba45330171a5e264ba but got 0 instead. Copied to FailedDownloads Folder. Cancelling install!

Cannot get MD5 of **USERSDIR**\Downloads\JourneyMap5.0.0_FairPlay_MC1.7.10.jar as it doesn't exist.

Please help me with the problem!!
Thanks you!!

**Comment by furrious** [comment]
I am having the same problem. I have yet to find any other places to download this version of the mod. All I can find is 5.1.0. I'd assume an update to the newest version would fix it?

**Comment by ChronomegaIV** [comment]
It looks like an update to the FULL-XML or MINI-XML reflecting the location of the 5.1.0 version would fix the issue. The original location of the file is on curse forge, and it looks like they removed the 5.0.0 version in trade for 5.1.0.

`<mod name="JourneyMap" version="5.0.0" url="http://minecraft.curseforge.com/mc-mods/32274-journeymap-32274/files/2219482/download" file="JourneyMap5.0.0_FairPlay_MC1.7.10.jar" md5="67d93dd4c415acba45330171a5e264ba" download="direct" type="mods" website="http://www.minecraftforum.net/topic/772071-" donation="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=D5KK9FRAQG6DE" server="no" authors="Mark Woodman AKA TechBrew" description="Real-time map in-game or in a web browser as you explore." />`

A fix should be (Mind you I have no access to make this change):

`<mod name="JourneyMap" version="`**5.1.0**`" url="`**http://<span></span>minecraft.curseforge.com/projects/journeymap-32274/files/2245166/download**`" file="`**journeymap-1.7.10-5.1.0-fairplay.jar**`" md5="`**8daac8de9888b948d763610abf498f5a**`" download="direct" type="mods" website="http://www.minecraftforum.net/topic/772071-" donation="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=D5KK9FRAQG6DE" server="no" authors="Mark Woodman AKA TechBrew" description="Real-time map in-game or in a web browser as you explore." />`

**Comment by PROJETO158** [comment]
hello to me with problems in my modpack. No or you can download it from error or it is muted I would like q u could help me

**Comment by krum85** [comment]
Have the same problem.. is there no way around this?

**Comment by cthulchu** [comment]
The issue's fixed. Here's how: https://bitbucket.org/TeamJM/journeymap/issues/2/journey-map-absence

You're welcome.

**Comment by furrious** [comment]
Wow, that's great to hear! Much thanks.

**Comment by b0bst3r** [comment]
Yeah issue fixed pack should be downloadable again
