### ISSUE TITLE
Plastic Tank placement causes server to be unopenable

### ISSUE THREAD

**Issue by Mcdanil** [BevoTechPack/BevoTechPack#878]
So, I've got a BevoTechPack server on the Nodecraft website. 

I was setting up an auto meat factory, and I placed a Minefactory Reloaded Plastic Tank underneath a Buildcraft fluid pipe, and the game immediately crashed. Since then, we have been unable to connect back to the server, and are met with these error messages.

[15:30:54] [Netty IO #2/ERROR]  [FML]: NetworkDispatcher exception
•io.netty.handler.codec.EncoderException: java.lang.NullPointerException
•at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:129) ~[MessageToByteEncoder.class:?]
•at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
•at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
•at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
•at cpw.mods.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:423) ~[NetworkDispatcher.class:?]
•at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
•at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
•at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
•at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
•at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
•at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
•at net.minecraft.network.NetworkManager$1.run(NetworkManager.java:174) [ek.class:?]
•at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [SingleThreadEventExecutor.class:?]
•at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [NioEventLoop.class:?]
•at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
•at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
•Caused by: java.lang.NullPointerException
•at net.minecraft.nbt.NBTTagCompound.func_150298_a(SourceFile:309) ~[dh.class:?]
•at net.minecraft.nbt.NBTTagCompound.func_74734_a(SourceFile:25) ~[dh.class:?]
•at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:149) ~[du.class:?]
•at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:139) ~[du.class:?]
•at net.minecraft.nbt.CompressedStreamTools.func_74798_a(CompressedStreamTools.java:82) ~[du.class:?]
•at net.minecraft.network.PacketBuffer.func_150786_a(SourceFile:78) ~[et.class:?]
•at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148840_b(SourceFile:50) ~[gf.class:?]
•at net.minecraft.util.MessageSerializer.encode(SourceFile:38) ~[fa.class:?]
•at net.minecraft.util.MessageSerializer.encode(SourceFile:14) ~[fa.class:?]
•at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:111) ~[MessageToByteEncoder.class:?]
•... 15 more
•[15:30:54] [Server thread/INFO]: SerDuncan lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

Anything you guys can let me know to figure this out?

**Comment by b0bst3r** [comment]
Can you pastebin the full crashlog and link it here?

**Comment by b0bst3r** [comment]
No reply to issue within 24 days.
