### ISSUE TITLE
Doors!

### ISSUE THREAD

**Issue by jreaper** [BevoTechPack/BevoTechPack#879]
Doors don't work on server.

**Comment by b0bst3r** [comment]
Need a lot more info than that please.  What do you mean don't work, as in don't open?

Which doors?
You changed any mods?

**Comment by jreaper** [comment]
Yes sorry, When placed on a server any door that was used in game would
refuse to open and some would simply just let anything walk straight
through them. In the end the solution was to delete Malissa's door mod I
think it was. Then all the doors started working as normal.

**Comment by b0bst3r** [comment]
Fixed in mod but this version of BTP will not update.
