### ISSUE TITLE
Games Crash On loading Single Player World

### ISSUE THREAD

**Issue by hogue321** [BevoTechPack/BevoTechPack#882]
I was playing when my building lost power. Also, Windows updated upon restart of computer, which may have something to do with it?

Crash Log: http://paste.atlauncher.com/view/36729351
Do I have a corrupted file somewhere?

**Comment by b0bst3r** [comment]
Sooo many errors in that log not sure which one(s) are causing it not to load so here's what I suggest.

Go into your \Instances\BevosTechPack\saves folder and make a backup of your world (called Le World).

Delete all instances of forcedchunks.dat from within the Le World folder and sub-folders - example = \Instances\BevosTechPack\saves\Le World\DIM-1\forcedchunks.dat

HQM data is corrupt however there were no HQM quests so unless you added some of your own either delete or replace config\hqm\quests.hqm with an original one.

If that doesn't work, make a new instance of BTP and copy over your world to it and see if it loads up then.

**Comment by b0bst3r** [comment]
No reply in 24 days closing issue
