### ISSUE TITLE
Error Installing an instance Bevos

### ISSUE THREAD

**Issue by SmexyTacos** [BevoTechPack/BevoTechPack#884]
I am getting an error and it cancels my installation right at the very beginning of when it installs. I have the lkatest version of java. The last error it gives me is, [07/2/2016 19:54:41 PM] Failed to download file launchwrapper-1.11.jar from all ATLauncherservers. Copied to FailedDownloads Folder. Cancelling install!
 The rest of it is here http://paste.atlauncher.com/view/b968a00c.
Please Help!

**Comment by b0bst3r** [comment]
I've tested the launchwrapper.jar  and new instance installs and both appear fine. Did you get this fixed?

**Comment by SmexyTacos** [comment]
No, I have narrowed it down to a network issue. I cant download anything.
Even when i start up the launcher. I can't connect to any server Amsterdam
Pheonix nothing. What do i do?

**Comment by b0bst3r** [comment]
Are you behind a proxy?

**Comment by SmexyTacos** [comment]
No I am not.

**Comment by bcdaedalus** [comment]
am also having the same issue unable to download the pack tryed a few different instances and 0 joy

**Comment by TheChilledGaming** [comment]
Do you live in Australia

**Comment by SmexyTacos** [comment]
No Western United States
