### ISSUE TITLE
READ THIS FIRST - RE: Bevo Tech Pack Reborn

### ISSUE THREAD

**Issue by b0bst3r** [BevoTechPack/BevoTechPack#885]
Java 8 is required 

BTPR is not backwards compatible with your old BTP worlds I put this on the launcher, on the update notes and in the work notes on github, if you try and update and it destroys your world don't blame me.

When creating an issue please state BTPR otherwise I will presume it's one of the older versions of BTP.

BTPR is available on the atlauncher but not as an update to BTP12, you will have to pick the version from the launcher.

http://bevolj.com/forums/index.php?threads/bevos-tech-pack-reborn-faq.865/ <- Reborn FAQ

Reborn Blog 
March 11th - http://bevolj.com/?p=5641

**Comment by andyid26** [comment]
Hello.

I have installed the BTPR pack on my server but on the client side of At Launcher, the BTPR is not in the list of update packs available.
I only see: 
BTP 12
BTP 12 Lite
BTP 11
BTP 11 Lite

This is the first time i install BTP on the client side of At Launcher,

**Comment by andyid26** [comment]
Disregard my above statement.
I closed my At Launcher and reopened it and it updated the list.

Thanks.
