### ISSUE TITLE
Update Computronics

### ISSUE THREAD

**Issue by Vexatos** [BevoTechPack/BevoTechPack#886]
`Preliminary_Modlist.txt` contains highly outdated versions of AsieLib and Computronics which will likely crash with the version of OpenComputers on the list. Please update to the latest versions of those two mods.

**Comment by b0bst3r** [comment]
Highly outdated? It's 1 version behind release :p

**Comment by b0bst3r** [comment]
I ninja'd in asielib 0.4.5 and computronics 1.6.0
