### ISSUE TITLE
bevotechpack crashing after installing the instance

### ISSUE THREAD

**Issue by coolgaza16** [BevoTechPack/BevoTechPack#888]
i want to install bevo tech pack but when i install it without changing any setting the instance wont launch and crashes befor ever getting to the main menu. crash log attatched. i have not changed any settings just clicked install and play
[crash-2016-02-10_13.12.46-client.txt](https://github.com/BevoTechPack/BevoTechPack/files/124768/crash-2016-02-10_13.12.46-client.txt)

**Comment by b0bst3r** [comment]
delete minecraft\config\hqm\quests.hqm and try again

**Comment by b0bst3r** [comment]
This should be fixed now, reinstall the instance of BTP12
