### ISSUE TITLE
Crashing at Mojang splash screen

### ISSUE THREAD

**Issue by Mightyracoon** [BevoTechPack/BevoTechPack#889]
Hi guys,

I've reinstalled Java multiple times so I don't think it's that, but the ATLauncher loads fine all the way up to the Mojang screen then crashes back to launcher. My crash log is here:

http://pastebin.com/2D4UAJL1

Any help would be appreciated. Thanks in advance.

**Comment by b0bst3r** [comment]
See my response in https://github.com/BevoTechPack/BevoTechPack/issues/888

**Comment by Mightyracoon** [comment]
Hi b0bst3r, thanks for the reply.

I tried your suggestion and it still crashed on the Mojang screen (back to the launcher). I'm no expert, but it looks like it's still trying to call in HQM?

Here's a pastebin from the latest crash:
http://pastebin.com/Ph7W8VrN

Thanks so far for your help

**Comment by b0bst3r** [comment]
HardcoreQuesting{The Journey (4.2.1)} [Hardcore Questing Mode] (HQM-The Journey (4.2.1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored

This is still the issue, HQM is erroring, you could try removing the mod since there's no quests in this version of BTP.

**Comment by Mightyracoon** [comment]
I did remove the mod from the downloads directory, it's weird that it's still calling for it?

**Comment by Mightyracoon** [comment]
I'm an idiot, I just deleted it from Windows Explorer rather than disabling it through ATLauncher. Once I'd done that, it booted straight in! TYVM!

Only issue now is that I can't connect to the server that I was on before, as I get a mod rejection error - would this be something that the server admin will need to disable too then?

**Comment by b0bst3r** [comment]
Need to get to the bottom of why this is occuring, can you think back and let me know what changed in between you playing on the server and it crashing.

Did you update java?
Did you by chance update to BTP Reborn then go back?
Any other thoughts?

**Comment by Mightyracoon** [comment]
Hi b0bst3r,

I haven't managed to play on the server with this machine yet, it's always just crashed. But I'm able to play it on 2 other machines in the house with the exact same configuration - it's strange. I've tried reinstalling Java, to no avail

**Comment by Mightyracoon** [comment]
I also haven't updated to the BTPR beta as the server is still running v12 FULL

**Comment by b0bst3r** [comment]
Do the other machines run java 8?

**Comment by Mightyracoon** [comment]
Just checked and they're both running Java 7, update 79.

I'll trying installing that and let you know how it goes

**Comment by Mightyracoon** [comment]
So I installed the same version of Java on a brand new installation of Windows and the same thing happened.

New crash log:
http://pastebin.com/5KiBDajd

Basically, it's any new Bevo installs - the original 2 that I did around a week ago are working fine, but I've now tried it on 3 different computers (having rolled back the Java version to 7u79 on 2 of them) and the same thing is happening...what's changed in the last week?

**Comment by b0bst3r** [comment]
In btp 11 and btp 12 nothing has changed, I brought out BTP-R which has it's own section.  I'll recheck.

**Comment by b0bst3r** [comment]
ok I see the problem.

**Comment by Mightyracoon** [comment]
Yeah, I have to wait until our server admin updates the server before I try BTP-R - excited to try it when I can though.

You see the problem? So it's not just me being stupid then? Or maybe it is...

**Comment by b0bst3r** [comment]
Any chance you can zip the config folder and all subs on one that is working and host it somewhere so I can fix this?

**Comment by Mightyracoon** [comment]
Absolutely mate, I'll get right on it

**Comment by Mightyracoon** [comment]
Here's the zip of the entire 'Configs' folder in ATLauncher - is this the one you wanted?
https://drive.google.com/file/d/0B6LK4MX58mPfSXJtVlQ5bHU4Q1E/view?usp=sharing

Or is it the Config folder under 'Instances->BevosTechPack'? If so, that's here:
drive.google.com/file/d/0B6LK4MX58mPfS2x6MVJCeExiYlU/view?usp=sharing

**Comment by b0bst3r** [comment]
Thanks should be fixed now, you'll need to close atlauncher and reload it then install btp12 from a new instance.

**Comment by Mightyracoon** [comment]
Yup, that's sorted it!

Thanks for your help mate
