### ISSUE TITLE
Galacticraft Error

### ISSUE THREAD

**Issue by sharkck** [BevoTechPack/BevoTechPack#892]
I just took the rocket to the moon and it appears, according to the crash log, the moon-sky isn't set to load?

Now my client crashes every time I try to join the server.

Here is the log file:
https://www.dropbox.com/s/61w2ghso2o0jra0/Galacticraft%20Error.txt?dl=0

BTW, HI BEVO!!!!!  
Thank you so much for the new updates post BTP12!

**Comment by b0bst3r** [comment]
Fixed in Galaxy Space 1.0.7 which will be included in the next update.

**Comment by sharkck** [comment]
Thanks!  Is there an ETA on when that may be released?

**Comment by b0bst3r** [comment]
Today
