### ISSUE TITLE
Bug with thaumcraft shards

### ISSUE THREAD

**Issue by ShadowKn1ght18** [BevoTechPack/BevoTechPack#893]
When i mine the thaumcraft infused stone with a silk touch pick and afterwards try to fortune it i just get yhe block and i even trued a normal iron pick and it still gave me the block.. I use manasteel tools if that helps any..

**Comment by b0bst3r** [comment]
What tool did you use to fortune the block?

**Comment by ShadowKn1ght18** [comment]
I used the fortune manasteel pick

**Comment by b0bst3r** [comment]
Yeah I can see the issue, silk touching any infused shard block renders it unbreakable by picking afterwards. Scratching my head at what could cause this one.
