### ISSUE TITLE
Iron heat coil crafting

### ISSUE THREAD

**Issue by Widowmaker2141** [BevoTechPack/BevoTechPack#896]
The iron heat coil has the same crafting as the Iron trapdoor I don't know how to fix that, but I just gave myself some and got through out the Iron that was needed.

**Comment by b0bst3r** [comment]
The pack has a mod called nomorerecipeconflicts, if you use a vanilla crafting table (also works with other crafting tables) an arrow appears allowing to cycle through any conflicting recipes.  Unfotunately this doesn't appear to work on the tinkers crafting table.

![f3purt6](https://cloud.githubusercontent.com/assets/2760085/13504492/a1bbd4a2-e16c-11e5-891a-2a8ceeaddfa6.png)

**Comment by Widowmaker2141** [comment]
Oh my bad never used that mod
