### ISSUE TITLE
Forge loader detected that the backup level.dat is being used?

### ISSUE THREAD

**Issue by timewhiz** [BevoTechPack/BevoTechPack#897]
This is an issue today, gives me the option of selecting yes or no. I select yes and it returns me to the same screen. clicking on yes multiple times has the instance crash. Days prior i did not have this issue.
[crash-2016-03-04_16.34.47-server.txt](https://github.com/BevoTechPack/BevoTechPack/files/159494/crash-2016-03-04_16.34.47-server.txt)

**Comment by b0bst3r** [comment]
This is usually caused by anti-virus programs locking the file so MC can't use it (or has been the cause in the past).  Try disabling your AV and see if it loads.
