### ISSUE TITLE
OpenGL error & NullPointerException error

### ISSUE THREAD

**Issue by chincychuchu** [BevoTechPack/BevoTechPack#898]
I'm getting the errors whenever I try to run the pack. I have no idea what to do to fix it. Please help.

 	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.

Current Language: ~~ERROR~~ NullPointerException: null

Those are the two errors i am getting.

**Comment by b0bst3r** [comment]
Need the full crashlog, pastebin it and link it here.

**Comment by chincychuchu** [comment]
I have installed some new drivers and have fixed the issue. Thank you anyways. 


On March 5, 2016, at 5:20 AM, b0bst3r <notifications@github.com> wrote:

Need the full crashlog, pastebin it and link it here.
