### ISSUE TITLE
SMP - Player Moved too Quickly

### ISSUE THREAD

**Issue by RickyRicksta** [BevoTechPack/BevoTechPack#899]
Hi there, great modpack!

I am using BTPR - BetaF Hotfix as both server and client

Recently I've come across this issue and I have no idea how to fix it, nor can I find anyone complaining about the same issue but I've only encountered this when messing with Galacticraft.

The problem is when floating back down to the overworld the server spams the "Player Moved too quickly!" warning and freezes the player in place. Relogging fixes this issue but when building a space station if you happen to float off the platform the issue starts again but relogging does not return you to the platform and if you try to move back the server seems to think you're speedhacking or something and freezes you in place. 

I've enabled allow-flight=true in the server.properties but I'm still getting the same issue, any ideas? 
Thankyou!

**Comment by b0bst3r** [comment]
Are you running Cauldron on the server or any plugins or extra mods like ftbutilities?

**Comment by RickyRicksta** [comment]
The only extra mods the servers has enabled are the optionally disabled ones and the already enabled ones the server came with, no extra mods other than those.

**Comment by b0bst3r** [comment]
Hmm I've done so much testing going and coming from planets in SMP and I've never come across this yet.  All researching has brought up is old information that cauldron used to cause this.  I'll keep looking.

**Comment by LukassGrey** [comment]
Hi, 

I also have problem with Player moved too quickly server spamm. However it`s not related with Galacticraft only. It seems that problem occurs  in case of any fast vertical movement. 

I`m running clear BTPR BetaH - on server and on client side. No additional mods/plugins.

**Comment by b0bst3r** [comment]
LukassGrey is that in SSP or SMP and if on SMP does the server run any plugins?

**Comment by LukassGrey** [comment]
SMP without plugins

**Comment by b0bst3r** [comment]
Great news, I've at long last managed to replicate this and have a fix coming, waiting on mod updates, if I don't get them by the end of today I will push this update on it's own.

**Comment by LukassGrey** [comment]
Great :) Many thanks :)

**Comment by b0bst3r** [comment]
Fixed in BetaI-Hotfix
