### ISSUE TITLE
Steel Recipe in Mekanism's Metallurgic Infuser

### ISSUE THREAD

**Issue by Mightyracoon** [BevoTechPack/BevoTechPack#900]
Hi b0bst3r,

Just installed a fresh server of BetaF - everything seems great, except for a missing recipe that we've noticed in Mekanism (in the Metallurgic Infuser).

Basically, it will let you turn Iron into Enriched Iron, but it won't then let you turn Enriched Iron into Steel Dust - this worked absolutely fine in the last BTP that we ran.

Is this an issue that you're aware of?

Cheers

**Comment by b0bst3r** [comment]
Yes I changed the recipe see here - http://bevolj.com/forums/index.php?threads/bevos-tech-pack-reborn-faq.865/

**Comment by Mightyracoon** [comment]
That's great, thanks for the link - should've read through that tbh.

Just in case it's suggested, is there a relatively easy way for me to change it to how it was before? Or will that have other knock-on effects with the modpack? I doubt I'll do it anyway, but better to know :)

**Comment by b0bst3r** [comment]
Delete minecraft\scripts\mek.zs and do a /mt reload in game (you will have to open to LAN and enable cheats if you're SSP).  Just be aware any update will put it back.  it wont break anything just make getting steel very easy which will make everything else easy and rather pointless.

**Comment by jmbarnez** [comment]
The only way to get diamond dust is from crushing it or macerating it, but the crusher or the enrichment chambers require steel to make.

**Comment by b0bst3r** [comment]
There are several ways to make steel, at least 4
