### ISSUE TITLE
Buildcraft 

### ISSUE THREAD

**Issue by Z0R4K** [BevoTechPack/BevoTechPack#901]
BuildCraft this not creating the quarry simply does not appear to create the craft table

**Comment by b0bst3r** [comment]
Buildcraft quarry is disabled, use Mekanism Digital Miner, Extra Utilities Ender Quarry, Magneticraft Miner or or or I'm sure there's another one.

**Comment by Z0R4K** [comment]
how do I enable mod quarry BuildCraft

**Comment by b0bst3r** [comment]
https://www.reddit.com/r/ATLauncher/comments/495agt/readd_bc_quarry_in_bevo_tech_reborn/
