### ISSUE TITLE
Cant craft IC2 basic machine casings

### ISSUE THREAD

**Issue by FatedOne** [BevoTechPack/BevoTechPack#903]
You get the furnace from nuclear craft.

**Comment by b0bst3r** [comment]
The pack has a mod called nomorerecipeconflicts, if you use a vanilla crafting table (also works with other crafting tables) an arrow appears allowing to cycle through any conflicting recipes.  Unfotunately this doesn't appear to work on the tinkers crafting table.

![f3purt6](https://cloud.githubusercontent.com/assets/2760085/13504492/a1bbd4a2-e16c-11e5-891a-2a8ceeaddfa6.png)

**Comment by Sil3ntStorm** [comment]
This one is worse than #904, as you can't even get AE to autocraft this, and nobody in their right mind would keep crafting something as basic as this manually.

**Comment by b0bst3r** [comment]
Hmm fair point.

**Comment by b0bst3r** [comment]
Lol no idea you had done these, I just made the exact same change

**Comment by b0bst3r** [comment]
betaH
