### ISSUE TITLE
Blackout Curtains uncraftable

### ISSUE THREAD

**Issue by Sil3ntStorm** [BevoTechPack/BevoTechPack#904]
The Blackout curtains from XU are not craftable due to a recipe collision with Malisis' Doors Curtains.
Whenever you place 6 wool in a crafting table in a door shape you end up with Malisis' curtains (all of which are useless junk - the only purpose possibly being decorating) instead of the highly useful and required XU Blackout Curtains (which are required for e.g. Dark Glass crafting).
Using BTPR BetaG.

**Comment by b0bst3r** [comment]
Same answer as any other conflicts - you have the tools within the pack to sort them:

The pack has a mod called nomorerecipeconflicts, if you use a vanilla crafting table an arrow appears allowing to cycle through any conflicting recipes.  Unfortunately this doesn't appear to work on the tinkers crafting table.

![f3purt6](https://cloud.githubusercontent.com/assets/2760085/13504492/a1bbd4a2-e16c-11e5-891a-2a8ceeaddfa6.png)

**Comment by Sil3ntStorm** [comment]
Who crafts stuff manually (especially in a tech pack)?
Also being able to specify the output with that mod is all nice and dandy but nobody uses the broken vanilla crafting tables that spit stuff into the world once you close the UI anyway, so that doesn't do much good unfortunately. Only exception would be for Unstable Ingot crafting (at least as long as one cares about diamonds).

Anyway, while testing to remove / change the recipe I figured that luckily XU Black Curtains are the only ones that craft with mixed colors of Wool.
Thanks to the awesomeness that is AE2 you can actually craft them by specifying a substituting pattern with mixed colors of dye and AE2 will still produce the black curtains if only one type of wool is left.
Still that means either having to create a recipe for it, or having to use a vanilla table.

**Comment by b0bst3r** [comment]
Recipe changed for black curtains

**Comment by b0bst3r** [comment]
betaH
