### ISSUE TITLE
Machine Frame

### ISSUE THREAD

**Issue by Afrim502** [BevoTechPack/BevoTechPack#910]
Hey Bevo!
when i craft the basic Machine frames from Thermal Expansion they require Steel in the recipe. is there any way i can edit this to make it use Iron in its Crafting instead?

**Comment by lilmoefow** [comment]
Its always required steel in this pack.

**Comment by Afrim502** [comment]
I know this pack always worked like that but i used to play other packs where the recipe for machine frames used iron instead, im wondering if there is something in the configs maybe that i can edit to make the recipe on this pack use iron

**Comment by Sil3ntStorm** [comment]
It's by design to make stuff more interesting.
According to some similar issues on here you can find ways to create steel by following the quests in the quest book.

**Comment by b0bst3r** [comment]
If you undo the changes I made and there's not many the pack will not play right and quests will not make sense and planet exploration would be kinda pointless.
