### ISSUE TITLE
Important Notice Text showing wrong pack version (From BetaG to BetaH)

### ISSUE THREAD

**Issue by DeploySpaceShip** [BevoTechPack/BevoTechPack#913]
I recently updated from BetaG to BetaH and I havent seen this in a thread yet.

The bug happened when I updated from BetaG to BetaH. In the important notice text, it should say:
"Welcome [player name] to Bevo's Tech Pack Reborn BetaH" but it says BetaG, restarting and reinstalling gives me the same notice.

I attached a picture of that notice (I blurred out my username cause of personal reasons)
![bug](https://cloud.githubusercontent.com/assets/17782803/13701908/3f537552-e78b-11e5-8856-7c1f0b763f70.png)

**Comment by b0bst3r** [comment]
Fixed, I removed the version number since I'll most likely always forget to change that.
