### ISSUE TITLE
1k storage cant complete

### ISSUE THREAD

**Issue by Widowmaker2141** [BevoTechPack/BevoTechPack#914]
so on the me quest it tells you to make a 1k storage it will not take I have gone in and tried all the filters from the quest editor still cant get it to take the only way I could it to complete is to delete the 1k requirement.

**Comment by b0bst3r** [comment]
What crafter did you use to make it?

**Comment by b0bst3r** [comment]
Do me a favour and take the 1k chip and craft it to get the 2 parts then recraft those parts together, does it complete the quest?

**Comment by b0bst3r** [comment]
betaG
