### ISSUE TITLE
Magneticraft Crafter Item Creation

### ISSUE THREAD

**Issue by dysd25** [BevoTechPack/BevoTechPack#915]
The Magneticraft Crafter randomly generates large amounts of items without the material for them. Was able to generate 70+ stacks of iron when after to converting existing stacks (~12) to ingots.

**Comment by b0bst3r** [comment]
Yeah I know about this dupe and so do the Magneticraft devs, unfortunately it wont be fixed since the devs have moved on to 1.8.  Can only hope people wont use/abuse it.

https://github.com/cout970/Magneticraft-API-and-Issues/issues/80

**Comment by b0bst3r** [comment]
I've decided to remove this from the next version and altered the HQM quest in such a way it should not cause an issue.
