### ISSUE TITLE
cant finish Mekanism x4

### ISSUE THREAD

**Issue by Mysterious-thingy** [BevoTechPack/BevoTechPack#916]
it says me i didnt make the 4 advanced solar generators which i definately have. i then also spawned new ones in from creative and i spawned in materials to make them a second time from scratch but that also didnt work.

**Comment by b0bst3r** [comment]
You need all 4 in your inventory at the same time.

**Comment by Mysterious-thingy** [comment]
I have all 4 ones in my inventory, I tried putting them all in the hotbar and it still does not work

**Comment by b0bst3r** [comment]
Yeah seems the quantity will have to be changed to 1.

**Comment by Mysterious-thingy** [comment]
Yeah its because they don't stack right?

**Comment by b0bst3r** [comment]
Yes it would appear that is correct.

**Comment by Mysterious-thingy** [comment]
well i did some research. i spawned in 4 solar panels stacked through the NEI cheat mode. and when stacked it still does not work sadly

**Comment by b0bst3r** [comment]
You need to change the detection to NBT but not sure if that "cheat" will work on HQM.

**Comment by Mysterious-thingy** [comment]
so okay is there anything else I can try? otherwise I will just wait till the update.

**Comment by Watschman** [comment]
if you are an admin on the server or on SSP, type /hqm edit in your chat (might have to enable cheats via Lan World) then you will have an admin book where you can autocomplete quests with a Shift click on them. After you auto completed your bugged quest just throw it away in a trash can or something like that. That way you don't have to wait for an update.

**Comment by b0bst3r** [comment]
betaG
