### ISSUE TITLE
Tinkers smeltery; different ores - different Usuages

### ISSUE THREAD

**Issue by Watschman** [BevoTechPack/BevoTechPack#919]
The problem that multiple ores spawn is already known, but I discovered that they are treated differently in the Tinkers smeltery.
The Thorium ore from Magneticraft can be smelt in the smeltery but the Thorium ore from Nuclearcraft can not be smelt in the smeltery.
This can be fixed be ether removing the ability to smelt Magneticraft Thorium ore or to add Nuclearcraft Thorium ore as a smeltable Object:

`mods.tconstruct.Smeltery.removeMelting(<Magneticraft:thorium_ore>);`
-->remove smelt ability

`mods.tconstruct.Smeltery.addMelting(<NuclearCraft:blockOre:5>, <liquid:thorium> * 288, 600, <NuclearCraft:blockOre:5>);`
-->add smelt ability

the same is for some other ores like
Uranium ( Smeltable from IC2 but not from Nuclearcraft and Magneticraft), 
Zinc (Smeltable form Flaxbeard's Steam Power but not from Magneticraft)
etc.
I would suggest to add them instead of removing them unless you want to make the pack harder.
If you need help by the coding I can write all of it and paste it into here so you just have to add it into an appropriate zenscript file.

**Comment by b0bst3r** [comment]
betaG
