### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by diadistis** [BevoTechPack/BevoTechPack#920]
There's currently no way to craft `Sheet Metal Block` from `Immersive Engineering` because the recipe conflicts with `Empty Cell` from `NuclearCraft`.

**Comment by b0bst3r** [comment]
For now use a normal crafting atable and you can cycle through the conflicting recipes.

**Comment by b0bst3r** [comment]
Fixed in update, 5th Iron plate added to Sheet metal block recipe to make 5 sheet metal blocks to original 4.
