### ISSUE TITLE
No dark iron

### ISSUE THREAD

**Issue by Baughn** [BevoTechPack/BevoTechPack#921]
There's no dark iron spawning in my world at all, near as I can tell. I'm uncertain why.

This renders nontrivial use of Factorization impossible.

**Comment by Baughn** [comment]
...never mind! I *finally* found it, after I decided to hover inside the Void. It spawns. It just doesn't spawn very much.

**Comment by b0bst3r** [comment]
Yes it is very very rare the different bedrock is a clue to you being nearby, once you get to flat bedrock you know it's close.  They spawn in clumps like this and are about 3 per 100x100 blocks http://imgur.com/a/lRmDa
