### ISSUE TITLE
Request:  FTB Utils and Libs libraries

### ISSUE THREAD

**Issue by devanchya** [BevoTechPack/BevoTechPack#922]
Revolution 2 bundles Forge Essentials and FTB Utils and Libs as part of their packs.
I would request this be added to BTP Reborn as its chunk claim system is very easy to use and very secure.

Thanks from Dig To Build

**Comment by b0bst3r** [comment]
Sorry not going to happen I dislike the cheaty commands it puts in (like /home /back etc) so feel free to add it to yours.
