### ISSUE TITLE
Portal to the 'Deep Dark' isn't working

### ISSUE THREAD

**Issue by NOBvadder** [BevoTechPack/BevoTechPack#927]
After setting up and right-clicking the Portal to the 'Deep Dark' from Extra Utilities nothing happens. Normally you should be teleported to the Deep Dark.

**Comment by Watschman** [comment]
yeah I belief it's an issue with Galacticraft storing the players data differently then Minecraft. I think adding the mod Player API should fix that issue.

**Comment by NOBvadder** [comment]
I'll test it, thanks

**Comment by b0bst3r** [comment]
PlayerAPI-1.7.10-1.4.jar will be added to next update
