### ISSUE TITLE
beta h missing 15 blocks

### ISSUE THREAD

**Issue by epileptictardis** [BevoTechPack/BevoTechPack#928]
have been running a server on beta g (and loving it keep up the great work) but when i tried to upgrade to beta h it says that there 15 blocks missing and if i continue i will remove them from the game alot of them have to do with clean/dirty/clump lilithium is this intended and can i update or and have them removed or is this a bug?

**Comment by b0bst3r** [comment]
Just click yes and carry on, it's normal.
