### ISSUE TITLE
Cannot use MFR Raw Rubber with IC2 Extractor

### ISSUE THREAD

**Issue by llomellamomario** [BevoTechPack/BevoTechPack#929]
Seeing that for all intents and purposes MFR Rubber Trees are equivalent to IC2 ones, strikes me as odd that the Raw Rubber doesn't have an extractor recipe to Rubber. Found it by getting an early extractor on my BTPR world, wanted to not chop/smelt as often. It would be more of a enhancement thing.

**Comment by b0bst3r** [comment]
Yeah that would make it all too easy since you don't have to wait for MFR rubber. You'd be absolutely swimming in rubber, would consider 1 raw for 1 rubber in extractor though if that's any good?

**Comment by llomellamomario** [comment]
Yeah. Would be good to just have it dedicated for rubber extraction, and give it a bit more use.

**Comment by b0bst3r** [comment]
Decided not to sorry :)
