### ISSUE TITLE
Logistics Pipes/Buildcraft crash after update to BetaI

### ISSUE THREAD

**Issue by aesguitar** [BevoTechPack/BevoTechPack#930]
My logistics pipes system has broken due to the update. Buildcraft golden pipes are not connecting to the logistics pipes and causing a CTD when broken next to a logistics pipe. Breaking the logistics pipes does not cause a crash. Breaking the BC pipes when they are not adjacent to a logistics pipes does not crash. Placing a bc pipe next to a logistics pipe does not cause a crash. Only when breaking a bc pipe when it is next to a logistics pipe causes a crash. 
![untitled-1](https://cloud.githubusercontent.com/assets/6676966/13865029/3803c4e0-ec7d-11e5-8706-2ab6d7008e60.jpg)
Here is the crash report and a screenshot.
[crash-2016-03-17_20.09.36-server.txt](https://github.com/BevoTechPack/BevoTechPack/files/178884/crash-2016-03-17_20.09.36-server.txt)

**Comment by b0bst3r** [comment]
Reverted to logisticspipes-0.9.3.93.jar (prior pack version) and crash still occurs.
Put back Logistics Pipes 0.9.3.99 and reverted Buildcraft to 7.1.14 and pipes connect and no crash occurs.

**Comment by b0bst3r** [comment]
As soon as BC 7.1.6 comes I'll push it in an update rather than revert backwards.

**Comment by b0bst3r** [comment]
BetaI-Hotfix
