### ISSUE TITLE
Waila GUI crash

### ISSUE THREAD

**Issue by Thistlebalm** [BevoTechPack/BevoTechPack#931]
BTP BetaI
crash log:
http://pastebin.com/05wCJye1

Steps to produce:
Opened waila gui with numpad 0
Click waila
Clicked configure aspect
Clicked default
Clicked back
Clicked back and crashed on this click.

**Comment by b0bst3r** [comment]
Reported

https://github.com/blay09/CraftingTweaks/issues/76

**Comment by b0bst3r** [comment]
Reverted back to .73 in BetaI-Hotfix
