### ISSUE TITLE
IC2 Overclocker upgrade is uncraftable

### ISSUE THREAD

**Issue by llomellamomario** [BevoTechPack/BevoTechPack#932]
As stated, currently the recipe is borked a bit. As you can see in the screenshots, when you craft 10k coolant cells, they come without any metadata (they are completely new after all), but the recipe requires 1k coolant cells with 1 as metadata value, thus not allowing crafting.

Recipe with everything crafted new: http://puu.sh/nL5lZ/de62920323.png
NEI Recipe: http://puu.sh/nL5y7/1c397f9a76.png

**Comment by b0bst3r** [comment]
I see 3 recipes in NEI, 1 with no meta, 1 with meta 1 made from coolant and 1 recipe to make the no meta cell into a meta:1 cell by crafting the cell into itself.

**Comment by llomellamomario** [comment]
I see that now, missed the 1k no meta to 1 meta shapeless. Still weird, does not make any sense that kind of 2 step recipe. Case closed I guess.
