### ISSUE TITLE
Nuclearcraft Crusher won't accept sandstone

### ISSUE THREAD

**Issue by Thistlebalm** [BevoTechPack/BevoTechPack#933]
BTP version BetaI

The Nuclearcraft Crusher won't turn sandstone(id 24) into four sand like it shows in NEI.
However there is a sandstone(id 24:32767) I found in the chisel gui that it does work with.
This sandstone(id 24:32767) won't work in a Mekanism Crusher.

**Comment by b0bst3r** [comment]
The only way I can see you can get that 24:32767 sandstone is by selecting it in chisel, therefore you need a chisel to get it, so you can just put the 24:32767 back into chisel and select sandstone 24.

Unless you know of another way to get this 24:32767 sandstone?

**Comment by Thistlebalm** [comment]
That's the only way I saw also. But the issue is the NC crusher won't accept the normal sandstone, I had to make the 24:32767 sandstone to get it to work. It's not a big deal to me, I just figured I'd report it.

**Comment by b0bst3r** [comment]
Unfortunately Nuclearcraft doesn't have machine mine/modtweaker support so I can't change this, sorry.
