### ISSUE TITLE
id conflicts updateing beta H to beta I on server

### ISSUE THREAD

**Issue by Stuferus** [BevoTechPack/BevoTechPack#934]
hi,

i tryed to day to update my server from H to I. server crashed after 5 sec after anyone logs in with completely diffrent inventorys and all the placed blocks are not the same.. total id chaos.

crashlog doesnt say anything useful.. just a random block thats involved in the crash everytime other one depending which player loged in and crashed it.

example. i have a wood house with chisle 2 wood, it was slimeblocks after the update..

did someone change ids in configs or should i not use the same world as long as this is beta?

**Comment by b0bst3r** [comment]
That's very odd as I play on a server that went from H to I with no issues like this and upgrades I do test.  Also there was no update to chisel.  Can you post your logs anyway so I can look please.

**Comment by Stuferus** [comment]
[crash-2016-03-18_14.58.26-server.txt](https://github.com/BevoTechPack/BevoTechPack/files/180459/crash-2016-03-18_14.58.26-server.txt)

**Comment by Stuferus** [comment]
i did the update manual.. aka delete the old mods and configs and upload the new ones.. i download the server files using atlauncher.

the log is the one the server generated for my house after i loged in.

**Comment by Stuferus** [comment]
we removed some mods we think we dont want/need, changed to I hotfix, installed 3 other mods we think would be nice to have, changed the server config for more gold generation (as it was quite low) and generated a new map.. since than (not updated from i hotfix) all is running well.. i think our server waits a few versions till we update as every time starting over isnt something we want to do.

thank you for the help sofar :)
