### ISSUE TITLE
Optional Mods

### ISSUE THREAD

**Issue by lilmoefow** [BevoTechPack/BevoTechPack#937]
Thaumcraft is in the pack. These are 2 good optional client side mods to "enhance" Thaumcraft.

Thaumcraft Node Tracker
http://mods.curse.com/mc-mods/minecraft/227328-thaumcraft-node-tracker

Thaumcraft NEI Plugin
http://minecraft.curseforge.com/projects/thaumcraft-nei-plugin
(this one also adds good support if added server side aswell as client side)

**Comment by b0bst3r** [comment]
Added TC NEI Plugin as default
Added TC Node tracker as optional

Released in BetaJ (soon)
