### ISSUE TITLE
Cannot get back to space station

### ISSUE THREAD

**Issue by addrever** [BevoTechPack/BevoTechPack#939]
Error and disconnect when accessing space station on a server I host.

This is the error:
http://pastebin.com/pETA2YCj

It seemed to have happened after the update from H to I.  I believe that Galacticraft was updated in I.

Any help is appreciated.

**Comment by Stuferus** [comment]
did you see if the blocks are the same in space? if thay not the same its maybe related to my id conflict problem.

**Comment by b0bst3r** [comment]
I can't do anything about this whilst Galacticraft's site is down.

**Comment by Stuferus** [comment]
Answer via mail:

ok, i see lets wait for it than :)

Am 22.03.2016 um 19:46 schrieb b0bst3r:

**Comment by b0bst3r** [comment]
Will be fixed in BetaJ
