### ISSUE TITLE
Rendering Crash

### ISSUE THREAD

**Issue by BevoLJ** [BevoTechPack/BevoTechPack#940]
cc: @MrTJP , @cout970

> Description: Rendering Block Entity
> 
> java.lang.NullPointerException: Rendering Block Entity
> 	at com.cout970.magneticraft.api.util.VecInt.getTileEntity(VecInt.java:173)
> 	at com.cout970.magneticraft.api.electricity.prefab.InterPoleWire.getStart(InterPoleWire.java:44)
> 	at com.cout970.magneticraft.client.tilerender.TileRenderPoleCableWire.func_147500_a(TileRenderPoleCableWire.java:113)
> 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
> 	at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
> 	at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
> 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
> 	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
> 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
> 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
> 	at net.minecraft.client.main.Main.main(SourceFile:148)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Stacktrace:
> 	at com.cout970.magneticraft.api.util.VecInt.getTileEntity(VecInt.java:173)
> 	at com.cout970.magneticraft.api.electricity.prefab.InterPoleWire.getStart(InterPoleWire.java:44)
> 	at com.cout970.magneticraft.client.tilerender.TileRenderPoleCableWire.func_147500_a(TileRenderPoleCableWire.java:113)
> 
> -- Block Entity Details --
> Details:
> 	Name: com.cout970.magneticraft.tileentity.pole.TileElectricPoleCableWire_Mg // com.cout970.magneticraft.tileentity.pole.TileElectricPoleCableWire
> 	Block type: ID #2133 (ElectricPoleCableConnection // com.cout970.magneticraft.block.BlockElectricPoleCableWire)
> 	Block data value: 9 / 0x9 / 0b1001
> 	Block location: World: (-33,67,215), Chunk: (at 15,4,7 in -3,13; contains blocks -48,0,208 to -33,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Actual block type: ID #2133 (ElectricPoleCableConnection // com.cout970.magneticraft.block.BlockElectricPoleCableWire)
> 	Actual block data value: 9 / 0x9 / 0b1001
> Stacktrace:
> 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
> 	at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
> 	at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
> 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
> 	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
> 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

Full log: https://gist.github.com/BevoLJ/a7e5b15f6b84e66a83ac

**Comment by b0bst3r** [comment]
What were you doing when this happened and is it repeatable?

**Comment by BevoLJ** [comment]
I was just logging into the game.  When I close the game, the next time I login, it crashes when logging in.  Once it has crashed, the following time I will login just fine.  Then the next time I login it will crash, reboot, log in fine.  Rinse and repeat. =P

**Comment by BevoLJ** [comment]
Ok, so I think it just happens if I logout, but don't close the game.  Like when I logout, backup the save folder and then log back in it crashes every time.  Which requires me to close the game completely and restart it to log back in.

**Comment by b0bst3r** [comment]
Unfortunately Magneticraft are working on 1.8/1.9 and not fixing/altering anything in 1.7, since it's closed source we can't get fixes.

**Comment by cout970** [comment]
Magneticraft it's open source https://bitbucket.org/cout970/magneticraft  if anyone wants to fix it, we are working on the 1.9 version but I have no enough time to work on it so the development is slow.

**Comment by b0bst3r** [comment]
@BevoLJ  I asked Dyonovan if he'd fix the issues with magneticraft but he needs your world download as we can't replicate this.  Can you get in touch with him or me please.
