### ISSUE TITLE
Blocks to Lava

### ISSUE THREAD

**Issue by BevoLJ** [BevoTechPack/BevoTechPack#941]
Odd issue I have been having upon reloading the game.  My Megneticraft boiler and heat cable turn to lava.

![untitled-1](https://cloud.githubusercontent.com/assets/5301213/13908699/3d8a552c-eed6-11e5-9857-7af960d5cc43.png)

**Comment by BevoLJ** [comment]
cc @cout970

**Comment by b0bst3r** [comment]
Yeah this happens if they get too hot 1200c for too long, use cooling blocks to lower the temp a bit.

**Comment by BevoLJ** [comment]
Rock on.  Thanks!
