### ISSUE TITLE
Player moved too quickly

### ISSUE THREAD

**Issue by Mightyracoon** [BevoTechPack/BevoTechPack#946]
Hi b0bst3r,

We appear to be getting an issue when using the jetpacks on our server (we're running BTP-Reborn-BetaF) where the server console is spammed with 'Player moved too quickly'. The player that's flying also locks up while this happens, as if they're being reset back to the point where they started 'moving too quickly'.

Is this a known issue? Or perhaps something you've fixed with a recent update?

Thanks in advance,
Racoon

**Comment by lilmoefow** [comment]
That issue was fixed in the BetaI-HOTFIX. I suggest updating your server to the latest version

**Comment by b0bst3r** [comment]
Yes update please it's fixed.

**Comment by Mightyracoon** [comment]
That's great, thanks. I'll update to BetaJ I think.

I'm assuming with the update I just need to backup the world, then overwrite the current .jar with the new one? Or are there any other steps with your pack?

**Comment by b0bst3r** [comment]
Depends how you make the server because there's 2 ways, the download server link from atlauncher's website and a way through the launcher itself.  If you mean the download from the website then yes delete config/mods/scripts on your server and unpack the zip.  Don't leave those 3 folders and unpack over the top as you'll end up with duplicate mods.

**Comment by Mightyracoon** [comment]
Cheers mate, I've done all that. However, I'm now getting an error saying some bits are missing:

Forge Mod Loader detected missing blocks/items

The missing blocks/items are from GalaxySpace, aobd and malisisdoors

I try running /fml confirm but it just hangs.

Any advice?

Thanks

**Comment by b0bst3r** [comment]
Yeah that's normal since GS updated from your old version to new, just do as it wants in console /fml confirm

**Comment by Mightyracoon** [comment]
Great, cheers. Can't get it to accept the /fml confirm, annoyingly. Think it's an McMyAdmin issue though. Does it normally take a while after confirming?

**Comment by Mightyracoon** [comment]
Don't worry, got it sorted - it was taking it's time to backup the world I think.

Thanks for your help!
