### ISSUE TITLE
Morpheus/Sleep Voting

### ISSUE THREAD

**Issue by Mightyracoon** [BevoTechPack/BevoTechPack#949]
Hi there,

Just got BetaJ up and running, after upgrading from BetaF. Is there a reason that Morpheus was removed? Went to go to sleep and usually only 50% people on the server need to be asleep, but we aren't getting that (or the message that pops up in chat)...I'm assuming that these were attached to Morpheus?

Did you remove it for a reason? Or am I okay to just drop it back in the mods folder?

Thanks in advance

**Comment by b0bst3r** [comment]
Morpheus has always been optional so yeah just drop it back in the mods folder.
