### ISSUE TITLE
EnderStorage and ChunkLoader bug on load save

### ISSUE THREAD

**Issue by Gungsu** [BevoTechPack/BevoTechPack#950]
Ender chest and ender tank don´t load on map load and crash save

ChunkLoader too

I put one ender tank and chunkloader in Nether
In overworld i put one EnderChest and use one Ender Pouch

When i save and quit, and re-load my save, he crash.

For reopen my save i open by MCedit and delete this blocks (EnderChest, ender tank, chunkloader)
and delete folders (chickenchunks,enderstorage).

**Comment by Landrash** [comment]
_This is kinda the main reason I personally don't use enderchests and tanks. I've seen this so many times when admining servers._
I don't think there's much that can be done on the side of this modpack without a crash log.

**Comment by Watschman** [comment]
as Landrash stated, without a crashlog we can do little to help to run down your problem.

**Comment by b0bst3r** [comment]
Never came back so not keeping open.
