### ISSUE TITLE
Magneticraft + Steve's Factory Manager

### ISSUE THREAD

**Issue by Dazzik316** [BevoTechPack/BevoTechPack#951]
The Steve's Factory Manager filter does not see/detect Magneticraft's chunk/rubble/pebble variations of ores with the "Magneticraft" designation.  Aobd chunk/rubble/pebble ores do show up in the filter.
chunk rubble pebble.  I've been running Beta H and Beta J.

**Comment by b0bst3r** [comment]
And neither mod is being developed anymore, not sure there's anything I can do about this

**Comment by Watschman** [comment]
I have to look into the source code to run down the issue, but you can work around that problem just have the chunk/rubble/pebble in your inventory and type into the filter " .inv " without the quotationmarks but with the dot. This way the Inventorymanager will show your inventory and you can set the chunk/rubble/pebble from Magneticraft into the filter.

Hopefully this was somehow understandable.

**Comment by Dazzik316** [comment]
Your workaround works and actually makes setting all my filters much easier!

**Comment by Watschman** [comment]
No problem and unfortunately I could not find the Problem yet in the code. It has probably something todo with hardcoding in ether Magneticraft or SFM, but the .inv should work always whatever item it is.
