### ISSUE TITLE
plasma shotgun crash

### ISSUE THREAD

**Issue by lilh** [BevoTechPack/BevoTechPack#952]
Right-clicking with an empty plasma shotgun (matter overdrive) causes the game to run out of memory and crash.

**Comment by b0bst3r** [comment]
Is it spamming something in the logs?

**Comment by lilh** [comment]
doesn't look like it

**Comment by b0bst3r** [comment]
SO how do you know it ran out of memory? do you get an error on screen?

**Comment by lilh** [comment]
yah

**Comment by b0bst3r** [comment]
pic pls

**Comment by Watschman** [comment]
when does the crash occur exactly? I tried to reproduce the crash but nothing like an ooM crash happened not even the logs showed anything or do have I missed something trying it? https://www.youtube.com/watch?v=aWgPWBNeHx8
