### ISSUE TITLE
some ore rubbles are not picked up

### ISSUE THREAD

**Issue by Phuttel** [BevoTechPack/BevoTechPack#953]
iron and copper rubble (from Magneticraft) are not picked up by pipes from thermal dynamics and buildcraft and any other method of item transporting except the magneticraft inserters and conveyor belts.
I am currently playing SSP if that helps.

Thanks if you can fix it.

**Comment by b0bst3r** [comment]
You have filters in the ducts, if so what are they set to?

**Comment by Phuttel** [comment]
I am using reinforced servo with an empty blacklist. I tested it with the inserters from magneticraft and works just perfectly fine. 

sorry for answering now, had checked my mails in a while. Ask if you want further Information to my setup etc.

**Comment by Xandulis** [comment]
"any other method of item transporting except"...

I just want to point out that refined relocation works just fine with filters

**Comment by b0bst3r** [comment]
Yeah I use relocators too, best filtering system since sliced bread.

**Comment by Phuttel** [comment]
> I just want to point out that refined relocation works just fine with filters

Thanks for the reply! I'm looking into it

**Comment by Phuttel** [comment]
@Xandulis  Works perfectly, thanks for tip!

**Comment by b0bst3r** [comment]
Works perfectly well with thermal dynamics itemducts.
![mag](https://cloud.githubusercontent.com/assets/2760085/14615752/1368b452-059f-11e6-84a5-8e1b5cbd672f.png)
