### ISSUE TITLE
Duplicate Bug

### ISSUE THREAD

**Issue by Izuzusama** [BevoTechPack/BevoTechPack#954]
Auto workbench is able to duplicate item
Place down auto workbench and place item
![2016-03-30_20 27 36](https://cloud.githubusercontent.com/assets/9895213/14142065/f7accf8e-f6b5-11e5-8ab7-adabf8611e73.png)
Click the down arrow
![2016-03-30_20 27 39](https://cloud.githubusercontent.com/assets/9895213/14142076/01a9e8aa-f6b6-11e5-9f38-f52ad6931ca9.png)

**Comment by Landrash** [comment]
Is it possible to do without the mod that adds the down arrow?
If not it might be a good plan to check other mod inventories in combination with the same down arrow function.

**Comment by Izuzusama** [comment]
I'm not sure whats the mod that adds the down button

**Comment by Izuzusama** [comment]
Ops click wrong and closed issue

**Comment by Landrash** [comment]
FYI,your picture has the same amount in both pictures.

Picture 1 9*64 in table and 64+9 in jnv.
Picture 2. 64 in table, 8*64 in hotbar and 64+9 in inv.

**Comment by Izuzusama** [comment]
When you click on a slot in auto workbench it does not subtract from your inventory. The item floats on your mouse.
http://i.imgur.com/o4AruaS.gifv
