### ISSUE TITLE
Maybe EnderIO crash

### ISSUE THREAD

**Issue by hAmpzter** [BevoTechPack/BevoTechPack#955]
I got a server crash a couple of days ago and did some more checking. Seems like it was either EnderIO or a core-crash with the enderchest-api in minecraft.
But yeah, EnderIO seems to be built for rv2 of AE2 and not rv3 that is included in this pack.

I have attached the full crash log.
[crash-2016-03-27_14.48.31-server.txt](https://github.com/BevoTechPack/BevoTechPack/files/197277/crash-2016-03-27_14.48.31-server.txt)

**Comment by b0bst3r** [comment]
Which dimension were you going to/from when this happened?

**Comment by hAmpzter** [comment]
I was not around on the server myself when it happened and I have tried asking the ones online at the time. No one of the ppl online seems to remember though.. :(

**Comment by lilmoefow** [comment]
Chicken-Bones/EnderStorage#65

**Comment by hAmpzter** [comment]
We are no longer running this server and I don't think that the issue is not relevant anymore. Closing!
