### ISSUE TITLE
Crash while loading Singleplayer

### ISSUE THREAD

**Issue by Resistancebear** [BevoTechPack/BevoTechPack#956]
I didn't change anything on my Java or Windows version but all of a sudden i can't start my single player world. I could actually start a new run but the saved world just crashes my Mc when starting .
Did just update the version to the new released one but didn't change anything also i did a backup from the game and installed the version i was playing on again but also didn't help.
Got my Log here :
http://pastebin.com/84mQ3ryd

**Comment by b0bst3r** [comment]
Try loading your world without chickenchunks (disable the mod through the launcher).  If it loads then re-enable the mod.

**Comment by Resistancebear** [comment]
Yeah works when chickenchunks is disabled but didn't work when reenabling it.
Guess i gotta go with a different chunk loader now . Thanks a lot though :)
