### ISSUE TITLE
Crafting the Booster Engine for the advanced jetpack

### ISSUE THREAD

**Issue by robdan54** [BevoTechPack/BevoTechPack#957]
For some reason I am unable to craft the booster engines and have no idea why and have looked around and a number of people have had a similar issue

**Comment by b0bst3r** [comment]
Clarify please are you talking about - Tier 1 Rocket Engine or Tier 1 Booster.   There's no such thing as a booster engine.

**Comment by b0bst3r** [comment]
You need to be more specific on parts as I crafted it with no problems, where does it go wrong?

**Comment by Watschman** [comment]
b0bst3r there is a booster engine, but it's name is messed up similar to the Nuclearcraft uranium ore, which is using the unlocalized name. But I did not seem to find any problems crafting the itemEngineBoost.name  in the latest version of BTP Reborn (BetaL)

**Comment by b0bst3r** [comment]
Yeah there seems to be a lot of localization issues, not sure why.
