### ISSUE TITLE
Applied Energistics charger glitch

### ISSUE THREAD

**Issue by Mysterious-thingy** [BevoTechPack/BevoTechPack#958]
hello its me again,

i found that if you place an uncharged certus quartz in the charger to power it, it doesnt show the certus quartz sprite in the charger, so the only way to know if it is charged is through the waila
![bevo 1](https://cloud.githubusercontent.com/assets/17799629/14221288/044da784-f866-11e5-94d7-e1cea177576c.png)
![bevo 2](https://cloud.githubusercontent.com/assets/17799629/14221289/044e328a-f866-11e5-91a2-b7515e1645c4.png)

**Comment by b0bst3r** [comment]
I take it you use Fast graphics settings?  I can replicate it on fast but it shows up on fancy.

**Comment by Mysterious-thingy** [comment]
ah yes thank you, now it works!

**Comment by b0bst3r** [comment]
It works in fast graphics but only from a very specific angle which is weird
