### ISSUE TITLE
Request: ProjectRed Fabrication

### ISSUE THREAD

**Issue by Sukasa** [BevoTechPack/BevoTechPack#961]
I see that the rest of PR is included in BTP Reborn, but not Fabrication (and thus the IC chips it enables use of).  Does this mod have a chance of being added in future versions?

**Comment by b0bst3r** [comment]
What do these IC chips do I can find no info anywhere?

**Comment by Sukasa** [comment]
ProjectRed Fabrication enables the creation of "IC" chips which are multiple regular chips contained in a single block.  Basically, super-miniaturization.

**Comment by Landrash** [comment]
@Sukasa You could replicate this with Opencomputers using the Micro controller. Most likely not what you want but it's and option.

**Comment by b0bst3r** [comment]
Every bloody update I keep forgetting to add this ......... sorry maybe by the time I reach betaZ :/

**Comment by b0bst3r** [comment]
Finally added to BetaV
