### ISSUE TITLE
kicked while using project red jetpack 7640:3056

### ISSUE THREAD

**Issue by StrommKral** [BevoTechPack/BevoTechPack#962]
booted from server, kicked from game, while flying with this jetpack

**Comment by Landrash** [comment]
Using latest version of the modpack?

**Comment by StrommKral** [comment]
it's 3 weeks since i started the server, haven't seen any updates that are critical to my current path of development on the server. don't really care about the jet pack, just thought, cheap and convenient with the tinker's wings/legs safe fall. The only other problem I have had is a crafting Quest not updating, (solar panels for the evaporator). I just edited past it, got dirt as a reward too wtf...is up with that? Anyway, thanks..

**Comment by b0bst3r** [comment]
What version of the pack are you playing as flight was fixed in one of them.

**Comment by StrommKral** [comment]
beta H,  i guess its older than i thought....really like the pack and your vids

**Comment by b0bst3r** [comment]
Thanks and flight was fixed in BetaI-Hotfix so any version older than that will fix flight
