### ISSUE TITLE
nuclearcraft (large) fissionreactors cause lag

### ISSUE THREAD

**Issue by LameGirlyCurly** [BevoTechPack/BevoTechPack#963]
In a nutshell - the bigger they get the more they lag. I've tried with different combinations of how they're set up or fueled, but the end-result is kinda terrible. 1000-5000us roughly. This example reactor is producing 82k rf/t with 0 heat, sized 17x17x17 and connected via tesseract to somewhere.

http://postimg.org/image/kdbdg8bft/

If you need additional information, I'm happy to give.
Tested with kcauldron 195 and 201 for now, same thing.

**Comment by spacebuilder2020** [comment]
Has this been solved yet?

**Comment by b0bst3r** [comment]
This should be addressed/fixed in BetaU-NC but heed the warnings I left all over the place.
