### ISSUE TITLE
Screen Glitches when looking down

### ISSUE THREAD

**Issue by HavocxPro** [BevoTechPack/BevoTechPack#964]
When looking down in the nether or overworld i get strange screen glitches, some white things start appearing and its really annoying, also is optifine is supported?
EDIT = Reborn version not old one

**Comment by HavocxPro** [comment]
i didnt have the same problem with any game also my PC is decent so im sure 100% its from minecraft or a bug

**Comment by b0bst3r** [comment]
optifine is not supported with Forge mod and it causes allsorts of glitches.  You might not get with other packs because most other packs are using older mod versions.

**Comment by HavocxPro** [comment]
nah i dont have optifine, i didnt install it

**Comment by b0bst3r** [comment]
Can you get me a screenshot of what you see?

**Comment by HavocxPro** [comment]
it happens really fast but im gonna give it a try

**Comment by HavocxPro** [comment]
Strange, i have never touched the settings but it seems because i didnt lock the frames so its happening when i have more than 120+ FPS, Closed
