### ISSUE TITLE
Immersive Engineering Wires Disappearing

### ISSUE THREAD

**Issue by Kackra** [BevoTechPack/BevoTechPack#965]
We updated our server to BetaO and now we have had problems with MV and LV wires disappear when adding a new line. Not sure what might be causing this.

**Comment by b0bst3r** [comment]
When do they disappear, when the chunks unloaded, when the server restarts or something else and when you say MV/LV wires are you talking about IE wires?

**Comment by Kackra** [comment]
It is the IE wires and it happend when I would use a transformer on a pole going from MV to LV for Powered Lantern or when I was extending my power lines farther out. I have not had the problem with the HV wires and we just started having this issue in the last few days

**Comment by Kackra** [comment]
Also when you connect the new wire it doesn't just disappear a good 10-20 disappear along a line starting or ending with the connection we just made

**Comment by Kackra** [comment]
Also when you connect the new wire it doesn't just disappear at the one connection but a good 10-20 disappear along a line starting or ending with the connection we just made

**Comment by b0bst3r** [comment]
Can't replicate this is your server vanilla Forge, or thermos/cauldron?

**Comment by Kackra** [comment]
We just used the server instance from ATLauncher with all optional mods selected. It is a large set up of wires as we like the look of IE. The MV and LV lines that disappear are quite long at least 200+ connected in a loop with capacitors and transformers every so often. We use the LV for the Powered Lanterns only and MV for all machine connections

**Comment by Kackra** [comment]
We did remove a few MV connectors on machines and switched to Ender IO conduits and I also removed all the transformers that were on posts and replaced them with capacitors and I have not had the problem happen.

**Comment by Landrash** [comment]
@Kackra I would probably report it to the makers of [Immersive Engineering](https://github.com/BluSunrize/ImmersiveEngineering).
I have quite big setups of IE wires myself and haven't seen this happen between updates of the modpack.
I'm assuming there havent been any errors in your log files or so that could shed some light on the cause?

**Comment by Kackra** [comment]
Not sure what might have changed but after the last update the problem has gone away. Thank for all the help.
