### ISSUE TITLE
Lighting issue Immersive Engineering

### ISSUE THREAD

**Issue by Morgloz** [BevoTechPack/BevoTechPack#967]
I am using the BetaO version and noticed some weird lighting when using immersive engineering connectors.

In this one the left connector has direct sight of the sky and the right one not.
![2016-04-21_20 25 51](https://cloud.githubusercontent.com/assets/18406501/14720140/39c024ce-0800-11e6-8bce-fbcbaf3b468a.png)

However if I block the sky...
![2016-04-21_20 26 00](https://cloud.githubusercontent.com/assets/18406501/14720141/39c22c7e-0800-11e6-8ea0-686ecf1c1d5e.png)

**Comment by b0bst3r** [comment]
The whole mod has issues with Fastcraft atm, If you're using it you can remove it, if you're connecting to a server which has it then other than ask the server owner to remove it there's not a lot I can do.  Blu (IE Dev) knows about the issue.

**Comment by b0bst3r** [comment]
Shading issue - http://postimg.org/image/tuq65defd/
Without shading issue - http://postimg.org/image/vb1onihc9/

**Comment by Morgloz** [comment]
Ok I will try without fastcraft, thanks
