### ISSUE TITLE
Request:  Add Remain in Motion

### ISSUE THREAD

**Issue by spacebuilder2020** [BevoTechPack/BevoTechPack#968]
We are finding in our testing that the frames from Project Red don't seem to work the best.  Because of that I am requesting you add Remain in Motion to the pack cause the frames in that mod are far more mature and have more functionality.

Thanks,

Spacebuilder2020

Digtobuild Head Admin

**Comment by b0bst3r** [comment]
I'm trying not to add anymore mods, there's approx 190 mods in the pack with all the optionals loaded and 190 was my max I set myself.  Nothing stopping you adding it in though.

**Comment by spacebuilder2020** [comment]
Unfortunately, this is not for my personal benefit, but for a player on our server where I am staff.(digtobuild).  They were looking forward to the redpower frames and then they found that the frames were very hard to use and unwieldy.  Since digtobuild is a large public server, forcing everyone on the server to add a mod is impossible.
