### ISSUE TITLE
Mekanism Steel Process Broken by IC2

### ISSUE THREAD

**Issue by powerengineer** [BevoTechPack/BevoTechPack#969]
The Mekanism steel process is typically:
Iron + Coal -> Enriched Iron + Coal -> Steel Dust -> Steel Ingot

Industrial Craft 2 appears to have modified this process to:
Iron + Coal -> Enriched Iron + **Diamond Dust** -> **Refined Iron Ingot**

**Comment by powerengineer** [comment]
This is in BetaO.

**Comment by b0bst3r** [comment]
Wasn't IC2 that changed the recipe :)
