### ISSUE TITLE
Request: Armourer's Workshop

### ISSUE THREAD

**Issue by ftog-thorgal** [BevoTechPack/BevoTechPack#970]
I hope this is the correct place to post this, if not please let me know for future reference.

I would love to see the Armourer's Workshop mod added to BTP Reborn. In case you are not familiar with the mod, here is the official post for it: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2309193-wip-alpha-armourers-workshop-weapon-armour-skins

I would like the option to make custom gears, frames, and anything and everything related to tech factory decorations. While there are other mods (for example Decocraft) that give you decorating options, none are as flexible as AW is.

I am not aware of any issues - besides possible slight FPS drops if someone uses them a lot - and I don't think it will use up too many ID's either.

Hope to see this mod in an update, and keep up the excellent work of making this well balanced modpack.

**Comment by b0bst3r** [comment]
I'm trying not to add anymore mods, there's approx 190 mods in the pack with all the optionals loaded and 190 was my max I set myself.  Nothing stopping you adding it in though.
