### ISSUE TITLE
Growthcraft: Salt water

### ISSUE THREAD

**Issue by Nezraddin** [BevoTechPack/BevoTechPack#971]
Hello.

It seems that you cannot get salt water from ocean-biomes, which seems - from what I found as information - the only way to get salt water for making griowthcraft salt to make cheese.

Other salt cannot be used (seems the "materialSalt" ore-dictonary is the one the machine searches for).

**Comment by b0bst3r** [comment]
Nezraddin for your info https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/338 it's turned off by default.

**Comment by IceDragon200** [comment]
@Nezraddin To add to that, we use `foodSalt` for the cheese, I'll update it to accept `materialSalt` as well

**Comment by b0bst3r** [comment]
And I turned it back off since Pam's harvestcraft salt works just fine and is all over the place.
