### ISSUE TITLE
Game crashes while loading

### ISSUE THREAD

**Issue by KingZyler** [BevoTechPack/BevoTechPack#972]
whenever i try to play it it goes to 7/7 1/12 3/3 and then it just crashes right there, it also happens with all the other modpacks.

**Comment by b0bst3r** [comment]
pastebin logs please

**Comment by KingZyler** [comment]
what is that?

**Comment by b0bst3r** [comment]
atlauncher has an "upload log" button on the launcher console, press it and copy the link it puts in the console to here.  Also check the crashlogs folder after you click the "open folder" button on the pack listed in the launcher.  If you find a crashlog with the right date/time for what's happening, copy the contents to pastebin.com and submit it and then copy the link to here.

**Comment by KingZyler** [comment]
http://paste.atlauncher.com/view/591c26e3 here is the link and i couldnt find a crashlog

**Comment by b0bst3r** [comment]
Can you leave it longer before killing MC and see what happens, I see nothing wrong in that log.

**Comment by KingZyler** [comment]
ok

**Comment by KingZyler** [comment]
http://paste.atlauncher.com/view/122c15d3 here it is

**Comment by b0bst3r** [comment]
Can you leave it 10 mins, I want to know if it carrys on or stays like that.

**Comment by KingZyler** [comment]
ill try

**Comment by KingZyler** [comment]
http://paste.atlauncher.com/view/90f94e37 i accidentally left it on over night

**Comment by b0bst3r** [comment]
Do you use McAfee or K9 web protection software on your PC.  If not what Antivirus do you use?

**Comment by KingZyler** [comment]
i use the norton antivirus

**Comment by b0bst3r** [comment]
Try disabling it and see if it runs then, all investigations are leading me to believe it's AV based issue.

**Comment by KingZyler** [comment]
ok

**Comment by KingZyler** [comment]
it didnt work
