### ISSUE TITLE
Expanding the Quest book

### ISSUE THREAD

**Issue by Landrash** [BevoTechPack/BevoTechPack#974]
@b0bst3r Is there any intresset/plans in expanding the quest book as it is today?
There's plenty of mods that could have quest lines like the one for Magneticraft.

Just on the top of my head I would love to see for example some of the more unused mods like **Pressure Pipes**, **Refined Relocation**, **Railcraft** have their own quest lines.

**Comment by b0bst3r** [comment]
No further plans on expanding the questline as I've moved onto building/testing/reporting bugs for 1.9 mods so I can build a pack on 1.9 mods
