### ISSUE TITLE
No Nether Fortress generated?

### ISSUE THREAD

**Issue by KollinsPlays** [BevoTechPack/BevoTechPack#975]
I'm using BTP-Reborn-BetaO and have not been able to find a Nether Fortress in the nether. I have about a 2,000 x 2,000 block area of The Nether mapped out and have found no trace of a fortress.  This is my 2nd time in The Nether in this pack, the 1st time was on BetaK or BetaL where I didn't explore much, just went in and gathered glowstone and quartz that spawned right by my portal.

Am I just having bad luck, or is there a problem with Nether Fortresses in the terrain gen in the pack?

**Comment by b0bst3r** [comment]
It's just bad luck we've had no issues finding nether fortresses.
