### ISSUE TITLE
Chapter 3 of quest oddness

### ISSUE THREAD

**Issue by meradudd** [BevoTechPack/BevoTechPack#976]
In the first, I would like to say how much I have enjoyed this pack and working through things.

Chapter 3 (the Mekanism quest line) is flummoxing me.  It says that I have completed 12/12 quests, but the quest-line is 86% complete.  That would intimate that there are two more quests to finish, but they aren't showing up.  I've burned through the rest of the quests and even tried using the 'admin HQM book', but no love.  Advice/help would be most appreciated.

**Comment by Landrash** [comment]
There's a hidden one that unlocks when you hold a certain item.

If you down the IC2 tech tree you undoubtedly hold it at least once.,
