### ISSUE TITLE
Storage Drawer messing first Item ID up

### ISSUE THREAD

**Issue by exor23** [BevoTechPack/BevoTechPack#977]
Getting items from a drawer give the first item a diffrent ID. if I have a drawer with three wood inside and try to pick up all three of them (by left-clicking on by one) then in the inventory there will be a stack of 2 woods and 1 wood which doesnt stack with the other of the same woods.

Step by Step to repreduce bug:
- place any drawer storage down
- put at least 2 or more of a item in the drawer (like wood)
- get at least 2 or more of the items, placed in the drawer back by left clicking
- try to stack the 2 or more items together --> bug

looks like the first item taken from the drawer has another id or item value.
sorry for my english, havent used it long time

**Comment by ftog-thorgal** [comment]
This doesn't seem to be limited to Storage Drawers. We are having this problem with Jabba barrels also. Furthermore, this even happens when you harvest industrial hemp. The first one doesn't stack with the rest of the ones you harvest. We figure out after a while that anything you do with an empty hand this happens. If you withdraw from barrels/drawers/harvest with an item in your hand this doesn't happen.

**Comment by McSharidan** [comment]
We are having similar issues, though from what I can see it's an inventory problem. Tooltips don't show any ID changes, however items picked up that get placed in the toolbar, refuse to stack with items in non-toolbar slots.

To test this, I split a stack of items in 4 slots in my toolbar. I then opened up my inventory and moved one of the slots up into the other part of the inventory. Then I moved that stack back down into the toolbar and then I tried to re-stack those 4 slots. The 3 untouched slots stacked up as normal but the 4th slot now will not stack with the remaining items of same type. This issue affects all items being moved to/from the toolbar and none of them appear to change IDs.

**Comment by b0bst3r** [comment]
Which pack version?

**Comment by McSharidan** [comment]
Latest release on ATL: BevoP for 1.7.10

**Comment by b0bst3r** [comment]
That item that will not stack gets withTag({Speed:0, Ticks:0}) added to it, this may take some finding as to what's doing this.

**Comment by Xfel** [comment]
I ran a short string constant search; it seems to be caused by Flaxbeard's Steam Power.

**Comment by b0bst3r** [comment]
Yeah I just completed a trial and error swapping mods in/out with the prev update and yep flaxbeards it is.

**Comment by Xfel** [comment]
Aaand it's already fixed: https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/issues/389

**Comment by b0bst3r** [comment]
Yeah but there's no release with the fix in, so will bring a p-hotfix to roll it back

**Comment by exor23** [comment]
this was pretty fast solution. thx for ur help.. ure amazing
