### ISSUE TITLE
Mekanism Fusion Reactor multiplier?

### ISSUE THREAD

**Issue by ftog-thorgal** [BevoTechPack/BevoTechPack#978]
One of the players on our server recently build a Mekanism Fusion Reactor and we noticed how ludicrous the power output of it is in BTP. I previous packs when I built these reactors you used to get 200,000 RF/t per 2 injection rate. So 200k at 2, 400k at 4, and so on.

This players Fusion reactor with an injection rate of 2 produces 3,190,000 RF/t. That is 16 times the output of the default Mekanism setting. I was wondering if this was intended or a config oversight?

**Comment by ftog-thorgal** [comment]
Before anyone mentions that it produces more during the initial laser blast, I am aware of that. During the initial laser reaction the reactor produced almost 40 million RF/t. It has since leveled at the normal temperature.

**Comment by b0bst3r** [comment]
Are you measuring the reactor output or from cables, as Mekanism has one of the most rediculous mechanics on energy pipes in any mod I've seen.

See here for reference - https://github.com/aidancbrady/Mekanism/issues/3159

**Comment by ftog-thorgal** [comment]
I measured it with a EnderIO creative capacitor bank set to show Input on one of the faces.

**Comment by b0bst3r** [comment]
I tested default configs with my configs, apart from the changes I made (none to do with the power multiplier) I don't see how this is the pack unless another mod has changed the figures (unlikely).  Quick question what version are you comparing it with as Aidan has made some siginificant changes in the last couple of versions.

**Comment by Vankka2** [comment]
Hey Thor if you were wondering we had a chemical mixer (or what ever) putting additional DT-Fuel in the reactor.
