### ISSUE TITLE
Recipe for Iron Heat Coil/Magneticraft replaced by Iron Trapdoor/Malisis' Doors

### ISSUE THREAD

**Issue by Kackra** [BevoTechPack/BevoTechPack#979]
When we try to craft an Iron Heat Coil 6194 from Magneticraft it only lets us make an Iron Trapdoor 2239 from Malisis' Doors. The other Heat Coils seem to work fine. I was unsure how I might be able to fix this problem.

**Comment by b0bst3r** [comment]
This was fixed ages back what version of the pack are you running?

**Comment by Kackra** [comment]
The newest one BetaP-Hotfix

**Comment by b0bst3r** [comment]
Sounds like your scripts arent' running do a /mt reload (enable Lan play with cheats if in SSP).  If you play on a server get an admin to do /mt reload.  

If neither works check the minecraft\scripts folder for md.zs.

**Comment by Kackra** [comment]
Ok I will try that thank you
