### ISSUE TITLE
Matter Overdrive: Matter Scanner crashes game

### ISSUE THREAD

**Issue by TvL2386** [BevoTechPack/BevoTechPack#981]
When having a Matter Scanner charged/bound in a Pattern Storage (with a single Pattern Drive (not sure if relevant)), the game crashes when you press 'C' to open the Matter Scanner GUI.

The game also crashes when scanning (right click with Matter Scanner in the hand)  a gold ingot that is lying on the ground.

I noticed sometimes the GUI does pop up... Crashes don't seem to be consistent...

[crashes.zip](https://github.com/BevoTechPack/BevoTechPack/files/253433/crashes.zip)

Not sure if you can reproduce.
We run a server with BTP-Reborn-BetaO. We have all mods except for Ruins.
The hoster has also added the following mods: https://www.dropbox.com/s/gm93ekc212ctbjx/Bevo-24-4.zip?dl=0

**Comment by TvL2386** [comment]
I reproduced it with the latest version without having external mods enabled. It was a single player game super flat. 

I have Bevo's Tech Pack BTP-Reborn-BetaP-Hofix with this sharecode: 9O9yoY5H

When trying to scan a working Basic Universal Cable from Mekanism the game crashed.

[fml-client-1.zip](https://github.com/BevoTechPack/BevoTechPack/files/253480/fml-client-1.zip)

**Comment by TvL2386** [comment]
I opened an issue at: https://github.com/simeonradivoev/MatterOverdrive/issues/498

**Comment by TvL2386** [comment]
![image](https://cloud.githubusercontent.com/assets/459167/15093454/14503040-1489-11e6-83d8-96329cfc2ce6.png)

**Comment by b0bst3r** [comment]
Check this isn't fixed in BetaQ (not yet released) as there's an update in builds but I couldn't find a changelog.
