### ISSUE TITLE
Quest Book Glitch

### ISSUE THREAD

**Issue by Teccy** [BevoTechPack/BevoTechPack#982]
I was doing the quest, (no name for the quest but it's in chapter 3) and within the quest, 5 blocks of unstable ingots, a builder's wand, and an ethereal sword, I submitted the quest which was supposed to give me 2 fully charged resonant tesseracts and half a stack of Cryo Stabilized-FluxDuct. The admins wouldn't do anything about it because "I had no way to prove it" and didn't give me my items back (not to mention I was new and my resources were about zero at that point...

**Comment by b0bst3r** [comment]
I just tested the quest and it worked fine so I don't know what else you want me to do.
