### ISSUE TITLE
crash when trying to modify Traveller's gear.

### ISSUE THREAD

**Issue by meradudd** [BevoTechPack/BevoTechPack#984]
I am trying to put moss on my traveller's boots.  When I put the boots in a crafting station,there is an instant crash.  When I try and use a tool station, it allows me to put in the boots, but when I try to modify them, it crashes.  Doesn't happen when I try to modify a TC tool, but it does happen when I try to modify the goggles or other traveller's gear.

Crash log of the first instance:
[crash-2016-05-15_11.47.11-client.txt](https://github.com/BevoTechPack/BevoTechPack/files/265160/crash-2016-05-15_11.47.11-client.txt)

Crash log of the second instance:
[crash-2016-05-15_11.51.37-client.txt](https://github.com/BevoTechPack/BevoTechPack/files/265162/crash-2016-05-15_11.51.37-client.txt)

**EDIT** This was not a problem in update O.  Currently running update Q.

**Comment by elifoster** [comment]
This is fixed as of FSP 0.29.3 :smile:

**Comment by b0bst3r** [comment]
Fixed in betaR (when it gets released)
