### ISSUE TITLE
Cannot make IndustrialCraft2 Overclocker Upgrade

### ISSUE THREAD

**Issue by arshiahf** [BevoTechPack/BevoTechPack#986]
Attempted to craft Overclock Upgrade from IndustrialCraft2 using both varieties of recipe, game would not make it.

**Comment by Sil3ntStorm** [comment]
#985 would fix that, if @b0bst3r decides to merge it.
That's actually the reason I did that patch, just went w/o creating an issue since I'd fixed it myself already and last time we did double work.

**Comment by b0bst3r** [comment]
Fixed in BetaR
