### ISSUE TITLE
Local server can't load.

### ISSUE THREAD

**Issue by roffa91** [BevoTechPack/BevoTechPack#987]
I used some blocks from ae2 and advanced automation and a few minutes after that the server crashed. Now I can't load the world. Please help if you can :)

http://pastebin.com/nh4KThxL

**Comment by b0bst3r** [comment]
If your server runs but crashes when you connect do the following:

Grab World Edit from here http://minecraft.curseforge.com/projects/worldedit/files
Put the world edit jar file in your SERVERS mod folder
Launch the server
In the server console type the following
/pos -227,24,53
/replace 0

Then try and connect, you should find the Progressive Automation chopper has vanished, this is correct as it was causing the crash.

Before replacing the chopper, stop or move your Progressive Automation Chopper away from the Thaumcraft trees it's trying to cut down as that looks like what caused the crash.

If you aren't running a local server and running in LAN Mode then things get tricky, I'll wait to hear back from you before we go any further.

**Comment by roffa91** [comment]
Thanks for your response, mate :) The server crashes after i press launch, but before the world loads. Can the World Edit still help med?

**Comment by b0bst3r** [comment]
You're in single player then not on or running a server?

**Comment by roffa91** [comment]
Yeah, it's a LAN server

**Comment by b0bst3r** [comment]
ok you're not quite screwed yet, talking you through using world edit to load your map and edit the block out is near on impossible, so, instead try this:

Edit config\forge.cfg and change the below to true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=false

then try loading your world, if it loads, save and quit then change it back to false.

**Comment by roffa91** [comment]
OMG, you are my hero <3 It worked! Thank you so much :):):)

**Comment by b0bst3r** [comment]
Don't try and use progressive automation chopper on thaumcraft trees or it will happen again.

**Comment by b0bst3r** [comment]
Fixed in Progressive Automation 1.6.35 will be added to next update
