### ISSUE TITLE
Mekanism v9 : An actually usable Energy Tablet cannot be crafted

### ISSUE THREAD

**Issue by Giovanni-NL** [BevoTechPack/BevoTechPack#988]
With the Mekanism update in release BetaR of this pack, the item Energy Tablet (id=5645) cannot be crafted.  It shows up in NEI, but there is no recipe in NEI for it.

You _can_ craft item 5645:100 using the recipe for the Energy Tablet.  That item, however, cannot be used for further crafting i.e. to craft the Mekanism Laser (id=1644:13)  

![image](https://cloud.githubusercontent.com/assets/4085882/15551570/e22656a8-22b6-11e6-8652-e1b749467dab.png)

**Comment by b0bst3r** [comment]
BetaR-Hotfix coming up
