### ISSUE TITLE
Mekanism Dynamic Glass causes crash

### ISSUE THREAD

**Issue by arshiahf** [BevoTechPack/BevoTechPack#991]
When you have a fully completed dynamic tank and right click the dynamic glass, it causes the game to crash

**Comment by b0bst3r** [comment]
crash log?

**Comment by arshiahf** [comment]
[Crash Log Dynamic Glass.txt](https://github.com/BevoTechPack/BevoTechPack/files/285175/Crash.Log.Dynamic.Glass.txt)

Sorry about that, been a while since I worked tech

**Comment by b0bst3r** [comment]
That's the forge log, need the crash log.

**Comment by arshiahf** [comment]
No regular crash log was generated, it just disconnected me from my single player game as though it was a server when I right-clicked it

**Comment by b0bst3r** [comment]
Mod Devs reply was to break the glass and replace
