### ISSUE TITLE
Cannot craft select Mekanism machines

### ISSUE THREAD

**Issue by arshiahf** [BevoTechPack/BevoTechPack#992]
Thus far, I've found I cannot craft Rotary Condensentrator, Chemical Dissolution Chamber, Chemical Washer, and Chemical Crystallizer outside of creative mode, making the 5x ore processing impossible, as well as crafting an induction matrix

**Comment by b0bst3r** [comment]
Which version of the pack are you playing?

**Comment by arshiahf** [comment]
Version R

**Comment by b0bst3r** [comment]
Suggest you update to R-Hotfix I can craft those no problem apart from the induction blocks which I know about.

**Comment by arshiahf** [comment]
Actually, looking at it, I am on BetaR-Hotfix. For some reason, it refuses to allow me to craft those machines, regardless

**Comment by b0bst3r** [comment]
SSP or SMP?

**Comment by arshiahf** [comment]
Not sure what those acronyms stand for

**Comment by b0bst3r** [comment]
Survival Single Player - Survival MultiPlayer

**Comment by arshiahf** [comment]
Yep. Playing survival on single. Updated everything, on the most current hotfix, have fully updated Java and Windows, still can't craft them in my instance

**Comment by arshiahf** [comment]
Also cannot make a Chemical Infuser, I just discovered

**Comment by arshiahf** [comment]
Discovered the issue. You cannot create the machines using tanks made before the most recent update.

**Comment by b0bst3r** [comment]
Ahh that explains why I can make them :)

**Comment by b0bst3r** [comment]
from  aidancbrady click link above to see reply

"Emptying the gas tank before recipe use should fix this issue. It's likely a result of the removal of item damage-based gas displays in item form."
