### ISSUE TITLE
Disappearing Laser Foci

### ISSUE THREAD

**Issue by KollinsPlays** [BevoTechPack/BevoTechPack#993]
Honestly I have just started using the MFR laser drill,prior to betaR but since updating to BetaR hotfix, the laser foci in an MFR Laser disappear each time I log out. This happened in my survival world and I was able to re-create it in a creative world. I can craft laser foci, store them in chests and player inventory and place them inside an MFR Laser. After logging out, I still have laser foci in player inventory and chests, but any laser foci that was in a Laser will disappear.

**Comment by b0bst3r** [comment]
Will be fixed in next MFR release
