### ISSUE TITLE
pneumaticCraft Causing crash

### ISSUE THREAD

**Issue by SkippTekk** [BevoTechPack/BevoTechPack#997]
Hey guys, i have been running a server for the latest pack that you guys provided. it updated perfectly fine 3 days ago (that's when i updated and skipped the hotfix), the server loaded PERFECTLY fine then it suddenly crashed about 4 hours ago. 

Steps to fix?, removed pneumaticCraft and the server loads perfectly fine.

Error log. http://pastebin.com/KY2kwKYz

This server has been loaded on my own personal machine, i was able to give it 10gb, still had the issue, removed the mod and it loaded perfectly fine. not sure what is wrong with it.

**Comment by b0bst3r** [comment]
Reinstall the client then delete the config folder on your server, then copy the config folder from your client to your server and try again.

**Comment by SkippTekk** [comment]
sure, ill give that a go.

**Comment by SkippTekk** [comment]
Thanks it worked :D
