### ISSUE TITLE
Divination sigil graphical bug

### ISSUE THREAD

**Issue by Chocobro** [BevoTechPack/BevoTechPack#999]
![bevostechback-betar-issue999](https://cloud.githubusercontent.com/assets/5677255/15806171/716e7a9e-2b35-11e6-8a93-b74d209daf6c.png)
hovering over a botania runic altar with blood magic's divination sigil causes the divination ui to have a white background appear. the divination ui is otherwise transparent.

edit: this happens only when there are items inside the runic altar.

**Comment by b0bst3r** [comment]
Pictures please (you can attach them in this issue), also pack version and are you using Optifine?

**Comment by Chocobro** [comment]
all optional mods for BetaT are installed. this is in SMP - i haven't installed optifine, unless it's included in the optionals.
pictures added to the OP.
